# Generated by Django 3.1.7 on 2022-08-01 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendorRecon', '0015_batchmaster_frequencymaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchmaster',
            name='processing_layer_id',
        ),
        migrations.RemoveField(
            model_name='frequencymaster',
            name='processing_layer_id',
        ),
        migrations.AddField(
            model_name='vendormaster',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendorRecon.batchmaster', verbose_name='Batch Id (Auto Generated)'),
        ),
        migrations.AddField(
            model_name='vendormaster',
            name='frequency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendorRecon.frequencymaster', verbose_name='Frequency Id (Auto Generated)'),
        ),
    ]
