# Generated by Django 3.1.7 on 2022-09-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorRecon', '0016_auto_20220801_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalClosingBalances',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenants_id', models.PositiveIntegerField(null=True, verbose_name='Tenants Id (Business Module - Tenant Id)')),
                ('groups_id', models.PositiveIntegerField(null=True, verbose_name='Groups Id (Business Module - Groups Id)')),
                ('entities_id', models.PositiveIntegerField(null=True, verbose_name='Entities Id (Business Module - Entities Id)')),
                ('m_processing_layer_id', models.PositiveIntegerField(null=True, verbose_name='M Processing Layer Id')),
                ('m_processing_sub_layer_id', models.PositiveIntegerField(null=True, verbose_name='M Processing Sub Layer Id')),
                ('processing_layer_id', models.PositiveIntegerField(null=True, verbose_name='Processing Layer Id')),
                ('external_closing_date', models.CharField(max_length=32, null=True, verbose_name='Closing Date')),
                ('external_closing_balance', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Closing Balance')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Closed ?')),
                ('approved_by', models.PositiveIntegerField(null=True, verbose_name='Approved By')),
                ('approved_date', models.CharField(max_length=32, null=True, verbose_name='Approved Date')),
            ],
            options={
                'db_table': 'external_closing_balances',
            },
        ),
        migrations.CreateModel(
            name='InternalClosingBalances',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenants_id', models.PositiveIntegerField(null=True, verbose_name='Tenants Id (Business Module - Tenant Id)')),
                ('groups_id', models.PositiveIntegerField(null=True, verbose_name='Groups Id (Business Module - Groups Id)')),
                ('entities_id', models.PositiveIntegerField(null=True, verbose_name='Entities Id (Business Module - Entities Id)')),
                ('m_processing_layer_id', models.PositiveIntegerField(null=True, verbose_name='M Processing Layer Id')),
                ('m_processing_sub_layer_id', models.PositiveIntegerField(null=True, verbose_name='M Processing Sub Layer Id')),
                ('processing_layer_id', models.PositiveIntegerField(null=True, verbose_name='Processing Layer Id')),
                ('internal_closing_date', models.CharField(max_length=32, null=True, verbose_name='Closing Date')),
                ('internal_closing_balance', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Closing Balance')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Closed ?')),
                ('approved_by', models.PositiveIntegerField(null=True, verbose_name='Approved By')),
                ('approved_date', models.CharField(max_length=32, null=True, verbose_name='Approved Date')),
            ],
            options={
                'db_table': 'internal_closing_balances',
            },
        ),
    ]
