# Generated by Django 3.1.7 on 2022-07-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0013_targetfiledefinitions_field_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionLogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenants_id', models.PositiveIntegerField(verbose_name='Tenants Id (Business Module - Tenant Id)')),
                ('groups_id', models.PositiveIntegerField(verbose_name='Groups Id (Business Module - Groups Id)')),
                ('entities_id', models.PositiveIntegerField(verbose_name='Entities Id (Business Module - Entities Id)')),
                ('m_processing_layer_id', models.PositiveIntegerField(verbose_name='M Processing Layer Id (Business Module - M Processing Layer Id)')),
                ('m_processing_sub_layer_id', models.PositiveIntegerField(verbose_name='M Processing Sub Layer Id (Business Module - M Processing Sub Layer Id)')),
                ('processing_layer_id', models.PositiveIntegerField(verbose_name='Processing Layer Id (Business Module - Processing Layer Id)')),
                ('start_date', models.DateTimeField(null=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(null=True, verbose_name='End Date')),
                ('status', models.CharField(max_length=64, null=True, verbose_name='Status')),
                ('duration', models.PositiveIntegerField(null=True, verbose_name='Duration')),
                ('comments', models.TextField(null=True, verbose_name='Comments')),
            ],
            options={
                'db_table': 'execution_logs',
            },
        )
    ]
