# Generated by Django 3.1.7 on 2022-07-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0014_auto_20220714_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionlogs',
            name='file_id',
            field=models.PositiveIntegerField(null=True, verbose_name='File Id (File Uploads - Id)'),
        ),
        migrations.AddField(
            model_name='executionlogs',
            name='gst_remittance_month',
            field=models.CharField(max_length=64, null=True, verbose_name='GST Remittance Month'),
        ),
        migrations.AddField(
            model_name='executionlogs',
            name='m_sources_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Sources Id (Sources _ Id)'),
        ),
        migrations.AddField(
            model_name='executionlogs',
            name='targets_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Target Id (Targets - Id)'),
        )
    ]
