# Generated by Django 3.1.7 on 2022-07-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0015_auto_20220714_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedefinitions',
            name='is_primary_date',
            field=models.BooleanField(default=False, verbose_name='Primary Date ?'),
        ),
        migrations.AddField(
            model_name='sourcedefinitions',
            name='is_status',
            field=models.BooleanField(default=False, verbose_name='Status ?'),
        ),
    ]
