# Generated by Django 3.1.7 on 2022-07-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0016_auto_20220714_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceRelations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenants_id', models.PositiveIntegerField(verbose_name='Tenants Id (Business Module - Tenant Id)')),
                ('groups_id', models.PositiveIntegerField(verbose_name='Groups Id (Business Module - Groups Id)')),
                ('entities_id', models.PositiveIntegerField(verbose_name='Entities Id (Business Module - Entities Id)')),
                ('m_processing_layer_id', models.PositiveIntegerField(verbose_name='M Processing Layer Id (Business Module - M Processing Layer Id)')),
                ('m_processing_sub_layer_id', models.PositiveIntegerField(verbose_name='M Processing Sub Layer Id (Business Module - M Processing Sub Layer Id)')),
                ('processing_layer_id', models.PositiveIntegerField(verbose_name='Processing Layer Id (Business Module - Processing Layer Id)')),
                ('m_sources_id', models.PositiveIntegerField(verbose_name='M Sources Id (Auto Generated)')),
                ('is_related', models.BooleanField(default=False, verbose_name='Related (Yes/No)')),
                ('m_source_relation_id', models.PositiveIntegerField(verbose_name='M Sources Id (Auto Generated)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('created_date', models.CharField(max_length=32, null=True, verbose_name='Created Date')),
                ('modified_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('modified_date', models.CharField(max_length=32, null=True, verbose_name='Modified Date')),
            ],
            options={
                'db_table': 'source_relations',
            },
        ),
        migrations.AddField(
            model_name='targetfiledefinitions',
            name='is_primary_date',
            field=models.BooleanField(default=False, verbose_name='Primary Date ?'),
        ),
        migrations.AddField(
            model_name='targetfiledefinitions',
            name='is_status',
            field=models.BooleanField(default=False, verbose_name='Status ?'),
        ),
        migrations.AddField(
            model_name='targetfiledefinitions',
            name='is_unique',
            field=models.BooleanField(default=False, verbose_name='Unique ?'),
        ),
    ]
