# Generated by Django 3.1.7 on 2022-07-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0018_auto_20220718_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcerelations',
            name='m_source_name',
            field=models.CharField(default=1, max_length=64, verbose_name='M Sources Name'),
            preserve_default=False,
        ),
    ]
