# Generated by Django 3.1.7 on 2022-09-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0019_auto_20220718_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='is_related',
            field=models.BooleanField(null=True, verbose_name='Related (Yes/No)'),
        ),
    ]
