from django.db import models

# Create your models here.

class TransactionExternalRecords(models.Model):
    class Meta:
        db_table = "t_external_records"

    external_records_id = models.AutoField(primary_key=True)
    tenants_id = models.PositiveIntegerField(verbose_name="Tenants Id (Business Module - Tenant Id)", null=True)
    groups_id = models.PositiveIntegerField(verbose_name="Groups Id (Business Module - Groups Id)", null=True)
    entities_id = models.PositiveIntegerField(verbose_name="Entities Id (Business Module - Entities Id)", null=True)
    m_processing_layer_id = models.PositiveIntegerField(verbose_name="M Processing Layer Id", null=True)
    m_processing_sub_layer_id = models.PositiveIntegerField(verbose_name="M Processing Sub Layer Id", null=True)
    processing_layer_id = models.PositiveIntegerField(verbose_name="Processing Layer Id", null=True)
    file_uploads_id = models.PositiveIntegerField(verbose_name="File Uploads Id (Recon Module - File Uploads Id)", null=True)
    m_sources_id = models.PositiveIntegerField(verbose_name="Sources Id (Sources Module - Sources Id)", null=True)
    staging_row_id = models.PositiveIntegerField(verbose_name="Staging Row Id (Staging Table - Row Id)", null=True)
    m_source_name = models.CharField(max_length=64, verbose_name="Source Name", null=True)
    ext_match_type_1 = models.CharField(max_length=32, verbose_name="Match Type 1", null=True)
    ext_match_type_2 = models.CharField(max_length=32, verbose_name="Match Type 2", null=True)
    ext_match_type_3 = models.CharField(max_length=32, verbose_name="Match Type 3", null=True)
    ext_match_type_4 = models.CharField(max_length=32, verbose_name="Match Type 4", null=True)
    ext_match_type_5 = models.CharField(max_length=32, verbose_name="Match Type 5", null=True)
    ext_processing_status_1 = models.CharField(max_length=32, verbose_name="Processing Status 1", null=True)
    ext_processing_status_2 = models.CharField(max_length=32, verbose_name="Processing Status 2", null=True)
    ext_processing_status_3 = models.CharField(max_length=32, verbose_name="Processing Status 3", null=True)
    ext_processing_status_4 = models.CharField(max_length=32, verbose_name="Processing Status 4", null=True)
    ext_processing_status_5 = models.CharField(max_length=32, verbose_name="Processing Status 5", null=True)
    processing_date_time = models.CharField(max_length=64, verbose_name="Processing Date Time", null=True)
    ext_reference_text_1 = models.TextField(verbose_name="Reference Text 1", null=True)
    ext_reference_text_2 = models.TextField(verbose_name="Reference Text 2", null=True)
    ext_reference_text_3 = models.TextField(verbose_name="Reference Text 3", null=True)
    ext_reference_text_4 = models.TextField(verbose_name="Reference Text 4", null=True)
    ext_reference_text_5 = models.TextField(verbose_name="Reference Text 5", null=True)
    ext_reference_text_6 = models.TextField(verbose_name="Reference Text 6", null=True)
    ext_reference_text_7 = models.TextField(verbose_name="Reference Text 7", null=True)
    ext_reference_text_8 = models.TextField(verbose_name="Reference Text 8", null=True)
    ext_reference_text_9 = models.TextField(verbose_name="Reference Text 9", null=True)
    ext_reference_text_10 = models.TextField(verbose_name="Reference Text 10", null=True)
    ext_reference_text_11 = models.TextField(verbose_name="Reference Text 11", null=True)
    ext_reference_text_12 = models.TextField(verbose_name="Reference Text 12", null=True)
    ext_reference_text_13 = models.TextField(verbose_name="Reference Text 13", null=True)
    ext_reference_text_14 = models.TextField(verbose_name="Reference Text 14", null=True)
    ext_reference_text_15 = models.TextField(verbose_name="Reference Text 15", null=True)
    ext_reference_text_16 = models.TextField(verbose_name="Reference Text 16", null=True)
    ext_reference_text_17 = models.TextField(verbose_name="Reference Text 17", null=True)
    ext_reference_text_18 = models.TextField(verbose_name="Reference Text 18", null=True)
    ext_reference_text_19 = models.TextField(verbose_name="Reference Text 19", null=True)
    ext_reference_text_20 = models.TextField(verbose_name="Reference Text 20", null=True)
    ext_reference_text_21 = models.TextField(verbose_name="Reference Text 21", null=True)
    ext_reference_text_22 = models.TextField(verbose_name="Reference Text 22", null=True)
    ext_reference_text_23 = models.TextField(verbose_name="Reference Text 23", null=True)
    ext_reference_text_24 = models.TextField(verbose_name="Reference Text 24", null=True)
    ext_reference_text_25 = models.TextField(verbose_name="Reference Text 25", null=True)
    ext_reference_text_26 = models.TextField(verbose_name="Reference Text 26", null=True)
    ext_reference_text_27 = models.TextField(verbose_name="Reference Text 27", null=True)
    ext_reference_text_28 = models.TextField(verbose_name="Reference Text 28", null=True)
    ext_reference_text_29 = models.TextField(verbose_name="Reference Text 29", null=True)
    ext_reference_text_30 = models.TextField(verbose_name="Reference Text 30", null=True)
    ext_reference_text_31 = models.TextField(verbose_name="Reference Text 31", null=True)
    ext_reference_text_32 = models.TextField(verbose_name="Reference Text 32", null=True)
    ext_reference_text_33 = models.TextField(verbose_name="Reference Text 33", null=True)
    ext_reference_text_34 = models.TextField(verbose_name="Reference Text 34", null=True)
    ext_reference_text_35 = models.TextField(verbose_name="Reference Text 35", null=True)
    ext_reference_text_36 = models.TextField(verbose_name="Reference Text 36", null=True)
    ext_reference_text_37 = models.TextField(verbose_name="Reference Text 37", null=True)
    ext_reference_text_38 = models.TextField(verbose_name="Reference Text 38", null=True)
    ext_reference_text_39 = models.TextField(verbose_name="Reference Text 39", null=True)
    ext_reference_text_40 = models.TextField(verbose_name="Reference Text 40", null=True)
    ext_reference_text_41 = models.TextField(verbose_name="Reference Text 41", null=True)
    ext_reference_text_42 = models.TextField(verbose_name="Reference Text 42", null=True)
    ext_reference_text_43 = models.TextField(verbose_name="Reference Text 43", null=True)
    ext_reference_text_44 = models.TextField(verbose_name="Reference Text 44", null=True)
    ext_reference_text_45 = models.TextField(verbose_name="Reference Text 45", null=True)
    ext_reference_text_46 = models.TextField(verbose_name="Reference Text 46", null=True)
    ext_reference_text_47 = models.TextField(verbose_name="Reference Text 47", null=True)
    ext_reference_text_48 = models.TextField(verbose_name="Reference Text 48", null=True)
    ext_reference_text_49 = models.TextField(verbose_name="Reference Text 49", null=True)
    ext_reference_text_50 = models.TextField(verbose_name="Reference Text 50", null=True)
    ext_reference_text_51 = models.TextField(verbose_name="Reference Text 51", null=True)
    ext_reference_text_52 = models.TextField(verbose_name="Reference Text 52", null=True)
    ext_reference_text_53 = models.TextField(verbose_name="Reference Text 53", null=True)
    ext_reference_text_54 = models.TextField(verbose_name="Reference Text 54", null=True)
    ext_reference_text_55 = models.TextField(verbose_name="Reference Text 55", null=True)
    ext_reference_text_56 = models.TextField(verbose_name="Reference Text 56", null=True)
    ext_reference_text_57 = models.TextField(verbose_name="Reference Text 57", null=True)
    ext_reference_text_58 = models.TextField(verbose_name="Reference Text 58", null=True)
    ext_reference_text_59 = models.TextField(verbose_name="Reference Text 59", null=True)
    ext_reference_text_60 = models.TextField(verbose_name="Reference Text 60", null=True)
    ext_reference_date_time_1 = models.DateTimeField(verbose_name="Reference Date Time 1", null=True)
    ext_reference_date_time_2 = models.DateTimeField(verbose_name="Reference Date Time 2", null=True)
    ext_reference_date_time_3 = models.DateTimeField(verbose_name="Reference Date Time 3", null=True)
    ext_reference_date_time_4 = models.DateTimeField(verbose_name="Reference Date Time 4", null=True)
    ext_reference_date_time_5 = models.DateTimeField(verbose_name="Reference Date Time 5", null=True)
    ext_reference_date_time_6 = models.DateTimeField(verbose_name="Reference Date Time 6", null=True)
    ext_reference_date_time_7 = models.DateTimeField(verbose_name="Reference Date Time 7", null=True)
    ext_reference_date_time_8 = models.DateTimeField(verbose_name="Reference Date Time 8", null=True)
    ext_reference_date_time_9 = models.DateTimeField(verbose_name="Reference Date Time 9", null=True)
    ext_reference_date_time_10 = models.DateTimeField(verbose_name="Reference Date Time 10", null=True)
    ext_debit_amount = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Debit Amount", null=True)
    ext_credit_amount = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Credit Amount", null=True)
    ext_amount_1 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Amount 1", null=True)
    ext_amount_2 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Amount 2", null=True)
    ext_amount_3 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Amount 3", null=True)
    ext_amount_4 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Amount 4", null=True)
    ext_amount_5 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Amount 5", null=True)
    ext_amount_6 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Amount 6", null=True)
    ext_amount_7 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Amount 7", null=True)
    ext_amount_8 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Amount 8", null=True)
    ext_amount_9 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Amount 9", null=True)
    ext_amount_10 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Amount 10", null=True)
    ext_amount_11 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Amount 11", null=True)
    ext_amount_12 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Amount 12", null=True)
    ext_amount_13 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Amount 13", null=True)
    ext_amount_14 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Amount 14", null=True)
    ext_amount_15 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Amount 15", null=True)
    ext_extracted_text_1 = models.TextField(verbose_name="Extracted Text 1", null=True)
    ext_extracted_text_2 = models.TextField(verbose_name="Extracted Text 2", null=True)
    ext_extracted_text_3 = models.TextField(verbose_name="Extracted Text 3", null=True)
    ext_extracted_text_4 = models.TextField(verbose_name="Extracted Text 4", null=True)
    ext_extracted_text_5 = models.TextField(verbose_name="Extracted Text 5", null=True)
    ext_extracted_text_6 = models.TextField(verbose_name="Extracted Text 6", null=True)
    ext_extracted_text_7 = models.TextField(verbose_name="Extracted Text 7", null=True)
    ext_extracted_text_8 = models.TextField(verbose_name="Extracted Text 8", null=True)
    ext_extracted_text_9 = models.TextField(verbose_name="Extracted Text 9", null=True)
    ext_extracted_text_10 = models.TextField(verbose_name="Extracted Text 10", null=True)
    ext_extracted_text_11 = models.TextField(verbose_name="Extracted Text 11", null=True)
    ext_extracted_text_12 = models.TextField(verbose_name="Extracted Text 12", null=True)
    ext_extracted_text_13 = models.TextField(verbose_name="Extracted Text 13", null=True)
    ext_extracted_text_14 = models.TextField(verbose_name="Extracted Text 14", null=True)
    ext_extracted_text_15 = models.TextField(verbose_name="Extracted Text 15", null=True)
    ext_extracted_text_16 = models.TextField(verbose_name="Extracted Text 16", null=True)
    ext_extracted_text_17 = models.TextField(verbose_name="Extracted Text 17", null=True)
    ext_extracted_text_18 = models.TextField(verbose_name="Extracted Text 18", null=True)
    ext_extracted_text_19 = models.TextField(verbose_name="Extracted Text 19", null=True)
    ext_extracted_text_20 = models.TextField(verbose_name="Extracted Text 20", null=True)
    ext_extracted_text_21 = models.TextField(verbose_name="Extracted Text 21", null=True)
    ext_extracted_text_22 = models.TextField(verbose_name="Extracted Text 22", null=True)
    ext_extracted_text_23 = models.TextField(verbose_name="Extracted Text 23", null=True)
    ext_extracted_text_24 = models.TextField(verbose_name="Extracted Text 24", null=True)
    ext_extracted_text_25 = models.TextField(verbose_name="Extracted Text 25", null=True)
    ext_extracted_text_26 = models.TextField(verbose_name="Extracted Text 26", null=True)
    ext_extracted_text_27 = models.TextField(verbose_name="Extracted Text 27", null=True)
    ext_extracted_text_28 = models.TextField(verbose_name="Extracted Text 28", null=True)
    ext_extracted_text_29 = models.TextField(verbose_name="Extracted Text 29", null=True)
    ext_extracted_text_30 = models.TextField(verbose_name="Extracted Text 30", null=True)
    internal_records_id = models.PositiveIntegerField(verbose_name="Internal Records Id", null=True)
    ext_contra_id = models.PositiveIntegerField(verbose_name="Contra Id", null=True)
    ext_generated_number_1 = models.PositiveIntegerField(verbose_name="Generated Number 1", null=True)
    ext_generated_number_2 = models.PositiveIntegerField(verbose_name="Generated Number 2", null=True)
    ext_generated_number_3 = models.PositiveIntegerField(verbose_name="Generated Number 3", null=True)
    ext_generated_number_4 = models.PositiveIntegerField(verbose_name="Generated Number 4", null=True)
    ext_generated_number_5 = models.PositiveIntegerField(verbose_name="Generated Number 5", null=True)
    ext_transaction_type_1 = models.CharField(max_length=32, verbose_name="Transaction Type 1", null=True)
    ext_transaction_type_2 = models.CharField(max_length=32, verbose_name="Transaction Type 2", null=True)
    ext_transaction_type_3 = models.CharField(max_length=32, verbose_name="Transaction Type 3", null=True)
    ext_transaction_type_4 = models.CharField(max_length=32, verbose_name="Transaction Type 4", null=True)
    ext_transaction_type_5 = models.CharField(max_length=32, verbose_name="Transaction Type 5", null=True)
    ext_record_status_1 = models.BooleanField(default=False, verbose_name="Record Status 1")
    ext_record_status_2 = models.BooleanField(default=False, verbose_name="Record Status 2")
    ext_record_status_3 = models.BooleanField(default=False, verbose_name="Record Status 3")
    ext_record_status_4 = models.BooleanField(default=False, verbose_name="Record Status 4")
    ext_record_status_5 = models.BooleanField(default=False, verbose_name="Record Status 5")
    ext_record_status_6 = models.BooleanField(default=False, verbose_name="Record Status 6")
    ext_record_status_7 = models.BooleanField(default=False, verbose_name="Record Status 7")
    ext_record_status_8 = models.BooleanField(default=False, verbose_name="Record Status 8")
    ext_record_status_9 = models.BooleanField(default=False, verbose_name="Record Status 9")
    ext_record_status_10 = models.BooleanField(default=False, verbose_name="Record Status 10")
    is_active = models.BooleanField(default=True, verbose_name="Active ?")
    created_by = models.PositiveSmallIntegerField(verbose_name="User Id", null=True)
    created_date = models.CharField(max_length=64, verbose_name="Created Date", null=True)
    modified_by = models.PositiveSmallIntegerField(verbose_name="User Id", null=True)
    modified_date = models.CharField(max_length=64, verbose_name="Modified Date", null=True)


class TransactionInternalRecords(models.Model):
    class Meta:
        db_table = "t_internal_records"

    internal_records_id = models.AutoField(primary_key=True)
    tenants_id = models.PositiveIntegerField(verbose_name="Tenants Id (Business Module - Tenant Id)", null=True)
    groups_id = models.PositiveIntegerField(verbose_name="Groups Id (Business Module - Groups Id)", null=True)
    entities_id = models.PositiveIntegerField(verbose_name="Entities Id (Business Module - Entities Id)", null=True)
    m_processing_layer_id = models.PositiveIntegerField(verbose_name="M Processing Layer Id", null=True)
    m_processing_sub_layer_id = models.PositiveIntegerField(verbose_name="M Processing Sub Layer Id", null=True)
    processing_layer_id = models.PositiveIntegerField(verbose_name="Processing Layer Id", null=True)
    file_uploads_id = models.PositiveIntegerField(verbose_name="File Uploads Id (Recon Module - File Uploads Id)", null=True)
    m_sources_id = models.PositiveIntegerField(verbose_name="Sources Id (Sources Module - Sources Id)", null=True)
    staging_row_id = models.PositiveIntegerField(verbose_name="Staging Row Id (Staging Table - Row Id)", null=True)
    m_source_name = models.CharField(max_length=64, verbose_name="Source Name", null=True)
    int_match_type_1 = models.CharField(max_length=32, verbose_name="Match Type 1", null=True)
    int_match_type_2 = models.CharField(max_length=32, verbose_name="Match Type 2", null=True)
    int_match_type_3 = models.CharField(max_length=32, verbose_name="Match Type 3", null=True)
    int_match_type_4 = models.CharField(max_length=32, verbose_name="Match Type 4", null=True)
    int_match_type_5 = models.CharField(max_length=32, verbose_name="Match Type 5", null=True)
    int_processing_status_1 = models.CharField(max_length=32, verbose_name="Processing Status 1", null=True)
    int_processing_status_2 = models.CharField(max_length=32, verbose_name="Processing Status 2", null=True)
    int_processing_status_3 = models.CharField(max_length=32, verbose_name="Processing Status 3", null=True)
    int_processing_status_4 = models.CharField(max_length=32, verbose_name="Processing Status 4", null=True)
    int_processing_status_5 = models.CharField(max_length=32, verbose_name="Processing Status 5", null=True)
    processing_date_time = models.CharField(max_length=64, verbose_name="Processing Date Time", null=True)
    int_reference_text_1 = models.TextField(verbose_name="Reference Text 1", null=True)
    int_reference_text_2 = models.TextField(verbose_name="Reference Text 2", null=True)
    int_reference_text_3 = models.TextField(verbose_name="Reference Text 3", null=True)
    int_reference_text_4 = models.TextField(verbose_name="Reference Text 4", null=True)
    int_reference_text_5 = models.TextField(verbose_name="Reference Text 5", null=True)
    int_reference_text_6 = models.TextField(verbose_name="Reference Text 6", null=True)
    int_reference_text_7 = models.TextField(verbose_name="Reference Text 7", null=True)
    int_reference_text_8 = models.TextField(verbose_name="Reference Text 8", null=True)
    int_reference_text_9 = models.TextField(verbose_name="Reference Text 9", null=True)
    int_reference_text_10 = models.TextField(verbose_name="Reference Text 10", null=True)
    int_reference_text_11 = models.TextField(verbose_name="Reference Text 11", null=True)
    int_reference_text_12 = models.TextField(verbose_name="Reference Text 12", null=True)
    int_reference_text_13 = models.TextField(verbose_name="Reference Text 13", null=True)
    int_reference_text_14 = models.TextField(verbose_name="Reference Text 14", null=True)
    int_reference_text_15 = models.TextField(verbose_name="Reference Text 15", null=True)
    int_reference_text_16 = models.TextField(verbose_name="Reference Text 16", null=True)
    int_reference_text_17 = models.TextField(verbose_name="Reference Text 17", null=True)
    int_reference_text_18 = models.TextField(verbose_name="Reference Text 18", null=True)
    int_reference_text_19 = models.TextField(verbose_name="Reference Text 19", null=True)
    int_reference_text_20 = models.TextField(verbose_name="Reference Text 20", null=True)
    int_reference_text_21 = models.TextField(verbose_name="Reference Text 21", null=True)
    int_reference_text_22 = models.TextField(verbose_name="Reference Text 22", null=True)
    int_reference_text_23 = models.TextField(verbose_name="Reference Text 23", null=True)
    int_reference_text_24 = models.TextField(verbose_name="Reference Text 24", null=True)
    int_reference_text_25 = models.TextField(verbose_name="Reference Text 25", null=True)
    int_reference_text_26 = models.TextField(verbose_name="Reference Text 26", null=True)
    int_reference_text_27 = models.TextField(verbose_name="Reference Text 27", null=True)
    int_reference_text_28 = models.TextField(verbose_name="Reference Text 28", null=True)
    int_reference_text_29 = models.TextField(verbose_name="Reference Text 29", null=True)
    int_reference_text_30 = models.TextField(verbose_name="Reference Text 30", null=True)
    int_reference_text_31 = models.TextField(verbose_name="Reference Text 31", null=True)
    int_reference_text_32 = models.TextField(verbose_name="Reference Text 32", null=True)
    int_reference_text_33 = models.TextField(verbose_name="Reference Text 33", null=True)
    int_reference_text_34 = models.TextField(verbose_name="Reference Text 34", null=True)
    int_reference_text_35 = models.TextField(verbose_name="Reference Text 35", null=True)
    int_reference_text_36 = models.TextField(verbose_name="Reference Text 36", null=True)
    int_reference_text_37 = models.TextField(verbose_name="Reference Text 37", null=True)
    int_reference_text_38 = models.TextField(verbose_name="Reference Text 38", null=True)
    int_reference_text_39 = models.TextField(verbose_name="Reference Text 39", null=True)
    int_reference_text_40 = models.TextField(verbose_name="Reference Text 40", null=True)
    int_reference_text_41 = models.TextField(verbose_name="Reference Text 41", null=True)
    int_reference_text_42 = models.TextField(verbose_name="Reference Text 42", null=True)
    int_reference_text_43 = models.TextField(verbose_name="Reference Text 43", null=True)
    int_reference_text_44 = models.TextField(verbose_name="Reference Text 44", null=True)
    int_reference_text_45 = models.TextField(verbose_name="Reference Text 45", null=True)
    int_reference_text_46 = models.TextField(verbose_name="Reference Text 46", null=True)
    int_reference_text_47 = models.TextField(verbose_name="Reference Text 47", null=True)
    int_reference_text_48 = models.TextField(verbose_name="Reference Text 48", null=True)
    int_reference_text_49 = models.TextField(verbose_name="Reference Text 49", null=True)
    int_reference_text_50 = models.TextField(verbose_name="Reference Text 50", null=True)
    int_reference_text_51 = models.TextField(verbose_name="Reference Text 51", null=True)
    int_reference_text_52 = models.TextField(verbose_name="Reference Text 52", null=True)
    int_reference_text_53 = models.TextField(verbose_name="Reference Text 53", null=True)
    int_reference_text_54 = models.TextField(verbose_name="Reference Text 54", null=True)
    int_reference_text_55 = models.TextField(verbose_name="Reference Text 55", null=True)
    int_reference_text_56 = models.TextField(verbose_name="Reference Text 56", null=True)
    int_reference_text_57 = models.TextField(verbose_name="Reference Text 57", null=True)
    int_reference_text_58 = models.TextField(verbose_name="Reference Text 58", null=True)
    int_reference_text_59 = models.TextField(verbose_name="Reference Text 59", null=True)
    int_reference_text_60 = models.TextField(verbose_name="Reference Text 60", null=True)
    int_reference_date_time_1 = models.DateTimeField(verbose_name="Reference Date Time 1", null=True)
    int_reference_date_time_2 = models.DateTimeField(verbose_name="Reference Date Time 2", null=True)
    int_reference_date_time_3 = models.DateTimeField(verbose_name="Reference Date Time 3", null=True)
    int_reference_date_time_4 = models.DateTimeField(verbose_name="Reference Date Time 4", null=True)
    int_reference_date_time_5 = models.DateTimeField(verbose_name="Reference Date Time 5", null=True)
    int_reference_date_time_6 = models.DateTimeField(verbose_name="Reference Date Time 6", null=True)
    int_reference_date_time_7 = models.DateTimeField(verbose_name="Reference Date Time 7", null=True)
    int_reference_date_time_8 = models.DateTimeField(verbose_name="Reference Date Time 8", null=True)
    int_reference_date_time_9 = models.DateTimeField(verbose_name="Reference Date Time 9", null=True)
    int_reference_date_time_10 = models.DateTimeField(verbose_name="Reference Date Time 10", null=True)
    int_debit_amount = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Debit Amount", null=True)
    int_credit_amount = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Credit Amount", null=True)
    int_amount_1 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Amount 1", null=True)
    int_amount_2 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Amount 2", null=True)
    int_amount_3 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Amount 3", null=True)
    int_amount_4 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Amount 4", null=True)
    int_amount_5 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Amount 5", null=True)
    int_amount_6 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Amount 6", null=True)
    int_amount_7 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Amount 7", null=True)
    int_amount_8 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Amount 8", null=True)
    int_amount_9 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Amount 9", null=True)
    int_amount_10 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Amount 10", null=True)
    int_amount_11 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Amount 11", null=True)
    int_amount_12 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Amount 12", null=True)
    int_amount_13 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Amount 13", null=True)
    int_amount_14 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Amount 14", null=True)
    int_amount_15 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Amount 15", null=True)
    int_extracted_text_1 = models.TextField(verbose_name="Extracted Text 1", null=True)
    int_extracted_text_2 = models.TextField(verbose_name="Extracted Text 2", null=True)
    int_extracted_text_3 = models.TextField(verbose_name="Extracted Text 3", null=True)
    int_extracted_text_4 = models.TextField(verbose_name="Extracted Text 4", null=True)
    int_extracted_text_5 = models.TextField(verbose_name="Extracted Text 5", null=True)
    int_extracted_text_6 = models.TextField(verbose_name="Extracted Text 6", null=True)
    int_extracted_text_7 = models.TextField(verbose_name="Extracted Text 7", null=True)
    int_extracted_text_8 = models.TextField(verbose_name="Extracted Text 8", null=True)
    int_extracted_text_9 = models.TextField(verbose_name="Extracted Text 9", null=True)
    int_extracted_text_10 = models.TextField(verbose_name="Extracted Text 10", null=True)
    int_extracted_text_11 = models.TextField(verbose_name="Extracted Text 11", null=True)
    int_extracted_text_12 = models.TextField(verbose_name="Extracted Text 12", null=True)
    int_extracted_text_13 = models.TextField(verbose_name="Extracted Text 13", null=True)
    int_extracted_text_14 = models.TextField(verbose_name="Extracted Text 14", null=True)
    int_extracted_text_15 = models.TextField(verbose_name="Extracted Text 15", null=True)
    int_extracted_text_16 = models.TextField(verbose_name="Extracted Text 16", null=True)
    int_extracted_text_17 = models.TextField(verbose_name="Extracted Text 17", null=True)
    int_extracted_text_18 = models.TextField(verbose_name="Extracted Text 18", null=True)
    int_extracted_text_19 = models.TextField(verbose_name="Extracted Text 19", null=True)
    int_extracted_text_20 = models.TextField(verbose_name="Extracted Text 20", null=True)
    int_extracted_text_21 = models.TextField(verbose_name="Extracted Text 21", null=True)
    int_extracted_text_22 = models.TextField(verbose_name="Extracted Text 22", null=True)
    int_extracted_text_23 = models.TextField(verbose_name="Extracted Text 23", null=True)
    int_extracted_text_24 = models.TextField(verbose_name="Extracted Text 24", null=True)
    int_extracted_text_25 = models.TextField(verbose_name="Extracted Text 25", null=True)
    int_extracted_text_26 = models.TextField(verbose_name="Extracted Text 26", null=True)
    int_extracted_text_27 = models.TextField(verbose_name="Extracted Text 27", null=True)
    int_extracted_text_28 = models.TextField(verbose_name="Extracted Text 28", null=True)
    int_extracted_text_29 = models.TextField(verbose_name="Extracted Text 29", null=True)
    int_extracted_text_30 = models.TextField(verbose_name="Extracted Text 30", null=True)
    external_records_id = models.PositiveIntegerField(verbose_name="Internal Records Id", null=True)
    int_contra_id = models.PositiveIntegerField(verbose_name="Contra Id", null=True)
    int_generated_number_1 = models.PositiveIntegerField(verbose_name="Generated Number 1", null=True)
    int_generated_number_2 = models.PositiveIntegerField(verbose_name="Generated Number 2", null=True)
    int_generated_number_3 = models.PositiveIntegerField(verbose_name="Generated Number 3", null=True)
    int_generated_number_4 = models.PositiveIntegerField(verbose_name="Generated Number 4", null=True)
    int_generated_number_5 = models.PositiveIntegerField(verbose_name="Generated Number 5", null=True)
    int_transaction_type_1 = models.CharField(max_length=32, verbose_name="Transaction Type 1", null=True)
    int_transaction_type_2 = models.CharField(max_length=32, verbose_name="Transaction Type 2", null=True)
    int_transaction_type_3 = models.CharField(max_length=32, verbose_name="Transaction Type 3", null=True)
    int_transaction_type_4 = models.CharField(max_length=32, verbose_name="Transaction Type 4", null=True)
    int_transaction_type_5 = models.CharField(max_length=32, verbose_name="Transaction Type 5", null=True)
    int_record_status_1 = models.BooleanField(default=False, verbose_name="Record Status 1")
    int_record_status_2 = models.BooleanField(default=False, verbose_name="Record Status 2")
    int_record_status_3 = models.BooleanField(default=False, verbose_name="Record Status 3")
    int_record_status_4 = models.BooleanField(default=False, verbose_name="Record Status 4")
    int_record_status_5 = models.BooleanField(default=False, verbose_name="Record Status 5")
    int_record_status_6 = models.BooleanField(default=False, verbose_name="Record Status 6")
    int_record_status_7 = models.BooleanField(default=False, verbose_name="Record Status 7")
    int_record_status_8 = models.BooleanField(default=False, verbose_name="Record Status 8")
    int_record_status_9 = models.BooleanField(default=False, verbose_name="Record Status 9")
    int_record_status_10 = models.BooleanField(default=False, verbose_name="Record Status 10")
    is_active = models.BooleanField(default=True, verbose_name="Active ?")
    created_by = models.PositiveSmallIntegerField(verbose_name="User Id", null=True)
    created_date = models.CharField(max_length=64, verbose_name="Created Date", null=True)
    modified_by = models.PositiveSmallIntegerField(verbose_name="User Id", null=True)
    modified_date = models.CharField(max_length=64, verbose_name="Modified Date", null=True)

class RecoSettings(models.Model):
    class Meta:
        db_table = "reco_settings"

    setting_id = models.AutoField(primary_key=True)
    tenants_id = models.PositiveIntegerField(verbose_name="Tenants Id", null=True)
    groups_id = models.PositiveIntegerField(verbose_name="Groups Id", null=True)
    entities_id = models.PositiveIntegerField(verbose_name="Entities Id", null=True)
    setting_key = models.CharField(max_length=32, verbose_name="Setting Key", null=True)
    setting_value = models.TextField(verbose_name="Setting Value", null=True)
    m_processing_layer_id = models.PositiveIntegerField(verbose_name="M Processing Layer Id", null=True)
    m_processing_sub_layer_id = models.PositiveIntegerField(verbose_name="M Processing Sub Layer Id", null=True)
    processing_layer_id = models.PositiveIntegerField(verbose_name="Processing Layer Id", null=True)
    is_active = models.BooleanField(default=True, verbose_name="Active ?")
    created_by = models.PositiveSmallIntegerField(verbose_name="User Id", null=True)
    created_date = models.CharField(max_length=64, verbose_name="Created Date", null=True)
    modified_by = models.PositiveSmallIntegerField(verbose_name="User Id", null=True)
    modified_date = models.CharField(max_length=64, verbose_name="Modified Date", null=True)

    def __str__(self):
        return self.setting_key

class RecoResults(models.Model):
    class Meta:
        db_table = "t_reco_results"

    t_reco_result_id = models.AutoField(primary_key=True)
    m_processing_layer_id = models.PositiveIntegerField(verbose_name="M Processing Layer Id", null=True)
    m_processing_sub_layer_id = models.PositiveIntegerField(verbose_name="M Processing Sub Layer Id", null=True)
    processing_layer_id = models.PositiveIntegerField(verbose_name="Processing Layer Id", null=True)
    t_external_records_id = models.PositiveIntegerField(verbose_name="External Records Id", null=True)
    t_internal_records_id = models.PositiveIntegerField(verbose_name="Internal Records Id", null=True)
    generated_number_1 = models.PositiveIntegerField(verbose_name="Generated Number 1", null=True)
    generated_number_2 = models.PositiveIntegerField(verbose_name="Generated Number 2", null=True)
    generated_number_3 = models.PositiveIntegerField(verbose_name="Generated Number 3", null=True)
    generated_number_4 = models.PositiveIntegerField(verbose_name="Generated Number 4", null=True)
    generated_number_5 = models.PositiveIntegerField(verbose_name="Generated Number 5", null=True)
    reco_result_status_1 = models.BooleanField(default=False, verbose_name="Reco Result Status 1")
    reco_result_status_2 = models.BooleanField(default=False, verbose_name="Reco Result Status 2")
    reco_result_status_3 = models.BooleanField(default=False, verbose_name="Reco Result Status 3")
    reco_result_status_4 = models.BooleanField(default=False, verbose_name="Reco Result Status 4")
    reco_result_status_5 = models.BooleanField(default=False, verbose_name="Reco Result Status 5")
    reco_status = models.CharField(max_length=32, verbose_name="Reco Status", null=True)
    reco_category = models.CharField(max_length=32, verbose_name="Reco Category", null=True)
    is_active = models.BooleanField(default=True, verbose_name="Active ?")
    created_by = models.PositiveSmallIntegerField(verbose_name="User Id", null=True)
    created_date = models.CharField(max_length=64, verbose_name="Created Date", null=True)
    modified_by = models.PositiveSmallIntegerField(verbose_name="User Id", null=True)
    modified_date = models.CharField(max_length=64, verbose_name="Modified Date", null=True)

class RecoExecutionLog(models.Model):
    class Meta:
        db_table = "reco_execution_log"

    reco_execution_log_id = models.AutoField(primary_key=True)
    tenants_id = models.PositiveIntegerField(verbose_name="Tenants Id", null=True)
    groups_id = models.PositiveIntegerField(verbose_name="Groups Id", null=True)
    entities_id = models.PositiveIntegerField(verbose_name="Entities Id", null=True)
    m_processing_layer_id = models.PositiveIntegerField(verbose_name="M Processing Layer Id", null=True)
    m_processing_sub_layer_id = models.PositiveIntegerField(verbose_name="M Processing Sub Layer Id", null=True)
    processing_layer_id = models.PositiveIntegerField(verbose_name="Processing Layer Id", null=True)
    start_date = models.CharField(max_length=64, verbose_name="Start Date", null=True)
    end_date = models.CharField(max_length=64, verbose_name="End Date", null=True)
    status = models.TextField(verbose_name="Status", null=True)
    row_count = models.PositiveIntegerField(verbose_name="Row Count", null=True)
    duration = models.PositiveIntegerField(verbose_name="Duration", null=True)
    comments = models.TextField(verbose_name="Comments", null=True)

class ReconFileUploads(models.Model):
    class Meta:
        db_table = "recon_file_uploads"

    id = models.AutoField(primary_key=True)
    tenants_id = models.PositiveIntegerField(verbose_name="Tenants Id (Business Module - Tenant Id)")
    groups_id = models.PositiveIntegerField(verbose_name="Groups Id (Business Module - Groups Id)")
    entities_id = models.PositiveIntegerField(verbose_name="Entities Id (Business Module - Entities Id)")
    m_source_id = models.PositiveIntegerField(verbose_name="Source Id (Business Module - Source Id)")
    m_processing_layer_id = models.PositiveIntegerField(verbose_name="M Processing Layer Id (Business Module - M Processing Layer Id)")
    m_processing_sub_layer_id = models.PositiveIntegerField(verbose_name="M Processing Sub Layer Id (Business Module - M Processing Sub Layer Id)")
    processing_layer_id = models.PositiveIntegerField(verbose_name="Processing Layer Id (Business Module - Processing Layer Id)")
    processing_layer_name = models.CharField(max_length=64, verbose_name="Processing Layer Name", null=True)
    source_type = models.CharField(max_length=128, verbose_name="File Name", null=True)
    extraction_type = models.CharField(max_length=128, verbose_name="File Name", null=True)
    file_name = models.CharField(max_length=128, verbose_name="File Name", null=True)
    file_size_bytes = models.PositiveIntegerField(verbose_name="File Size Bytes", null=True)
    file_path = models.CharField(max_length=512, verbose_name="File Path", null=True)
    status = models.CharField(max_length=32, verbose_name="Status", null=True)
    comments = models.TextField(verbose_name="Comments", null=True)
    system_comments = models.TextField(verbose_name="System Comments", null=True)
    file_row_count = models.PositiveIntegerField(verbose_name="File Row Count (Business Module - File Row Count)", null=True)
    is_processed = models.BooleanField(default=True, verbose_name="Active ?")
    is_processing = models.PositiveIntegerField(verbose_name="Is Processing?")
    is_active = models.BooleanField(default=True, verbose_name="Active ?")
    created_by = models.PositiveSmallIntegerField(verbose_name="User Id", null=True)
    created_date = models.CharField(max_length=64, verbose_name="Created Date", null=True)
    modified_by = models.PositiveSmallIntegerField(verbose_name="User Id", null=True)
    modified_date = models.CharField(max_length=64, verbose_name="Modified Date", null=True)

class StagingExternalRecords(models.Model):
    class Meta:
        db_table = "stg_external_records"

    stg_external_records_id = models.AutoField(primary_key=True)
    tenants_id = models.PositiveIntegerField(verbose_name="Tenants Id (Business Module - Tenant Id)", null=True)
    groups_id = models.PositiveIntegerField(verbose_name="Groups Id (Business Module - Groups Id)", null=True)
    entities_id = models.PositiveIntegerField(verbose_name="Entities Id (Business Module - Entities Id)", null=True)
    m_processing_layer_id = models.PositiveIntegerField(verbose_name="M Processing Layer Id", null=True)
    m_processing_sub_layer_id = models.PositiveIntegerField(verbose_name="M Processing Sub Layer Id", null=True)
    processing_layer_id = models.PositiveIntegerField(verbose_name="Processing Layer Id", null=True)
    file_uploads_id = models.PositiveIntegerField(verbose_name="File Uploads Id (Recon Module - File Uploads Id)", null=True)
    m_sources_id = models.PositiveIntegerField(verbose_name="Sources Id (Sources Module - Sources Id)", null=True)
    staging_row_id = models.PositiveIntegerField(verbose_name="Staging Row Id (Staging Table - Row Id)", null=True)
    m_source_name = models.CharField(max_length=64, verbose_name="Source Name", null=True)
    ext_match_type_1 = models.CharField(max_length=32, verbose_name="Match Type 1", null=True)
    ext_match_type_2 = models.CharField(max_length=32, verbose_name="Match Type 2", null=True)
    ext_match_type_3 = models.CharField(max_length=32, verbose_name="Match Type 3", null=True)
    ext_match_type_4 = models.CharField(max_length=32, verbose_name="Match Type 4", null=True)
    ext_match_type_5 = models.CharField(max_length=32, verbose_name="Match Type 5", null=True)
    ext_processing_status_1 = models.CharField(max_length=32, verbose_name="Processing Status 1", null=True)
    ext_processing_status_2 = models.CharField(max_length=32, verbose_name="Processing Status 2", null=True)
    ext_processing_status_3 = models.CharField(max_length=32, verbose_name="Processing Status 3", null=True)
    ext_processing_status_4 = models.CharField(max_length=32, verbose_name="Processing Status 4", null=True)
    ext_processing_status_5 = models.CharField(max_length=32, verbose_name="Processing Status 5", null=True)
    processing_date_time = models.CharField(max_length=64, verbose_name="Processing Date Time", null=True)
    ext_reference_text_1 = models.TextField(verbose_name="Reference Text 1", null=True)
    ext_reference_text_2 = models.TextField(verbose_name="Reference Text 2", null=True)
    ext_reference_text_3 = models.TextField(verbose_name="Reference Text 3", null=True)
    ext_reference_text_4 = models.TextField(verbose_name="Reference Text 4", null=True)
    ext_reference_text_5 = models.TextField(verbose_name="Reference Text 5", null=True)
    ext_reference_text_6 = models.TextField(verbose_name="Reference Text 6", null=True)
    ext_reference_text_7 = models.TextField(verbose_name="Reference Text 7", null=True)
    ext_reference_text_8 = models.TextField(verbose_name="Reference Text 8", null=True)
    ext_reference_text_9 = models.TextField(verbose_name="Reference Text 9", null=True)
    ext_reference_text_10 = models.TextField(verbose_name="Reference Text 10", null=True)
    ext_reference_text_11 = models.TextField(verbose_name="Reference Text 11", null=True)
    ext_reference_text_12 = models.TextField(verbose_name="Reference Text 12", null=True)
    ext_reference_text_13 = models.TextField(verbose_name="Reference Text 13", null=True)
    ext_reference_text_14 = models.TextField(verbose_name="Reference Text 14", null=True)
    ext_reference_text_15 = models.TextField(verbose_name="Reference Text 15", null=True)
    ext_reference_text_16 = models.TextField(verbose_name="Reference Text 16", null=True)
    ext_reference_text_17 = models.TextField(verbose_name="Reference Text 17", null=True)
    ext_reference_text_18 = models.TextField(verbose_name="Reference Text 18", null=True)
    ext_reference_text_19 = models.TextField(verbose_name="Reference Text 19", null=True)
    ext_reference_text_20 = models.TextField(verbose_name="Reference Text 20", null=True)
    ext_reference_text_21 = models.TextField(verbose_name="Reference Text 21", null=True)
    ext_reference_text_22 = models.TextField(verbose_name="Reference Text 22", null=True)
    ext_reference_text_23 = models.TextField(verbose_name="Reference Text 23", null=True)
    ext_reference_text_24 = models.TextField(verbose_name="Reference Text 24", null=True)
    ext_reference_text_25 = models.TextField(verbose_name="Reference Text 25", null=True)
    ext_reference_text_26 = models.TextField(verbose_name="Reference Text 26", null=True)
    ext_reference_text_27 = models.TextField(verbose_name="Reference Text 27", null=True)
    ext_reference_text_28 = models.TextField(verbose_name="Reference Text 28", null=True)
    ext_reference_text_29 = models.TextField(verbose_name="Reference Text 29", null=True)
    ext_reference_text_30 = models.TextField(verbose_name="Reference Text 30", null=True)
    ext_reference_text_31 = models.TextField(verbose_name="Reference Text 31", null=True)
    ext_reference_text_32 = models.TextField(verbose_name="Reference Text 32", null=True)
    ext_reference_text_33 = models.TextField(verbose_name="Reference Text 33", null=True)
    ext_reference_text_34 = models.TextField(verbose_name="Reference Text 34", null=True)
    ext_reference_text_35 = models.TextField(verbose_name="Reference Text 35", null=True)
    ext_reference_text_36 = models.TextField(verbose_name="Reference Text 36", null=True)
    ext_reference_text_37 = models.TextField(verbose_name="Reference Text 37", null=True)
    ext_reference_text_38 = models.TextField(verbose_name="Reference Text 38", null=True)
    ext_reference_text_39 = models.TextField(verbose_name="Reference Text 39", null=True)
    ext_reference_text_40 = models.TextField(verbose_name="Reference Text 40", null=True)
    ext_reference_text_41 = models.TextField(verbose_name="Reference Text 41", null=True)
    ext_reference_text_42 = models.TextField(verbose_name="Reference Text 42", null=True)
    ext_reference_text_43 = models.TextField(verbose_name="Reference Text 43", null=True)
    ext_reference_text_44 = models.TextField(verbose_name="Reference Text 44", null=True)
    ext_reference_text_45 = models.TextField(verbose_name="Reference Text 45", null=True)
    ext_reference_text_46 = models.TextField(verbose_name="Reference Text 46", null=True)
    ext_reference_text_47 = models.TextField(verbose_name="Reference Text 47", null=True)
    ext_reference_text_48 = models.TextField(verbose_name="Reference Text 48", null=True)
    ext_reference_text_49 = models.TextField(verbose_name="Reference Text 49", null=True)
    ext_reference_text_50 = models.TextField(verbose_name="Reference Text 50", null=True)
    ext_reference_text_51 = models.TextField(verbose_name="Reference Text 51", null=True)
    ext_reference_text_52 = models.TextField(verbose_name="Reference Text 52", null=True)
    ext_reference_text_53 = models.TextField(verbose_name="Reference Text 53", null=True)
    ext_reference_text_54 = models.TextField(verbose_name="Reference Text 54", null=True)
    ext_reference_text_55 = models.TextField(verbose_name="Reference Text 55", null=True)
    ext_reference_text_56 = models.TextField(verbose_name="Reference Text 56", null=True)
    ext_reference_text_57 = models.TextField(verbose_name="Reference Text 57", null=True)
    ext_reference_text_58 = models.TextField(verbose_name="Reference Text 58", null=True)
    ext_reference_text_59 = models.TextField(verbose_name="Reference Text 59", null=True)
    ext_reference_text_60 = models.TextField(verbose_name="Reference Text 60", null=True)
    ext_reference_date_time_1 = models.CharField(max_length=32, verbose_name="Reference Date Time 1", null=True)
    ext_reference_date_time_2 = models.CharField(max_length=32, verbose_name="Reference Date Time 2", null=True)
    ext_reference_date_time_3 = models.CharField(max_length=32, verbose_name="Reference Date Time 3", null=True)
    ext_reference_date_time_4 = models.CharField(max_length=32, verbose_name="Reference Date Time 4", null=True)
    ext_reference_date_time_5 = models.CharField(max_length=32, verbose_name="Reference Date Time 5", null=True)
    ext_reference_date_time_6 = models.CharField(max_length=32, verbose_name="Reference Date Time 6", null=True)
    ext_reference_date_time_7 = models.CharField(max_length=32, verbose_name="Reference Date Time 7", null=True)
    ext_reference_date_time_8 = models.CharField(max_length=32, verbose_name="Reference Date Time 8", null=True)
    ext_reference_date_time_9 = models.CharField(max_length=32, verbose_name="Reference Date Time 9", null=True)
    ext_reference_date_time_10 = models.CharField(max_length=32, verbose_name="Reference Date Time 10", null=True)
    ext_debit_amount = models.CharField(max_length=32, verbose_name="Debit Amount", null=True)
    ext_credit_amount = models.CharField(max_length=32, verbose_name="Credit Amount", null=True)
    ext_amount_1 = models.CharField(max_length=32, verbose_name="Amount 1", null=True)
    ext_amount_2 = models.CharField(max_length=32, verbose_name="Amount 2", null=True)
    ext_amount_3 = models.CharField(max_length=32, verbose_name="Amount 3", null=True)
    ext_amount_4 = models.CharField(max_length=32, verbose_name="Amount 4", null=True)
    ext_amount_5 = models.CharField(max_length=32, verbose_name="Amount 5", null=True)
    ext_amount_6 = models.CharField(max_length=32, verbose_name="Amount 6", null=True)
    ext_amount_7 = models.CharField(max_length=32, verbose_name="Amount 7", null=True)
    ext_amount_8 = models.CharField(max_length=32, verbose_name="Amount 8", null=True)
    ext_amount_9 = models.CharField(max_length=32, verbose_name="Amount 9", null=True)
    ext_amount_10 = models.CharField(max_length=32, verbose_name="Amount 10", null=True)
    ext_amount_11 = models.CharField(max_length=32, verbose_name="Amount 11", null=True)
    ext_amount_12 = models.CharField(max_length=32, verbose_name="Amount 12", null=True)
    ext_amount_13 = models.CharField(max_length=32, verbose_name="Amount 13", null=True)
    ext_amount_14 = models.CharField(max_length=32, verbose_name="Amount 14", null=True)
    ext_amount_15 = models.CharField(max_length=32, verbose_name="Amount 15", null=True)
    ext_extracted_text_1 = models.TextField(verbose_name="Extracted Text 1", null=True)
    ext_extracted_text_2 = models.TextField(verbose_name="Extracted Text 2", null=True)
    ext_extracted_text_3 = models.TextField(verbose_name="Extracted Text 3", null=True)
    ext_extracted_text_4 = models.TextField(verbose_name="Extracted Text 4", null=True)
    ext_extracted_text_5 = models.TextField(verbose_name="Extracted Text 5", null=True)
    ext_extracted_text_6 = models.TextField(verbose_name="Extracted Text 6", null=True)
    ext_extracted_text_7 = models.TextField(verbose_name="Extracted Text 7", null=True)
    ext_extracted_text_8 = models.TextField(verbose_name="Extracted Text 8", null=True)
    ext_extracted_text_9 = models.TextField(verbose_name="Extracted Text 9", null=True)
    ext_extracted_text_10 = models.TextField(verbose_name="Extracted Text 10", null=True)
    ext_extracted_text_11 = models.TextField(verbose_name="Extracted Text 11", null=True)
    ext_extracted_text_12 = models.TextField(verbose_name="Extracted Text 12", null=True)
    ext_extracted_text_13 = models.TextField(verbose_name="Extracted Text 13", null=True)
    ext_extracted_text_14 = models.TextField(verbose_name="Extracted Text 14", null=True)
    ext_extracted_text_15 = models.TextField(verbose_name="Extracted Text 15", null=True)
    ext_extracted_text_16 = models.TextField(verbose_name="Extracted Text 16", null=True)
    ext_extracted_text_17 = models.TextField(verbose_name="Extracted Text 17", null=True)
    ext_extracted_text_18 = models.TextField(verbose_name="Extracted Text 18", null=True)
    ext_extracted_text_19 = models.TextField(verbose_name="Extracted Text 19", null=True)
    ext_extracted_text_20 = models.TextField(verbose_name="Extracted Text 20", null=True)
    ext_extracted_text_21 = models.TextField(verbose_name="Extracted Text 21", null=True)
    ext_extracted_text_22 = models.TextField(verbose_name="Extracted Text 22", null=True)
    ext_extracted_text_23 = models.TextField(verbose_name="Extracted Text 23", null=True)
    ext_extracted_text_24 = models.TextField(verbose_name="Extracted Text 24", null=True)
    ext_extracted_text_25 = models.TextField(verbose_name="Extracted Text 25", null=True)
    ext_extracted_text_26 = models.TextField(verbose_name="Extracted Text 26", null=True)
    ext_extracted_text_27 = models.TextField(verbose_name="Extracted Text 27", null=True)
    ext_extracted_text_28 = models.TextField(verbose_name="Extracted Text 28", null=True)
    ext_extracted_text_29 = models.TextField(verbose_name="Extracted Text 29", null=True)
    ext_extracted_text_30 = models.TextField(verbose_name="Extracted Text 30", null=True)
    internal_records_id = models.CharField(max_length=11, verbose_name="Internal Records Id", null=True)
    ext_contra_id = models.CharField(max_length=11, verbose_name="Contra Id", null=True)
    ext_generated_number_1 = models.CharField(max_length=11, verbose_name="Generated Number 1", null=True)
    ext_generated_number_2 = models.CharField(max_length=11, verbose_name="Generated Number 2", null=True)
    ext_generated_number_3 = models.CharField(max_length=11, verbose_name="Generated Number 3", null=True)
    ext_generated_number_4 = models.CharField(max_length=11, verbose_name="Generated Number 4", null=True)
    ext_generated_number_5 = models.CharField(max_length=11, verbose_name="Generated Number 5", null=True)
    ext_transaction_type_1 = models.CharField(max_length=32, verbose_name="Transaction Type 1", null=True)
    ext_transaction_type_2 = models.CharField(max_length=32, verbose_name="Transaction Type 2", null=True)
    ext_transaction_type_3 = models.CharField(max_length=32, verbose_name="Transaction Type 3", null=True)
    ext_transaction_type_4 = models.CharField(max_length=32, verbose_name="Transaction Type 4", null=True)
    ext_transaction_type_5 = models.CharField(max_length=32, verbose_name="Transaction Type 5", null=True)
    ext_record_status_1 = models.BooleanField(default=False, verbose_name="Record Status 1")
    ext_record_status_2 = models.BooleanField(default=False, verbose_name="Record Status 2")
    ext_record_status_3 = models.BooleanField(default=False, verbose_name="Record Status 3")
    ext_record_status_4 = models.BooleanField(default=False, verbose_name="Record Status 4")
    ext_record_status_5 = models.BooleanField(default=False, verbose_name="Record Status 5")
    ext_record_status_6 = models.BooleanField(default=False, verbose_name="Record Status 6")
    ext_record_status_7 = models.BooleanField(default=False, verbose_name="Record Status 7")
    ext_record_status_8 = models.BooleanField(default=False, verbose_name="Record Status 8")
    ext_record_status_9 = models.BooleanField(default=False, verbose_name="Record Status 9")
    ext_record_status_10 = models.BooleanField(default=False, verbose_name="Record Status 10")
    is_active = models.BooleanField(default=True, verbose_name="Active ?")
    created_by = models.PositiveSmallIntegerField(verbose_name="User Id", null=True)
    created_date = models.CharField(max_length=64, verbose_name="Created Date", null=True)
    modified_by = models.PositiveSmallIntegerField(verbose_name="User Id", null=True)
    modified_date = models.CharField(max_length=64, verbose_name="Modified Date", null=True)

class StagingInternalRecords(models.Model):
    class Meta:
        db_table = "stg_internal_records"

    stg_internal_records_id = models.AutoField(primary_key=True)
    tenants_id = models.PositiveIntegerField(verbose_name="Tenants Id (Business Module - Tenant Id)", null=True)
    groups_id = models.PositiveIntegerField(verbose_name="Groups Id (Business Module - Groups Id)", null=True)
    entities_id = models.PositiveIntegerField(verbose_name="Entities Id (Business Module - Entities Id)", null=True)
    m_processing_layer_id = models.PositiveIntegerField(verbose_name="M Processing Layer Id", null=True)
    m_processing_sub_layer_id = models.PositiveIntegerField(verbose_name="M Processing Sub Layer Id", null=True)
    processing_layer_id = models.PositiveIntegerField(verbose_name="Processing Layer Id", null=True)
    file_uploads_id = models.PositiveIntegerField(verbose_name="File Uploads Id (Recon Module - File Uploads Id)", null=True)
    m_sources_id = models.PositiveIntegerField(verbose_name="Sources Id (Sources Module - Sources Id)", null=True)
    staging_row_id = models.PositiveIntegerField(verbose_name="Staging Row Id (Staging Table - Row Id)", null=True)
    m_source_name = models.CharField(max_length=64, verbose_name="Source Name", null=True)
    int_match_type_1 = models.CharField(max_length=32, verbose_name="Match Type 1", null=True)
    int_match_type_2 = models.CharField(max_length=32, verbose_name="Match Type 2", null=True)
    int_match_type_3 = models.CharField(max_length=32, verbose_name="Match Type 3", null=True)
    int_match_type_4 = models.CharField(max_length=32, verbose_name="Match Type 4", null=True)
    int_match_type_5 = models.CharField(max_length=32, verbose_name="Match Type 5", null=True)
    int_processing_status_1 = models.CharField(max_length=32, verbose_name="Processing Status 1", null=True)
    int_processing_status_2 = models.CharField(max_length=32, verbose_name="Processing Status 2", null=True)
    int_processing_status_3 = models.CharField(max_length=32, verbose_name="Processing Status 3", null=True)
    int_processing_status_4 = models.CharField(max_length=32, verbose_name="Processing Status 4", null=True)
    int_processing_status_5 = models.CharField(max_length=32, verbose_name="Processing Status 5", null=True)
    processing_date_time = models.CharField(max_length=64, verbose_name="Processing Date Time", null=True)
    int_reference_text_1 = models.TextField(verbose_name="Reference Text 1", null=True)
    int_reference_text_2 = models.TextField(verbose_name="Reference Text 2", null=True)
    int_reference_text_3 = models.TextField(verbose_name="Reference Text 3", null=True)
    int_reference_text_4 = models.TextField(verbose_name="Reference Text 4", null=True)
    int_reference_text_5 = models.TextField(verbose_name="Reference Text 5", null=True)
    int_reference_text_6 = models.TextField(verbose_name="Reference Text 6", null=True)
    int_reference_text_7 = models.TextField(verbose_name="Reference Text 7", null=True)
    int_reference_text_8 = models.TextField(verbose_name="Reference Text 8", null=True)
    int_reference_text_9 = models.TextField(verbose_name="Reference Text 9", null=True)
    int_reference_text_10 = models.TextField(verbose_name="Reference Text 10", null=True)
    int_reference_text_11 = models.TextField(verbose_name="Reference Text 11", null=True)
    int_reference_text_12 = models.TextField(verbose_name="Reference Text 12", null=True)
    int_reference_text_13 = models.TextField(verbose_name="Reference Text 13", null=True)
    int_reference_text_14 = models.TextField(verbose_name="Reference Text 14", null=True)
    int_reference_text_15 = models.TextField(verbose_name="Reference Text 15", null=True)
    int_reference_text_16 = models.TextField(verbose_name="Reference Text 16", null=True)
    int_reference_text_17 = models.TextField(verbose_name="Reference Text 17", null=True)
    int_reference_text_18 = models.TextField(verbose_name="Reference Text 18", null=True)
    int_reference_text_19 = models.TextField(verbose_name="Reference Text 19", null=True)
    int_reference_text_20 = models.TextField(verbose_name="Reference Text 20", null=True)
    int_reference_text_21 = models.TextField(verbose_name="Reference Text 21", null=True)
    int_reference_text_22 = models.TextField(verbose_name="Reference Text 22", null=True)
    int_reference_text_23 = models.TextField(verbose_name="Reference Text 23", null=True)
    int_reference_text_24 = models.TextField(verbose_name="Reference Text 24", null=True)
    int_reference_text_25 = models.TextField(verbose_name="Reference Text 25", null=True)
    int_reference_text_26 = models.TextField(verbose_name="Reference Text 26", null=True)
    int_reference_text_27 = models.TextField(verbose_name="Reference Text 27", null=True)
    int_reference_text_28 = models.TextField(verbose_name="Reference Text 28", null=True)
    int_reference_text_29 = models.TextField(verbose_name="Reference Text 29", null=True)
    int_reference_text_30 = models.TextField(verbose_name="Reference Text 30", null=True)
    int_reference_text_31 = models.TextField(verbose_name="Reference Text 31", null=True)
    int_reference_text_32 = models.TextField(verbose_name="Reference Text 32", null=True)
    int_reference_text_33 = models.TextField(verbose_name="Reference Text 33", null=True)
    int_reference_text_34 = models.TextField(verbose_name="Reference Text 34", null=True)
    int_reference_text_35 = models.TextField(verbose_name="Reference Text 35", null=True)
    int_reference_text_36 = models.TextField(verbose_name="Reference Text 36", null=True)
    int_reference_text_37 = models.TextField(verbose_name="Reference Text 37", null=True)
    int_reference_text_38 = models.TextField(verbose_name="Reference Text 38", null=True)
    int_reference_text_39 = models.TextField(verbose_name="Reference Text 39", null=True)
    int_reference_text_40 = models.TextField(verbose_name="Reference Text 40", null=True)
    int_reference_text_41 = models.TextField(verbose_name="Reference Text 41", null=True)
    int_reference_text_42 = models.TextField(verbose_name="Reference Text 42", null=True)
    int_reference_text_43 = models.TextField(verbose_name="Reference Text 43", null=True)
    int_reference_text_44 = models.TextField(verbose_name="Reference Text 44", null=True)
    int_reference_text_45 = models.TextField(verbose_name="Reference Text 45", null=True)
    int_reference_text_46 = models.TextField(verbose_name="Reference Text 46", null=True)
    int_reference_text_47 = models.TextField(verbose_name="Reference Text 47", null=True)
    int_reference_text_48 = models.TextField(verbose_name="Reference Text 48", null=True)
    int_reference_text_49 = models.TextField(verbose_name="Reference Text 49", null=True)
    int_reference_text_50 = models.TextField(verbose_name="Reference Text 50", null=True)
    int_reference_text_51 = models.TextField(verbose_name="Reference Text 51", null=True)
    int_reference_text_52 = models.TextField(verbose_name="Reference Text 52", null=True)
    int_reference_text_53 = models.TextField(verbose_name="Reference Text 53", null=True)
    int_reference_text_54 = models.TextField(verbose_name="Reference Text 54", null=True)
    int_reference_text_55 = models.TextField(verbose_name="Reference Text 55", null=True)
    int_reference_text_56 = models.TextField(verbose_name="Reference Text 56", null=True)
    int_reference_text_57 = models.TextField(verbose_name="Reference Text 57", null=True)
    int_reference_text_58 = models.TextField(verbose_name="Reference Text 58", null=True)
    int_reference_text_59 = models.TextField(verbose_name="Reference Text 59", null=True)
    int_reference_text_60 = models.TextField(verbose_name="Reference Text 60", null=True)
    int_reference_date_time_1 = models.CharField(max_length=32, verbose_name="Reference Date Time 1", null=True)
    int_reference_date_time_2 = models.CharField(max_length=32, verbose_name="Reference Date Time 2", null=True)
    int_reference_date_time_3 = models.CharField(max_length=32, verbose_name="Reference Date Time 3", null=True)
    int_reference_date_time_4 = models.CharField(max_length=32, verbose_name="Reference Date Time 4", null=True)
    int_reference_date_time_5 = models.CharField(max_length=32, verbose_name="Reference Date Time 5", null=True)
    int_reference_date_time_6 = models.CharField(max_length=32, verbose_name="Reference Date Time 6", null=True)
    int_reference_date_time_7 = models.CharField(max_length=32, verbose_name="Reference Date Time 7", null=True)
    int_reference_date_time_8 = models.CharField(max_length=32, verbose_name="Reference Date Time 8", null=True)
    int_reference_date_time_9 = models.CharField(max_length=32, verbose_name="Reference Date Time 9", null=True)
    int_reference_date_time_10 = models.CharField(max_length=32, verbose_name="Reference Date Time 10", null=True)
    int_debit_amount = models.CharField(max_length=32, verbose_name="Debit Amount", null=True)
    int_credit_amount = models.CharField(max_length=32, verbose_name="Credit Amount", null=True)
    int_amount_1 = models.CharField(max_length=32, verbose_name="Amount 1", null=True)
    int_amount_2 = models.CharField(max_length=32, verbose_name="Amount 2", null=True)
    int_amount_3 = models.CharField(max_length=32, verbose_name="Amount 3", null=True)
    int_amount_4 = models.CharField(max_length=32, verbose_name="Amount 4", null=True)
    int_amount_5 = models.CharField(max_length=32, verbose_name="Amount 5", null=True)
    int_amount_6 = models.CharField(max_length=32, verbose_name="Amount 6", null=True)
    int_amount_7 = models.CharField(max_length=32, verbose_name="Amount 7", null=True)
    int_amount_8 = models.CharField(max_length=32, verbose_name="Amount 8", null=True)
    int_amount_9 = models.CharField(max_length=32, verbose_name="Amount 9", null=True)
    int_amount_10 = models.CharField(max_length=32, verbose_name="Amount 10", null=True)
    int_amount_11 = models.CharField(max_length=32, verbose_name="Amount 11", null=True)
    int_amount_12 = models.CharField(max_length=32, verbose_name="Amount 12", null=True)
    int_amount_13 = models.CharField(max_length=32, verbose_name="Amount 13", null=True)
    int_amount_14 = models.CharField(max_length=32, verbose_name="Amount 14", null=True)
    int_amount_15 = models.CharField(max_length=32, verbose_name="Amount 15", null=True)
    int_extracted_text_1 = models.TextField(verbose_name="Extracted Text 1", null=True)
    int_extracted_text_2 = models.TextField(verbose_name="Extracted Text 2", null=True)
    int_extracted_text_3 = models.TextField(verbose_name="Extracted Text 3", null=True)
    int_extracted_text_4 = models.TextField(verbose_name="Extracted Text 4", null=True)
    int_extracted_text_5 = models.TextField(verbose_name="Extracted Text 5", null=True)
    int_extracted_text_6 = models.TextField(verbose_name="Extracted Text 6", null=True)
    int_extracted_text_7 = models.TextField(verbose_name="Extracted Text 7", null=True)
    int_extracted_text_8 = models.TextField(verbose_name="Extracted Text 8", null=True)
    int_extracted_text_9 = models.TextField(verbose_name="Extracted Text 9", null=True)
    int_extracted_text_10 = models.TextField(verbose_name="Extracted Text 10", null=True)
    int_extracted_text_11 = models.TextField(verbose_name="Extracted Text 11", null=True)
    int_extracted_text_12 = models.TextField(verbose_name="Extracted Text 12", null=True)
    int_extracted_text_13 = models.TextField(verbose_name="Extracted Text 13", null=True)
    int_extracted_text_14 = models.TextField(verbose_name="Extracted Text 14", null=True)
    int_extracted_text_15 = models.TextField(verbose_name="Extracted Text 15", null=True)
    int_extracted_text_16 = models.TextField(verbose_name="Extracted Text 16", null=True)
    int_extracted_text_17 = models.TextField(verbose_name="Extracted Text 17", null=True)
    int_extracted_text_18 = models.TextField(verbose_name="Extracted Text 18", null=True)
    int_extracted_text_19 = models.TextField(verbose_name="Extracted Text 19", null=True)
    int_extracted_text_20 = models.TextField(verbose_name="Extracted Text 20", null=True)
    int_extracted_text_21 = models.TextField(verbose_name="Extracted Text 21", null=True)
    int_extracted_text_22 = models.TextField(verbose_name="Extracted Text 22", null=True)
    int_extracted_text_23 = models.TextField(verbose_name="Extracted Text 23", null=True)
    int_extracted_text_24 = models.TextField(verbose_name="Extracted Text 24", null=True)
    int_extracted_text_25 = models.TextField(verbose_name="Extracted Text 25", null=True)
    int_extracted_text_26 = models.TextField(verbose_name="Extracted Text 26", null=True)
    int_extracted_text_27 = models.TextField(verbose_name="Extracted Text 27", null=True)
    int_extracted_text_28 = models.TextField(verbose_name="Extracted Text 28", null=True)
    int_extracted_text_29 = models.TextField(verbose_name="Extracted Text 29", null=True)
    int_extracted_text_30 = models.TextField(verbose_name="Extracted Text 30", null=True)
    external_records_id = models.CharField(max_length=11, verbose_name="External Records Id", null=True)
    int_contra_id = models.CharField(max_length=11, verbose_name="Contra Id", null=True)
    int_generated_number_1 = models.CharField(max_length=11, verbose_name="Generated Number 1", null=True)
    int_generated_number_2 = models.CharField(max_length=11, verbose_name="Generated Number 2", null=True)
    int_generated_number_3 = models.CharField(max_length=11, verbose_name="Generated Number 3", null=True)
    int_generated_number_4 = models.CharField(max_length=11, verbose_name="Generated Number 4", null=True)
    int_generated_number_5 = models.CharField(max_length=11, verbose_name="Generated Number 5", null=True)
    int_transaction_type_1 = models.CharField(max_length=32, verbose_name="Transaction Type 1", null=True)
    int_transaction_type_2 = models.CharField(max_length=32, verbose_name="Transaction Type 2", null=True)
    int_transaction_type_3 = models.CharField(max_length=32, verbose_name="Transaction Type 3", null=True)
    int_transaction_type_4 = models.CharField(max_length=32, verbose_name="Transaction Type 4", null=True)
    int_transaction_type_5 = models.CharField(max_length=32, verbose_name="Transaction Type 5", null=True)
    int_record_status_1 = models.BooleanField(default=False, verbose_name="Record Status 1")
    int_record_status_2 = models.BooleanField(default=False, verbose_name="Record Status 2")
    int_record_status_3 = models.BooleanField(default=False, verbose_name="Record Status 3")
    int_record_status_4 = models.BooleanField(default=False, verbose_name="Record Status 4")
    int_record_status_5 = models.BooleanField(default=False, verbose_name="Record Status 5")
    int_record_status_6 = models.BooleanField(default=False, verbose_name="Record Status 6")
    int_record_status_7 = models.BooleanField(default=False, verbose_name="Record Status 7")
    int_record_status_8 = models.BooleanField(default=False, verbose_name="Record Status 8")
    int_record_status_9 = models.BooleanField(default=False, verbose_name="Record Status 9")
    int_record_status_10 = models.BooleanField(default=False, verbose_name="Record Status 10")
    is_active = models.BooleanField(default=True, verbose_name="Active ?")
    created_by = models.PositiveSmallIntegerField(verbose_name="User Id", null=True)
    created_date = models.CharField(max_length=64, verbose_name="Created Date", null=True)
    modified_by = models.PositiveSmallIntegerField(verbose_name="User Id", null=True)
    modified_date = models.CharField(max_length=64, verbose_name="Modified Date", null=True)

class ReportGeneration(models.Model):
    class Meta:
        db_table = "report_generation"

    is_report_generating = models.BooleanField(default=False, verbose_name="Report Generating?")

class SettingQueries(models.Model):
    class Meta:
        db_table = "setting_queries"

    setting_queries_id = models.AutoField(primary_key=True)
    tenants_id = models.PositiveIntegerField(verbose_name="Tenants Id (Business Module - Tenant Id)", null=True)
    groups_id = models.PositiveIntegerField(verbose_name="Groups Id (Business Module - Groups Id)", null=True)
    entities_id = models.PositiveIntegerField(verbose_name="Entities Id (Business Module - Entities Id)", null=True)
    m_processing_layer_id = models.PositiveIntegerField(verbose_name="M Processing Layer Id", null=True)
    m_processing_sub_layer_id = models.PositiveIntegerField(verbose_name="M Processing Sub Layer Id", null=True)
    setting_key = models.CharField(max_length=32, verbose_name="Setting Key", null=True)
    setting_value = models.TextField(verbose_name="Setting Value", null=True)
    is_active = models.BooleanField(default=True, verbose_name="Active ?")
    created_by = models.PositiveSmallIntegerField(verbose_name="User Id", null=True)
    created_date = models.CharField(max_length=64, verbose_name="Created Date", null=True)
    modified_by = models.PositiveSmallIntegerField(verbose_name="User Id", null=True)
    modified_date = models.CharField(max_length=64, verbose_name="Modified Date", null=True)

    def __str__(self):
        return self.setting_key

class RecoExecutionTasks(models.Model):
    class Meta:
        db_table = "reco_execution_tasks"

    id = models.AutoField(primary_key=True)
    tenants_id = models.PositiveIntegerField(verbose_name="Tenants Id (Business Module - Tenant Id)", null=True)
    groups_id = models.PositiveIntegerField(verbose_name="Groups Id (Business Module - Groups Id)", null=True)
    entities_id = models.PositiveIntegerField(verbose_name="Entities Id (Business Module - Entities Id)", null=True)
    m_processing_layer_id = models.PositiveIntegerField(verbose_name="M Processing Layer Id", null=True)
    m_processing_sub_layer_id = models.PositiveIntegerField(verbose_name="M Processing Sub Layer Id", null=True)
    processing_layer_id = models.PositiveIntegerField(verbose_name="Processing Layer Id", null=True)
    execution_sequence = models.PositiveIntegerField(verbose_name="Execution Sequence", null=True)
    procedure_name = models.CharField(max_length=256, verbose_name="Procedure Name", null=True)
    description = models.TextField(verbose_name="Procedure Description", null=True)
    is_active = models.BooleanField(default=True, verbose_name="Active ?")
    created_by = models.PositiveSmallIntegerField(verbose_name="User Id", null=True)
    created_date = models.CharField(max_length=64, verbose_name="Created Date", null=True)
    modified_by = models.PositiveSmallIntegerField(verbose_name="User Id", null=True)
    modified_date = models.CharField(max_length=64, verbose_name="Modified Date", null=True)

    def __str__(self):
        return self.procedure_name

class MasterMatchingComments(models.Model):
    class Meta:
        db_table = "m_matching_comments"

    id = models.AutoField(primary_key = True)
    tenants_id = models.PositiveIntegerField(verbose_name="Tenants Id (Business Module - Tenant Id)", null=True)
    groups_id = models.PositiveIntegerField(verbose_name="Groups Id (Business Module - Groups Id)", null=True)
    entities_id = models.PositiveIntegerField(verbose_name="Entities Id (Business Module - Entities Id)", null=True)
    m_processing_layer_id = models.PositiveIntegerField(verbose_name="M Processing Layer Id", null=True)
    m_processing_sub_layer_id = models.PositiveIntegerField(verbose_name="M Processing Sub Layer Id", null=True)
    name = models.CharField(max_length=256, verbose_name="Name", null=True)
    description = models.TextField(verbose_name="Description", null=True)
    is_active = models.BooleanField(default=True, verbose_name="Active ?")
    created_by = models.PositiveSmallIntegerField(verbose_name="User Id", null=True)
    created_date = models.CharField(max_length=64, verbose_name="Created Date", null=True)
    modified_by = models.PositiveSmallIntegerField(verbose_name="User Id", null=True)
    modified_date = models.CharField(max_length=64, verbose_name="Modified Date", null=True)

    def __str__(self):
        return self.name


class ClosingBalancesBank(models.Model):
    class Meta:
        db_table = "closing_balances_bank"

    closing_balances_bank_id = models.AutoField(primary_key=True)
    tenants_id = models.PositiveIntegerField(verbose_name="Tenants Id (Business Module - Tenant Id)")
    groups_id = models.PositiveIntegerField(verbose_name="Groups Id (Business Module - Groups Id)")
    entities_id = models.PositiveIntegerField(verbose_name="Entities Id (Business Module - Entities Id)")
    m_processing_layer_id = models.PositiveIntegerField(verbose_name="M Processing Layer Id", null=True)
    m_processing_sub_layer_id = models.PositiveIntegerField(verbose_name="M Processing Sub Layer Id", null=True)
    processing_layer_id = models.PositiveIntegerField(verbose_name="Processing Layer Id", null=True)
    bank_closing_month = models.CharField(max_length=32, verbose_name="Bank Closing Month", null=True)
    bank_closing_year = models.CharField(max_length=6, verbose_name="Bank Closing Year", null=True)
    bank_closing_date = models.CharField(max_length=32, verbose_name="Date", null=True)
    bank_closing_balance = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Bank Closing Balance", null=True)
    approved_by = models.PositiveIntegerField(verbose_name="Approved By", null=True)
    approved_date = models.CharField(max_length=64, verbose_name="Approved Date", null=True)

class ClosingBalancesGL(models.Model):
    class Meta:
        db_table = "closing_balances_gl"

    closing_balances_gl_id = models.AutoField(primary_key=True)
    tenants_id = models.PositiveIntegerField(verbose_name="Tenants Id (Business Module - Tenant Id)")
    groups_id = models.PositiveIntegerField(verbose_name="Groups Id (Business Module - Groups Id)")
    entities_id = models.PositiveIntegerField(verbose_name="Entities Id (Business Module - Entities Id)")
    m_processing_layer_id = models.PositiveIntegerField(verbose_name="M Processing Layer Id", null=True)
    m_processing_sub_layer_id = models.PositiveIntegerField(verbose_name="M Processing Sub Layer Id", null=True)
    processing_layer_id = models.PositiveIntegerField(verbose_name="Processing Layer Id", null=True)
    gl_closing_month = models.CharField(max_length=32, verbose_name="GL Closing Month", null=True)
    gl_closing_year = models.CharField(max_length=6, verbose_name="GL Closing Year", null=True)
    gl_closing_date = models.CharField(max_length=32, verbose_name="Date", null=True)
    gl_closing_balance = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="GL Closing Balance", null=True)
    approved_by = models.PositiveIntegerField(verbose_name="Approved By", null=True)
    approved_date = models.CharField(max_length=64, verbose_name="Approved Date", null=True)

class DailyBalancesBank(models.Model):
    class Meta:
        db_table = "daily_balances_bank"

    daily_balances_bank_id = models.AutoField(primary_key=True)
    tenants_id = models.PositiveIntegerField(verbose_name="Tenants Id (Business Module - Tenant Id)")
    groups_id = models.PositiveIntegerField(verbose_name="Groups Id (Business Module - Groups Id)")
    entities_id = models.PositiveIntegerField(verbose_name="Entities Id (Business Module - Entities Id)")
    m_processing_layer_id = models.PositiveIntegerField(verbose_name="M Processing Layer Id", null=True)
    m_processing_sub_layer_id = models.PositiveIntegerField(verbose_name="M Processing Sub Layer Id", null=True)
    processing_layer_id = models.PositiveIntegerField(verbose_name="Processing Layer Id", null=True)
    date = models.CharField(max_length=32, verbose_name="Date", null=True, unique=False)
    total_debits_bank = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Total Debits Bank", null=True)
    total_credits_bank = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Total Credits Bank", null=True)
    bank_opening_balance = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Bank Opening Balance", null=True)
    bank_closing_balance = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Bank Closing Balance", null=True)
    approved_by = models.PositiveIntegerField(verbose_name="Approved By", null=True)
    approved_date = models.CharField(max_length=64, verbose_name="Approved Date", null=True)

class DailyBalancesGL(models.Model):
    class Meta:
        db_table = "daily_balances_gl"

    daily_balances_gl_id = models.AutoField(primary_key=True)
    tenants_id = models.PositiveIntegerField(verbose_name="Tenants Id (Business Module - Tenant Id)")
    groups_id = models.PositiveIntegerField(verbose_name="Groups Id (Business Module - Groups Id)")
    entities_id = models.PositiveIntegerField(verbose_name="Entities Id (Business Module - Entities Id)")
    m_processing_layer_id = models.PositiveIntegerField(verbose_name="M Processing Layer Id", null=True)
    m_processing_sub_layer_id = models.PositiveIntegerField(verbose_name="M Processing Sub Layer Id", null=True)
    processing_layer_id = models.PositiveIntegerField(verbose_name="Processing Layer Id", null=True)
    date = models.CharField(max_length=32, verbose_name="Date", null=True, unique=False)
    total_debits_gl = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Total Debits GL", null=True)
    total_credits_gl = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Total Credits GL", null=True)
    gl_opening_balance = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="GL Opening Balance", null=True)
    gl_closing_balance = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="GL Closing Balance", null=True)
    approved_by = models.PositiveIntegerField(verbose_name="Approved By", null=True)
    approved_date = models.CharField(max_length=64, verbose_name="Approved Date", null=True)