from django.db import models
from django.utils import timezone

# Create your models here.

class FileUploads(models.Model):
    class Meta:
        db_table = "file_uploads"

    id = models.AutoField(primary_key=True)
    tenants_id = models.PositiveIntegerField(verbose_name="Tenants Id (Business Module - Tenant Id)", null=False)
    groups_id = models.PositiveIntegerField(verbose_name="Groups Id (Business Module - Groups Id)", null=False)
    entities_id = models.PositiveIntegerField(verbose_name="Entities Id (Business Module - Entities Id)", null=False)
    m_source_id = models.PositiveIntegerField(verbose_name="Source Id (Business Module - Source Id)", null=False)
    m_processing_layer_id = models.PositiveIntegerField(verbose_name="M Processing Layer Id (Business Module - M Processing Layer Id)", null=False)
    m_processing_sub_layer_id = models.PositiveIntegerField(verbose_name="M Processing Sub Layer Id (Business Module - M Processing Sub Layer Id)", null=False)
    processing_layer_id = models.PositiveIntegerField(verbose_name="Processing Layer Id (Business Module - Processing Layer Id)", null=False)
    processing_layer_name = models.CharField(max_length=64, verbose_name="Processing Layer Name", null=True)
    source_type = models.CharField(max_length=128, verbose_name="File Name", null=True)
    extraction_type = models.CharField(max_length=128, verbose_name="File Name", null=True)
    file_name = models.CharField(max_length=128, verbose_name="File Name", null=True)
    file_upload_type = models.CharField(max_length=64, verbose_name="File Upload Type", null=False)
    file_size_bytes = models.PositiveIntegerField(verbose_name="File Size Bytes", null=True)
    file_path = models.CharField(max_length=512, verbose_name="File Path", null=True)
    status = models.CharField(max_length=32, verbose_name="Status", null=True)
    comments = models.TextField(verbose_name="Comments", null=True)
    file_row_count = models.PositiveIntegerField(verbose_name="File Row Count (Business Module - File Row Count)", null=True)
    is_processed = models.BooleanField(default=True, verbose_name="Active ?")
    is_processing = models.PositiveIntegerField(verbose_name="Is Processing?")
    input_date = models.CharField(max_length=64, verbose_name="Input Date", null=True)
    is_active = models.BooleanField(default=True, verbose_name="Active ?")
    created_by = models.PositiveSmallIntegerField(verbose_name="User Id", null=True)
    created_date = models.DateTimeField(default=timezone.now, verbose_name="Created Date")
    modified_by = models.PositiveSmallIntegerField(verbose_name="User Id", null=True)
    modified_date = models.DateTimeField(default=timezone.now, verbose_name="Modified Date")

class StagingInternalRecords(models.Model):
    class Meta:
        db_table = "stg_internal_records"

    id = models.AutoField(primary_key=True)
    tenants_id = models.PositiveIntegerField(verbose_name="Tenants Id (Business Module - Tenant Id)", null=False)
    groups_id = models.PositiveIntegerField(verbose_name="Groups Id (Business Module - Groups Id)", null=False)
    entities_id = models.PositiveIntegerField(verbose_name="Entities Id (Business Module - Entities Id)", null=False)
    file_id = models.PositiveIntegerField(verbose_name="File Id", null=False)
    job_execution_id = models.PositiveIntegerField(verbose_name="Job Execution Id", null=False)
    m_processing_layer_id = models.PositiveIntegerField(verbose_name="M Processing Layer Id (Business Module - M Processing Layer Id)", null=False)
    m_processing_sub_layer_id = models.PositiveIntegerField(verbose_name="M Processing Sub Layer Id (Business Module - M Processing Sub Layer Id)", null=False)
    processing_layer_id = models.PositiveIntegerField(verbose_name="Processing Layer Id (Business Module - Processing Layer Id)", null=False)
    processing_layer_name = models.CharField(max_length=64, verbose_name="Processing Layer Name", null=True)
    int_processing_status_1 = models.CharField(max_length=64, verbose_name="Int Processing Status 1", null=True)
    int_processing_status_2 = models.CharField(max_length=64, verbose_name="Int Processing Status 2", null=True)
    int_processing_status_3 = models.CharField(max_length=64, verbose_name="Int Processing Status 3", null=True)
    int_processing_status_4 = models.CharField(max_length=64, verbose_name="Int Processing Status 4", null=True)
    int_processing_status_5 = models.CharField(max_length=64, verbose_name="Int Processing Status 5", null=True)
    int_match_type_1 = models.CharField(max_length=64, verbose_name="Int Match Type 1", null=True)
    int_match_type_2 = models.CharField(max_length=64, verbose_name="Int Match Type 2", null=True)
    int_match_type_3 = models.CharField(max_length=64, verbose_name="Int Match Type 3", null=True)
    int_match_type_4 = models.CharField(max_length=64, verbose_name="Int Match Type 4", null=True)
    int_match_type_5 = models.CharField(max_length=64, verbose_name="Int Match Type 5", null=True)
    int_reference_text_1 = models.TextField(verbose_name="Int Reference Text 1", null=True)
    int_reference_text_2 = models.TextField(verbose_name="Int Reference Text 2", null=True)
    int_reference_text_3 = models.TextField(verbose_name="Int Reference Text 3", null=True)
    int_reference_text_4 = models.TextField(verbose_name="Int Reference Text 4", null=True)
    int_reference_text_5 = models.TextField(verbose_name="Int Reference Text 5", null=True)
    int_reference_text_6 = models.TextField(verbose_name="Int Reference Text 6", null=True)
    int_reference_text_7 = models.TextField(verbose_name="Int Reference Text 7", null=True)
    int_reference_text_8 = models.TextField(verbose_name="Int Reference Text 8", null=True)
    int_reference_text_9 = models.TextField(verbose_name="Int Reference Text 9", null=True)
    int_reference_text_10 = models.TextField(verbose_name="Int Reference Text 10", null=True)
    int_reference_text_11 = models.TextField(verbose_name="Int Reference Text 11", null=True)
    int_reference_text_12 = models.TextField(verbose_name="Int Reference Text 12", null=True)
    int_reference_text_13 = models.TextField(verbose_name="Int Reference Text 13", null=True)
    int_reference_text_14 = models.TextField(verbose_name="Int Reference Text 14", null=True)
    int_reference_text_15 = models.TextField(verbose_name="Int Reference Text 15", null=True)
    int_reference_text_16 = models.TextField(verbose_name="Int Reference Text 16", null=True)
    int_reference_text_17 = models.TextField(verbose_name="Int Reference Text 17", null=True)
    int_reference_text_18 = models.TextField(verbose_name="Int Reference Text 18", null=True)
    int_reference_text_19 = models.TextField(verbose_name="Int Reference Text 19", null=True)
    int_reference_text_20 = models.TextField(verbose_name="Int Reference Text 20", null=True)
    int_reference_text_21 = models.TextField(verbose_name="Int Reference Text 21", null=True)
    int_reference_text_22 = models.TextField(verbose_name="Int Reference Text 22", null=True)
    int_reference_text_23 = models.TextField(verbose_name="Int Reference Text 23", null=True)
    int_reference_text_24 = models.TextField(verbose_name="Int Reference Text 24", null=True)
    int_reference_text_25 = models.TextField(verbose_name="Int Reference Text 25", null=True)
    int_reference_text_26 = models.TextField(verbose_name="Int Reference Text 26", null=True)
    int_reference_text_27 = models.TextField(verbose_name="Int Reference Text 27", null=True)
    int_reference_text_28 = models.TextField(verbose_name="Int Reference Text 28", null=True)
    int_reference_text_29 = models.TextField(verbose_name="Int Reference Text 29", null=True)
    int_reference_text_30 = models.TextField(verbose_name="Int Reference Text 30", null=True)
    int_reference_text_31 = models.TextField(verbose_name="Int Reference Text 31", null=True)
    int_reference_text_32 = models.TextField(verbose_name="Int Reference Text 32", null=True)
    int_reference_text_33 = models.TextField(verbose_name="Int Reference Text 33", null=True)
    int_reference_text_34 = models.TextField(verbose_name="Int Reference Text 34", null=True)
    int_reference_text_35 = models.TextField(verbose_name="Int Reference Text 35", null=True)
    int_extracted_text_1 = models.TextField(verbose_name="Int Extracted Text 1", null=True)
    int_extracted_text_2 = models.TextField(verbose_name="Int Extracted Text 2", null=True)
    int_extracted_text_3 = models.TextField(verbose_name="Int Extracted Text 3", null=True)
    int_extracted_text_4 = models.TextField(verbose_name="Int Extracted Text 4", null=True)
    int_extracted_text_5 = models.TextField(verbose_name="Int Extracted Text 5", null=True)
    int_extracted_text_6 = models.TextField(verbose_name="Int Extracted Text 6", null=True)
    int_extracted_text_7 = models.TextField(verbose_name="Int Extracted Text 7", null=True)
    int_extracted_text_8 = models.TextField(verbose_name="Int Extracted Text 8", null=True)
    int_extracted_text_9 = models.TextField(verbose_name="Int Extracted Text 9", null=True)
    int_extracted_text_10 = models.TextField(verbose_name="Int Extracted Text 10", null=True)
    int_extracted_text_11 = models.TextField(verbose_name="Int Extracted Text 11", null=True)
    int_extracted_text_12 = models.TextField(verbose_name="Int Extracted Text 12", null=True)
    int_extracted_text_13 = models.TextField(verbose_name="Int Extracted Text 13", null=True)
    int_extracted_text_14 = models.TextField(verbose_name="Int Extracted Text 14", null=True)
    int_extracted_text_15 = models.TextField(verbose_name="Int Extracted Text 15", null=True)
    int_extracted_text_16 = models.TextField(verbose_name="Int Extracted Text 16", null=True)
    int_extracted_text_17 = models.TextField(verbose_name="Int Extracted Text 17", null=True)
    int_extracted_text_18 = models.TextField(verbose_name="Int Extracted Text 18", null=True)
    int_extracted_text_19 = models.TextField(verbose_name="Int Extracted Text 19", null=True)
    int_extracted_text_20 = models.TextField(verbose_name="Int Extracted Text 20", null=True)
    int_extracted_text_21 = models.TextField(verbose_name="Int Extracted Text 21", null=True)
    int_extracted_text_22 = models.TextField(verbose_name="Int Extracted Text 22", null=True)
    int_extracted_text_23 = models.TextField(verbose_name="Int Extracted Text 23", null=True)
    int_extracted_text_24 = models.TextField(verbose_name="Int Extracted Text 24", null=True)
    int_extracted_text_25 = models.TextField(verbose_name="Int Extracted Text 25", null=True)
    int_extracted_text_26 = models.TextField(verbose_name="Int Extracted Text 26", null=True)
    int_extracted_text_27 = models.TextField(verbose_name="Int Extracted Text 27", null=True)
    int_extracted_text_28 = models.TextField(verbose_name="Int Extracted Text 28", null=True)
    int_extracted_text_29 = models.TextField(verbose_name="Int Extracted Text 29", null=True)
    int_extracted_text_30 = models.TextField(verbose_name="Int Extracted Text 30", null=True)
    int_extracted_text_31 = models.TextField(verbose_name="Int Extracted Text 31", null=True)
    int_extracted_text_32 = models.TextField(verbose_name="Int Extracted Text 32", null=True)
    int_extracted_text_33 = models.TextField(verbose_name="Int Extracted Text 33", null=True)
    int_extracted_text_34 = models.TextField(verbose_name="Int Extracted Text 34", null=True)
    int_extracted_text_35 = models.TextField(verbose_name="Int Extracted Text 35", null=True)
    int_extracted_text_36 = models.TextField(verbose_name="Int Extracted Text 36", null=True)
    int_extracted_text_37 = models.TextField(verbose_name="Int Extracted Text 37", null=True)
    int_extracted_text_38 = models.TextField(verbose_name="Int Extracted Text 38", null=True)
    int_extracted_text_39 = models.TextField(verbose_name="Int Extracted Text 39", null=True)
    int_extracted_text_40 = models.TextField(verbose_name="Int Extracted Text 40", null=True)
    int_extracted_text_41 = models.TextField(verbose_name="Int Extracted Text 41", null=True)
    int_extracted_text_42 = models.TextField(verbose_name="Int Extracted Text 42", null=True)
    int_extracted_text_43 = models.TextField(verbose_name="Int Extracted Text 43", null=True)
    int_extracted_text_44 = models.TextField(verbose_name="Int Extracted Text 44", null=True)
    int_extracted_text_45 = models.TextField(verbose_name="Int Extracted Text 45", null=True)
    int_extracted_text_46 = models.TextField(verbose_name="Int Extracted Text 46", null=True)
    int_extracted_text_47 = models.TextField(verbose_name="Int Extracted Text 47", null=True)
    int_extracted_text_48 = models.TextField(verbose_name="Int Extracted Text 48", null=True)
    int_extracted_text_49 = models.TextField(verbose_name="Int Extracted Text 49", null=True)
    int_extracted_text_50 = models.TextField(verbose_name="Int Extracted Text 50", null=True)
    int_reference_date_time_1 = models.TextField(verbose_name="Int Reference Date Time 1", null=True)
    int_reference_date_time_2 = models.TextField(verbose_name="Int Reference Date Time 2", null=True)
    int_reference_date_time_3 = models.TextField(verbose_name="Int Reference Date Time 3", null=True)
    int_reference_date_time_4 = models.TextField(verbose_name="Int Reference Date Time 4", null=True)
    int_reference_date_time_5 = models.TextField(verbose_name="Int Reference Date Time 5", null=True)
    int_debit_amount = models.CharField(max_length=64, verbose_name="Int Debit Amount", null=True)
    int_credit_amount = models.CharField(max_length=64, verbose_name="Int Credit Amount", null=True)
    int_amount_1 = models.CharField(max_length=64, verbose_name="Int Amount 1", null=True)
    int_amount_2 = models.CharField(max_length=64, verbose_name="Int Amount 2", null=True)
    int_amount_3 = models.CharField(max_length=64, verbose_name="Int Amount 3", null=True)
    int_amount_4 = models.CharField(max_length=64, verbose_name="Int Amount 4", null=True)
    int_amount_5 = models.CharField(max_length=64, verbose_name="Int Amount 5", null=True)
    int_amount_6 = models.CharField(max_length=64, verbose_name="Int Amount 6", null=True)
    int_amount_7 = models.CharField(max_length=64, verbose_name="Int Amount 7", null=True)
    int_amount_8 = models.CharField(max_length=64, verbose_name="Int Amount 8", null=True)
    int_amount_9 = models.CharField(max_length=64, verbose_name="Int Amount 9", null=True)
    int_amount_10 = models.CharField(max_length=64, verbose_name="Int Amount 10", null=True)
    int_generated_num_1 = models.CharField(max_length=8, verbose_name="Int Generated Number 1", null=True)
    int_generated_num_2 = models.CharField(max_length=8, verbose_name="Int Generated Number 2", null=True)
    int_generated_num_3 = models.CharField(max_length=8, verbose_name="Int Generated Number 3", null=True)
    int_generated_num_4 = models.CharField(max_length=8, verbose_name="Int Generated Number 4", null=True)
    int_generated_num_5 = models.CharField(max_length=8, verbose_name="Int Generated Number 5", null=True)
    int_generated_num_6 = models.CharField(max_length=8, verbose_name="Int Generated Number 6", null=True)
    int_generated_num_7 = models.CharField(max_length=8, verbose_name="Int Generated Number 7", null=True)
    int_generated_num_8 = models.CharField(max_length=8, verbose_name="Int Generated Number 8", null=True)
    int_generated_num_9 = models.CharField(max_length=8, verbose_name="Int Generated Number 9", null=True)
    int_generated_num_10 = models.CharField(max_length=8, verbose_name="Int Generated Number 10", null=True)
    is_active = models.CharField(max_length=1, verbose_name="Active ?", null=True)
    created_by = models.CharField(max_length=16, verbose_name="User Id", null=True)
    created_date = models.DateTimeField(auto_now_add = True, verbose_name="Created Date")
    modified_by = models.CharField(max_length=16, verbose_name="User Id", null=True)
    modified_date = models.DateTimeField(auto_now = True, verbose_name="Modified Date")

class StagingExternalRecords(models.Model):
    class Meta:
        db_table = "stg_external_records"

    id = models.AutoField(primary_key=True)
    tenants_id = models.PositiveIntegerField(verbose_name="Tenants Id (Business Module - Tenant Id)", null=False)
    groups_id = models.PositiveIntegerField(verbose_name="Groups Id (Business Module - Groups Id)", null=False)
    entities_id = models.PositiveIntegerField(verbose_name="Entities Id (Business Module - Entities Id)", null=False)
    file_id = models.PositiveIntegerField(verbose_name="File Id", null=False)
    job_execution_id = models.PositiveIntegerField(verbose_name="Job Execution Id", null=False)
    m_processing_layer_id = models.PositiveIntegerField(verbose_name="M Processing Layer Id (Business Module - M Processing Layer Id)", null=False)
    m_processing_sub_layer_id = models.PositiveIntegerField(verbose_name="M Processing Sub Layer Id (Business Module - M Processing Sub Layer Id)", null=False)
    processing_layer_id = models.PositiveIntegerField(verbose_name="Processing Layer Id (Business Module - Processing Layer Id)", null=False)
    processing_layer_name = models.CharField(max_length=64, verbose_name="Processing Layer Name", null=True)
    ext_processing_status_1 = models.CharField(max_length=64, verbose_name="Ext Processing Status 1", null=True)
    ext_processing_status_2 = models.CharField(max_length=64, verbose_name="Ext Processing Status 2", null=True)
    ext_processing_status_3 = models.CharField(max_length=64, verbose_name="Ext Processing Status 3", null=True)
    ext_processing_status_4 = models.CharField(max_length=64, verbose_name="Ext Processing Status 4", null=True)
    ext_processing_status_5 = models.CharField(max_length=64, verbose_name="Ext Processing Status 5", null=True)
    ext_match_type_1 = models.CharField(max_length=64, verbose_name="Ext Match Type 1", null=True)
    ext_match_type_2 = models.CharField(max_length=64, verbose_name="Ext Match Type 2", null=True)
    ext_match_type_3 = models.CharField(max_length=64, verbose_name="Ext Match Type 3", null=True)
    ext_match_type_4 = models.CharField(max_length=64, verbose_name="Ext Match Type 4", null=True)
    ext_match_type_5 = models.CharField(max_length=64, verbose_name="Ext Match Type 5", null=True)
    ext_reference_text_1 = models.TextField(verbose_name="Ext Reference Text 1", null=True)
    ext_reference_text_2 = models.TextField(verbose_name="Ext Reference Text 2", null=True)
    ext_reference_text_3 = models.TextField(verbose_name="Ext Reference Text 3", null=True)
    ext_reference_text_4 = models.TextField(verbose_name="Ext Reference Text 4", null=True)
    ext_reference_text_5 = models.TextField(verbose_name="Ext Reference Text 5", null=True)
    ext_reference_text_6 = models.TextField(verbose_name="Ext Reference Text 6", null=True)
    ext_reference_text_7 = models.TextField(verbose_name="Ext Reference Text 7", null=True)
    ext_reference_text_8 = models.TextField(verbose_name="Ext Reference Text 8", null=True)
    ext_reference_text_9 = models.TextField(verbose_name="Ext Reference Text 9", null=True)
    ext_reference_text_10 = models.TextField(verbose_name="Ext Reference Text 10", null=True)
    ext_reference_text_11 = models.TextField(verbose_name="Ext Reference Text 11", null=True)
    ext_reference_text_12 = models.TextField(verbose_name="Ext Reference Text 12", null=True)
    ext_reference_text_13 = models.TextField(verbose_name="Ext Reference Text 13", null=True)
    ext_reference_text_14 = models.TextField(verbose_name="Ext Reference Text 14", null=True)
    ext_reference_text_15 = models.TextField(verbose_name="Ext Reference Text 15", null=True)
    ext_reference_text_16 = models.TextField(verbose_name="Ext Reference Text 16", null=True)
    ext_reference_text_17 = models.TextField(verbose_name="Ext Reference Text 17", null=True)
    ext_reference_text_18 = models.TextField(verbose_name="Ext Reference Text 18", null=True)
    ext_reference_text_19 = models.TextField(verbose_name="Ext Reference Text 19", null=True)
    ext_reference_text_20 = models.TextField(verbose_name="Ext Reference Text 20", null=True)
    ext_reference_text_21 = models.TextField(verbose_name="Ext Reference Text 21", null=True)
    ext_reference_text_22 = models.TextField(verbose_name="Ext Reference Text 22", null=True)
    ext_reference_text_23 = models.TextField(verbose_name="Ext Reference Text 23", null=True)
    ext_reference_text_24 = models.TextField(verbose_name="Ext Reference Text 24", null=True)
    ext_reference_text_25 = models.TextField(verbose_name="Ext Reference Text 25", null=True)
    ext_extracted_text_1 = models.TextField(verbose_name="Ext Extracted Text 1", null=True)
    ext_extracted_text_2 = models.TextField(verbose_name="Ext Extracted Text 2", null=True)
    ext_extracted_text_3 = models.TextField(verbose_name="Ext Extracted Text 3", null=True)
    ext_extracted_text_4 = models.TextField(verbose_name="Ext Extracted Text 4", null=True)
    ext_extracted_text_5 = models.TextField(verbose_name="Ext Extracted Text 5", null=True)
    ext_extracted_text_6 = models.TextField(verbose_name="Ext Extracted Text 6", null=True)
    ext_extracted_text_7 = models.TextField(verbose_name="Ext Extracted Text 7", null=True)
    ext_extracted_text_8 = models.TextField(verbose_name="Ext Extracted Text 8", null=True)
    ext_extracted_text_9 = models.TextField(verbose_name="Ext Extracted Text 9", null=True)
    ext_extracted_text_10 = models.TextField(verbose_name="Ext Extracted Text 10", null=True)
    ext_reference_date_time_1 = models.TextField(verbose_name="Ext Reference Date Time 1", null=True)
    ext_reference_date_time_2 = models.TextField(verbose_name="Ext Reference Date Time 2", null=True)
    ext_reference_date_time_3 = models.TextField(verbose_name="Ext Reference Date Time 3", null=True)
    ext_reference_date_time_4 = models.TextField(verbose_name="Ext Reference Date Time 4", null=True)
    ext_reference_date_time_5 = models.TextField(verbose_name="Ext Reference Date Time 5", null=True)
    ext_debit_amount = models.CharField(max_length=64, verbose_name="Ext Debit Amount", null=True)
    ext_credit_amount = models.CharField(max_length=64, verbose_name="Ext Credit Amount", null=True)
    ext_amount_1 = models.CharField(max_length=64, verbose_name="Ext Amount 1", null=True)
    ext_amount_2 = models.CharField(max_length=64, verbose_name="Ext Amount 2", null=True)
    ext_amount_3 = models.CharField(max_length=64, verbose_name="Ext Amount 3", null=True)
    ext_amount_4 = models.CharField(max_length=64, verbose_name="Ext Amount 4", null=True)
    ext_amount_5 = models.CharField(max_length=64, verbose_name="Ext Amount 5", null=True)
    ext_amount_6 = models.CharField(max_length=64, verbose_name="Ext Amount 6", null=True)
    ext_amount_7 = models.CharField(max_length=64, verbose_name="Ext Amount 7", null=True)
    ext_amount_8 = models.CharField(max_length=64, verbose_name="Ext Amount 8", null=True)
    ext_amount_9 = models.CharField(max_length=64, verbose_name="Ext Amount 9", null=True)
    ext_amount_10 = models.CharField(max_length=64, verbose_name="Ext Amount 10", null=True)
    ext_generated_num_1 = models.CharField(max_length=8, null=True)
    ext_generated_num_2 = models.CharField(max_length=8, verbose_name="Ext Generated Number 2", null=True)
    ext_generated_num_3 = models.CharField(max_length=8, verbose_name="Ext Generated Number 3", null=True)
    ext_generated_num_4 = models.CharField(max_length=8, verbose_name="Ext Generated Number 4", null=True)
    ext_generated_num_5 = models.CharField(max_length=8, verbose_name="Ext Generated Number 5", null=True)
    ext_generated_num_6 = models.CharField(max_length=8, verbose_name="Ext Generated Number 6", null=True)
    ext_generated_num_7 = models.CharField(max_length=8, verbose_name="Ext Generated Number 7", null=True)
    ext_generated_num_8 = models.CharField(max_length=8, verbose_name="Ext Generated Number 8", null=True)
    ext_generated_num_9 = models.CharField(max_length=8, verbose_name="Ext Generated Number 9", null=True)
    ext_generated_num_10 = models.CharField(max_length=8, verbose_name="Ext Generated Number 10", null=True)
    is_active = models.CharField(max_length=1, verbose_name="Active ?", null=True)
    created_by = models.CharField(max_length=16, verbose_name="User Id", null=True)
    created_date = models.DateTimeField(auto_now_add = True, verbose_name="Created Date")
    modified_by = models.CharField(max_length=16, verbose_name="User Id", null=True)
    modified_date = models.DateTimeField(auto_now = True, verbose_name="Modified Date")

class StagingUTRDetails(models.Model):
    class Meta:
        db_table = "stg_utr_details"

    id = models.AutoField(primary_key=True)
    tenants_id = models.PositiveIntegerField(verbose_name="Tenants Id (Business Module - Tenant Id)", null=False)
    groups_id = models.PositiveIntegerField(verbose_name="Groups Id (Business Module - Groups Id)", null=False)
    entities_id = models.PositiveIntegerField(verbose_name="Entities Id (Business Module - Entities Id)", null=False)
    file_id = models.PositiveIntegerField(verbose_name="File Id", null=False)
    job_execution_id = models.PositiveIntegerField(verbose_name="Job Execution Id", null=False)
    m_processing_layer_id = models.PositiveIntegerField(verbose_name="M Processing Layer Id (Business Module - M Processing Layer Id)", null=False)
    m_processing_sub_layer_id = models.PositiveIntegerField(verbose_name="M Processing Sub Layer Id (Business Module - M Processing Sub Layer Id)", null=False)
    processing_layer_id = models.PositiveIntegerField(verbose_name="Processing Layer Id (Business Module - Processing Layer Id)", null=False)
    processing_layer_name = models.CharField(max_length=64, verbose_name="Processing Layer Name", null=True)
    utr_processing_status_1 = models.CharField(max_length=64, verbose_name="UTR Processing Status 1", null=True)
    utr_processing_status_2 = models.CharField(max_length=64, verbose_name="UTR Processing Status 2", null=True)
    utr_match_type_1 = models.CharField(max_length=64, verbose_name="UTR Match Type 1", null=True)
    utr_match_type_2 = models.CharField(max_length=64, verbose_name="UTR Match Type 2", null=True)
    utr_reference_text_1 = models.TextField(verbose_name="UTR Reference Text 1", null=True)
    utr_reference_text_2 = models.TextField(verbose_name="UTR Reference Text 2", null=True)
    utr_reference_text_3 = models.TextField(verbose_name="UTR Reference Text 3", null=True)
    utr_reference_text_4 = models.TextField(verbose_name="UTR Reference Text 4", null=True)
    utr_reference_text_5 = models.TextField(verbose_name="UTR Reference Text 5", null=True)
    utr_reference_text_6 = models.TextField(verbose_name="UTR Reference Text 6", null=True)
    utr_reference_text_7 = models.TextField(verbose_name="UTR Reference Text 7", null=True)
    utr_reference_text_8 = models.TextField(verbose_name="UTR Reference Text 8", null=True)
    utr_reference_text_9 = models.TextField(verbose_name="UTR Reference Text 9", null=True)
    utr_reference_text_10 = models.TextField(verbose_name="UTR Reference Text 10", null=True)
    utr_reference_text_11 = models.TextField(verbose_name="UTR Reference Text 11", null=True)
    utr_reference_text_12 = models.TextField(verbose_name="UTR Reference Text 12", null=True)
    utr_reference_text_13 = models.TextField(verbose_name="UTR Reference Text 13", null=True)
    utr_reference_text_14 = models.TextField(verbose_name="UTR Reference Text 14", null=True)
    utr_reference_text_15 = models.TextField(verbose_name="UTR Reference Text 15", null=True)
    utr_reference_text_16 = models.TextField(verbose_name="UTR Reference Text 16", null=True)
    utr_reference_text_17 = models.TextField(verbose_name="UTR Reference Text 17", null=True)
    utr_reference_text_18 = models.TextField(verbose_name="UTR Reference Text 18", null=True)
    utr_reference_text_19 = models.TextField(verbose_name="UTR Reference Text 19", null=True)
    utr_reference_text_20 = models.TextField(verbose_name="UTR Reference Text 20", null=True)
    utr_reference_text_21 = models.TextField(verbose_name="UTR Reference Text 21", null=True)
    utr_reference_text_22 = models.TextField(verbose_name="UTR Reference Text 22", null=True)
    utr_reference_text_23 = models.TextField(verbose_name="UTR Reference Text 23", null=True)
    utr_reference_text_24 = models.TextField(verbose_name="UTR Reference Text 24", null=True)
    utr_reference_text_25 = models.TextField(verbose_name="UTR Reference Text 25", null=True)
    utr_reference_date_time_1 = models.DateTimeField(verbose_name="UTR Reference Date Time 1", null=True)
    utr_reference_date_time_2 = models.DateTimeField(verbose_name="UTR Reference Date Time 2", null=True)
    utr_reference_date_time_3 = models.DateTimeField(verbose_name="UTR Reference Date Time 3", null=True)
    utr_reference_date_time_4 = models.DateTimeField(verbose_name="UTR Reference Date Time 4", null=True)
    utr_reference_date_time_5 = models.DateTimeField(verbose_name="UTR Reference Date Time 5", null=True)
    utr_amount_1 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="UTR Amount 1", null=True)
    utr_amount_2 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="UTR Amount 2", null=True)
    utr_generated_num_1 = models.PositiveIntegerField(verbose_name="UTR Generated Number 1", null=True)
    utr_generated_num_2 = models.PositiveIntegerField(verbose_name="UTR Generated Number 2", null=True)
    utr_generated_num_3 = models.PositiveIntegerField(verbose_name="UTR Generated Number 3", null=True)
    utr_generated_num_4 = models.PositiveIntegerField(verbose_name="UTR Generated Number 4", null=True)
    utr_generated_num_5 = models.PositiveIntegerField(verbose_name="UTR Generated Number 5", null=True)
    is_active = models.BooleanField(default=True, verbose_name="Active ?")
    created_by = models.PositiveSmallIntegerField(verbose_name="User Id", null=True)
    created_date = models.DateTimeField(auto_now_add = True, verbose_name="Created Date")
    modified_by = models.PositiveSmallIntegerField(verbose_name="User Id", null=True)
    modified_date = models.DateTimeField(auto_now = True, verbose_name="Modified Date")

class InternalRecords(models.Model):
    class Meta:
        db_table = "t_internal_records"

    id = models.AutoField(primary_key=True)
    tenants_id = models.PositiveIntegerField(verbose_name="Tenants Id (Business Module - Tenant Id)", null=False)
    groups_id = models.PositiveIntegerField(verbose_name="Groups Id (Business Module - Groups Id)", null=False)
    entities_id = models.PositiveIntegerField(verbose_name="Entities Id (Business Module - Entities Id)", null=False)
    file_id = models.PositiveIntegerField(verbose_name="File Id", null=False)
    job_execution_id = models.PositiveIntegerField(verbose_name="Job Execution Id", null=False)
    m_processing_layer_id = models.PositiveIntegerField(verbose_name="M Processing Layer Id (Business Module - M Processing Layer Id)", null=False)
    m_processing_sub_layer_id = models.PositiveIntegerField(verbose_name="M Processing Sub Layer Id (Business Module - M Processing Sub Layer Id)", null=False)
    processing_layer_id = models.PositiveIntegerField(verbose_name="Processing Layer Id (Business Module - Processing Layer Id)", null=False)
    processing_layer_name = models.CharField(max_length=64, verbose_name="Processing Layer Name", null=True)
    int_processing_status_1 = models.CharField(max_length=64, verbose_name="Int Processing Status 1", null=True)
    int_processing_status_2 = models.CharField(max_length=64, verbose_name="Int Processing Status 2", null=True)
    int_processing_status_3 = models.CharField(max_length=64, verbose_name="Int Processing Status 3", null=True)
    int_processing_status_4 = models.CharField(max_length=64, verbose_name="Int Processing Status 4", null=True)
    int_processing_status_5 = models.CharField(max_length=64, verbose_name="Int Processing Status 5", null=True)
    int_match_type_1 = models.CharField(max_length=64, verbose_name="Int Match Type 1", null=True)
    int_match_type_2 = models.CharField(max_length=64, verbose_name="Int Match Type 2", null=True)
    int_match_type_3 = models.CharField(max_length=64, verbose_name="Int Match Type 3", null=True)
    int_match_type_4 = models.CharField(max_length=64, verbose_name="Int Match Type 4", null=True)
    int_match_type_5 = models.CharField(max_length=64, verbose_name="Int Match Type 5", null=True)
    int_reference_text_1 = models.TextField(verbose_name="Int Reference Text 1", null=True)
    int_reference_text_2 = models.TextField(verbose_name="Int Reference Text 2", null=True)
    int_reference_text_3 = models.TextField(verbose_name="Int Reference Text 3", null=True)
    int_reference_text_4 = models.TextField(verbose_name="Int Reference Text 4", null=True)
    int_reference_text_5 = models.TextField(verbose_name="Int Reference Text 5", null=True)
    int_reference_text_6 = models.TextField(verbose_name="Int Reference Text 6", null=True)
    int_reference_text_7 = models.TextField(verbose_name="Int Reference Text 7", null=True)
    int_reference_text_8 = models.TextField(verbose_name="Int Reference Text 8", null=True)
    int_reference_text_9 = models.TextField(verbose_name="Int Reference Text 9", null=True)
    int_reference_text_10 = models.TextField(verbose_name="Int Reference Text 10", null=True)
    int_reference_text_11 = models.TextField(verbose_name="Int Reference Text 11", null=True)
    int_reference_text_12 = models.TextField(verbose_name="Int Reference Text 12", null=True)
    int_reference_text_13 = models.TextField(verbose_name="Int Reference Text 13", null=True)
    int_reference_text_14 = models.TextField(verbose_name="Int Reference Text 14", null=True)
    int_reference_text_15 = models.TextField(verbose_name="Int Reference Text 15", null=True)
    int_reference_text_16 = models.TextField(verbose_name="Int Reference Text 16", null=True)
    int_reference_text_17 = models.TextField(verbose_name="Int Reference Text 17", null=True)
    int_reference_text_18 = models.TextField(verbose_name="Int Reference Text 18", null=True)
    int_reference_text_19 = models.TextField(verbose_name="Int Reference Text 19", null=True)
    int_reference_text_20 = models.TextField(verbose_name="Int Reference Text 20", null=True)
    int_reference_text_21 = models.TextField(verbose_name="Int Reference Text 21", null=True)
    int_reference_text_22 = models.TextField(verbose_name="Int Reference Text 22", null=True)
    int_reference_text_23 = models.TextField(verbose_name="Int Reference Text 23", null=True)
    int_reference_text_24 = models.TextField(verbose_name="Int Reference Text 24", null=True)
    int_reference_text_25 = models.TextField(verbose_name="Int Reference Text 25", null=True)
    int_reference_text_26 = models.TextField(verbose_name="Int Reference Text 26", null=True)
    int_reference_text_27 = models.TextField(verbose_name="Int Reference Text 27", null=True)
    int_reference_text_28 = models.TextField(verbose_name="Int Reference Text 28", null=True)
    int_reference_text_29 = models.TextField(verbose_name="Int Reference Text 29", null=True)
    int_reference_text_30 = models.TextField(verbose_name="Int Reference Text 30", null=True)
    int_reference_text_31 = models.TextField(verbose_name="Int Reference Text 31", null=True)
    int_reference_text_32 = models.TextField(verbose_name="Int Reference Text 32", null=True)
    int_reference_text_33 = models.TextField(verbose_name="Int Reference Text 33", null=True)
    int_reference_text_34 = models.TextField(verbose_name="Int Reference Text 34", null=True)
    int_reference_text_35 = models.TextField(verbose_name="Int Reference Text 35", null=True)
    int_extracted_text_1 = models.CharField(max_length=512, verbose_name="Int Extracted Text 1", null=True)
    int_extracted_text_2 = models.CharField(max_length=512, verbose_name="Int Extracted Text 2", null=True)
    int_extracted_text_3 = models.CharField(max_length=512, verbose_name="Int Extracted Text 3", null=True)
    int_extracted_text_4 = models.CharField(max_length=512, verbose_name="Int Extracted Text 4", null=True)
    int_extracted_text_5 = models.CharField(max_length=512, verbose_name="Int Extracted Text 5", null=True)
    int_extracted_text_6 = models.CharField(max_length=512, verbose_name="Int Extracted Text 6", null=True)
    int_extracted_text_7 = models.CharField(max_length=512, verbose_name="Int Extracted Text 7", null=True)
    int_extracted_text_8 = models.CharField(max_length=512, verbose_name="Int Extracted Text 8", null=True)
    int_extracted_text_9 = models.CharField(max_length=512, verbose_name="Int Extracted Text 9", null=True)
    int_extracted_text_10 = models.CharField(max_length=512, verbose_name="Int Extracted Text 10", null=True)
    int_extracted_text_11 = models.TextField(verbose_name="Int Extracted Text 11", null=True)
    int_extracted_text_12 = models.TextField(verbose_name="Int Extracted Text 12", null=True)
    int_extracted_text_13 = models.TextField(verbose_name="Int Extracted Text 13", null=True)
    int_extracted_text_14 = models.TextField(verbose_name="Int Extracted Text 14", null=True)
    int_extracted_text_15 = models.TextField(verbose_name="Int Extracted Text 15", null=True)
    int_extracted_text_16 = models.TextField(verbose_name="Int Extracted Text 16", null=True)
    int_extracted_text_17 = models.TextField(verbose_name="Int Extracted Text 17", null=True)
    int_extracted_text_18 = models.TextField(verbose_name="Int Extracted Text 18", null=True)
    int_extracted_text_19 = models.TextField(verbose_name="Int Extracted Text 19", null=True)
    int_extracted_text_20 = models.TextField(verbose_name="Int Extracted Text 20", null=True)
    int_extracted_text_21 = models.TextField(verbose_name="Int Extracted Text 21", null=True)
    int_extracted_text_22 = models.TextField(verbose_name="Int Extracted Text 22", null=True)
    int_extracted_text_23 = models.TextField(verbose_name="Int Extracted Text 23", null=True)
    int_extracted_text_24 = models.TextField(verbose_name="Int Extracted Text 24", null=True)
    int_extracted_text_25 = models.TextField(verbose_name="Int Extracted Text 25", null=True)
    int_extracted_text_26 = models.TextField(verbose_name="Int Extracted Text 26", null=True)
    int_extracted_text_27 = models.TextField(verbose_name="Int Extracted Text 27", null=True)
    int_extracted_text_28 = models.TextField(verbose_name="Int Extracted Text 28", null=True)
    int_extracted_text_29 = models.TextField(verbose_name="Int Extracted Text 29", null=True)
    int_extracted_text_30 = models.TextField(verbose_name="Int Extracted Text 30", null=True)
    int_extracted_text_31 = models.TextField(verbose_name="Int Extracted Text 31", null=True)
    int_extracted_text_32 = models.TextField(verbose_name="Int Extracted Text 32", null=True)
    int_extracted_text_33 = models.TextField(verbose_name="Int Extracted Text 33", null=True)
    int_extracted_text_34 = models.TextField(verbose_name="Int Extracted Text 34", null=True)
    int_extracted_text_35 = models.TextField(verbose_name="Int Extracted Text 35", null=True)
    int_extracted_text_36 = models.TextField(verbose_name="Int Extracted Text 36", null=True)
    int_extracted_text_37 = models.TextField(verbose_name="Int Extracted Text 37", null=True)
    int_extracted_text_38 = models.TextField(verbose_name="Int Extracted Text 38", null=True)
    int_extracted_text_39 = models.TextField(verbose_name="Int Extracted Text 39", null=True)
    int_extracted_text_40 = models.TextField(verbose_name="Int Extracted Text 40", null=True)
    int_extracted_text_41 = models.TextField(verbose_name="Int Extracted Text 41", null=True)
    int_extracted_text_42 = models.TextField(verbose_name="Int Extracted Text 42", null=True)
    int_extracted_text_43 = models.TextField(verbose_name="Int Extracted Text 43", null=True)
    int_extracted_text_44 = models.TextField(verbose_name="Int Extracted Text 44", null=True)
    int_extracted_text_45 = models.TextField(verbose_name="Int Extracted Text 45", null=True)
    int_extracted_text_46 = models.TextField(verbose_name="Int Extracted Text 46", null=True)
    int_extracted_text_47 = models.TextField(verbose_name="Int Extracted Text 47", null=True)
    int_extracted_text_48 = models.TextField(verbose_name="Int Extracted Text 48", null=True)
    int_extracted_text_49 = models.TextField(verbose_name="Int Extracted Text 49", null=True)
    int_extracted_text_50 = models.TextField(verbose_name="Int Extracted Text 50", null=True)
    int_reference_date_time_1 = models.DateTimeField(verbose_name="Int Reference Date Time 1", null=True)
    int_reference_date_time_2 = models.DateTimeField(verbose_name="Int Reference Date Time 2", null=True)
    int_reference_date_time_3 = models.DateTimeField(verbose_name="Int Reference Date Time 3", null=True)
    int_reference_date_time_4 = models.DateTimeField(verbose_name="Int Reference Date Time 4", null=True)
    int_reference_date_time_5 = models.DateTimeField(verbose_name="Int Reference Date Time 5", null=True)
    int_debit_amount = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Int Debit Amount", null=True)
    int_credit_amount = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Int Credit Amount", null=True)
    int_amount_1 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Int Amount 1", null=True)
    int_amount_2 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Int Amount 2", null=True)
    int_amount_3 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Int Amount 3", null=True)
    int_amount_4 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Int Amount 4", null=True)
    int_amount_5 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Int Amount 5", null=True)
    int_amount_6 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Int Amount 6", null=True)
    int_amount_7 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Int Amount 7", null=True)
    int_amount_8 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Int Amount 8", null=True)
    int_amount_9 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Int Amount 9", null=True)
    int_amount_10 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Int Amount 10", null=True)
    int_generated_num_1 = models.PositiveIntegerField(verbose_name="Int Generated Number 1", null=True)
    int_generated_num_2 = models.PositiveIntegerField(verbose_name="Int Generated Number 2", null=True)
    int_generated_num_3 = models.PositiveIntegerField(verbose_name="Int Generated Number 3", null=True)
    int_generated_num_4 = models.PositiveIntegerField(verbose_name="Int Generated Number 4", null=True)
    int_generated_num_5 = models.PositiveIntegerField(verbose_name="Int Generated Number 5", null=True)
    int_generated_num_6 = models.PositiveIntegerField(verbose_name="Int Generated Number 6", null=True)
    int_generated_num_7 = models.PositiveIntegerField(verbose_name="Int Generated Number 7", null=True)
    int_generated_num_8 = models.PositiveIntegerField(verbose_name="Int Generated Number 8", null=True)
    int_generated_num_9 = models.PositiveIntegerField(verbose_name="Int Generated Number 9", null=True)
    int_generated_num_10 = models.PositiveIntegerField(verbose_name="Int Generated Number 10", null=True)
    is_active = models.BooleanField(default=True, verbose_name="Active ?")
    created_by = models.PositiveSmallIntegerField(verbose_name="User Id", null=True)
    created_date = models.DateTimeField(auto_now_add = True, verbose_name="Created Date")
    modified_by = models.PositiveSmallIntegerField(verbose_name="User Id", null=True)
    modified_date = models.DateTimeField(auto_now = True, verbose_name="Modified Date")

class ExternalRecords(models.Model):
    class Meta:
        db_table = "t_external_records"

    id = models.AutoField(primary_key=True)
    tenants_id = models.PositiveIntegerField(verbose_name="Tenants Id (Business Module - Tenant Id)", null=False)
    groups_id = models.PositiveIntegerField(verbose_name="Groups Id (Business Module - Groups Id)", null=False)
    entities_id = models.PositiveIntegerField(verbose_name="Entities Id (Business Module - Entities Id)", null=False)
    file_id = models.PositiveIntegerField(verbose_name="File Id", null=False)
    job_execution_id = models.PositiveIntegerField(verbose_name="Job Execution Id", null=False)
    m_processing_layer_id = models.PositiveIntegerField(verbose_name="M Processing Layer Id (Business Module - M Processing Layer Id)", null=False)
    m_processing_sub_layer_id = models.PositiveIntegerField(verbose_name="M Processing Sub Layer Id (Business Module - M Processing Sub Layer Id)", null=False)
    processing_layer_id = models.PositiveIntegerField(verbose_name="Processing Layer Id (Business Module - Processing Layer Id)", null=False)
    processing_layer_name = models.CharField(max_length=64, verbose_name="Processing Layer Name", null=True)
    ext_processing_status_1 = models.CharField(max_length=64, verbose_name="Ext Processing Status 1", null=True)
    ext_processing_status_2 = models.CharField(max_length=64, verbose_name="Ext Processing Status 2", null=True)
    ext_processing_status_3 = models.CharField(max_length=64, verbose_name="Ext Processing Status 3", null=True)
    ext_processing_status_4 = models.CharField(max_length=64, verbose_name="Ext Processing Status 4", null=True)
    ext_processing_status_5 = models.CharField(max_length=64, verbose_name="Ext Processing Status 5", null=True)
    ext_match_type_1 = models.CharField(max_length=64, verbose_name="Ext Match Type 1", null=True)
    ext_match_type_2 = models.CharField(max_length=64, verbose_name="Ext Match Type 2", null=True)
    ext_match_type_3 = models.CharField(max_length=64, verbose_name="Ext Match Type 3", null=True)
    ext_match_type_4 = models.CharField(max_length=64, verbose_name="Ext Match Type 4", null=True)
    ext_match_type_5 = models.CharField(max_length=64, verbose_name="Ext Match Type 5", null=True)
    ext_reference_text_1 = models.TextField(verbose_name="Ext Reference Text 1", null=True)
    ext_reference_text_2 = models.TextField(verbose_name="Ext Reference Text 2", null=True)
    ext_reference_text_3 = models.TextField(verbose_name="Ext Reference Text 3", null=True)
    ext_reference_text_4 = models.TextField(verbose_name="Ext Reference Text 4", null=True)
    ext_reference_text_5 = models.TextField(verbose_name="Ext Reference Text 5", null=True)
    ext_reference_text_6 = models.TextField(verbose_name="Ext Reference Text 6", null=True)
    ext_reference_text_7 = models.TextField(verbose_name="Ext Reference Text 7", null=True)
    ext_reference_text_8 = models.TextField(verbose_name="Ext Reference Text 8", null=True)
    ext_reference_text_9 = models.TextField(verbose_name="Ext Reference Text 9", null=True)
    ext_reference_text_10 = models.TextField(verbose_name="Ext Reference Text 10", null=True)
    ext_reference_text_11 = models.TextField(verbose_name="Ext Reference Text 11", null=True)
    ext_reference_text_12 = models.TextField(verbose_name="Ext Reference Text 12", null=True)
    ext_reference_text_13 = models.TextField(verbose_name="Ext Reference Text 13", null=True)
    ext_reference_text_14 = models.TextField(verbose_name="Ext Reference Text 14", null=True)
    ext_reference_text_15 = models.TextField(verbose_name="Ext Reference Text 15", null=True)
    ext_reference_text_16 = models.TextField(verbose_name="Ext Reference Text 16", null=True)
    ext_reference_text_17 = models.TextField(verbose_name="Ext Reference Text 17", null=True)
    ext_reference_text_18 = models.TextField(verbose_name="Ext Reference Text 18", null=True)
    ext_reference_text_19 = models.TextField(verbose_name="Ext Reference Text 19", null=True)
    ext_reference_text_20 = models.TextField(verbose_name="Ext Reference Text 20", null=True)
    ext_reference_text_21 = models.TextField(verbose_name="Ext Reference Text 21", null=True)
    ext_reference_text_22 = models.TextField(verbose_name="Ext Reference Text 22", null=True)
    ext_reference_text_23 = models.TextField(verbose_name="Ext Reference Text 23", null=True)
    ext_reference_text_24 = models.TextField(verbose_name="Ext Reference Text 24", null=True)
    ext_reference_text_25 = models.TextField(verbose_name="Ext Reference Text 25", null=True)
    ext_extracted_text_1 = models.CharField(max_length=512, verbose_name="Ext Extracted Text 1", null=True)
    ext_extracted_text_2 = models.CharField(max_length=512, verbose_name="Ext Extracted Text 2", null=True)
    ext_extracted_text_3 = models.CharField(max_length=512, verbose_name="Ext Extracted Text 3", null=True)
    ext_extracted_text_4 = models.CharField(max_length=512, verbose_name="Ext Extracted Text 4", null=True)
    ext_extracted_text_5 = models.CharField(max_length=512, verbose_name="Ext Extracted Text 5", null=True)
    ext_extracted_text_6 = models.CharField(max_length=512, verbose_name="Ext Extracted Text 6", null=True)
    ext_extracted_text_7 = models.CharField(max_length=512, verbose_name="Ext Extracted Text 7", null=True)
    ext_extracted_text_8 = models.CharField(max_length=512, verbose_name="Ext Extracted Text 8", null=True)
    ext_extracted_text_9 = models.CharField(max_length=512, verbose_name="Ext Extracted Text 9", null=True)
    ext_extracted_text_10 = models.CharField(max_length=512, verbose_name="Ext Extracted Text 10", null=True)
    ext_reference_date_time_1 = models.DateTimeField(verbose_name="Ext Reference Date Time 1", null=True)
    ext_reference_date_time_2 = models.DateTimeField(verbose_name="Ext Reference Date Time 2", null=True)
    ext_reference_date_time_3 = models.DateTimeField(verbose_name="Ext Reference Date Time 3", null=True)
    ext_reference_date_time_4 = models.DateTimeField(verbose_name="Ext Reference Date Time 4", null=True)
    ext_reference_date_time_5 = models.DateTimeField(verbose_name="Ext Reference Date Time 5", null=True)
    ext_debit_amount = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Ext Debit Amount", null=True)
    ext_credit_amount = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Ext Credit Amount", null=True)
    ext_amount_1 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Ext Amount 1", null=True)
    ext_amount_2 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Ext Amount 2", null=True)
    ext_amount_3 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Ext Amount 3", null=True)
    ext_amount_4 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Ext Amount 4", null=True)
    ext_amount_5 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Ext Amount 5", null=True)
    ext_amount_6 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Ext Amount 6", null=True)
    ext_amount_7 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Ext Amount 7", null=True)
    ext_amount_8 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Ext Amount 8", null=True)
    ext_amount_9 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Ext Amount 9", null=True)
    ext_amount_10 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Ext Amount 10", null=True)
    ext_generated_num_1 = models.PositiveIntegerField(verbose_name="Ext Generated Number 1", null=True)
    ext_generated_num_2 = models.PositiveIntegerField(verbose_name="Ext Generated Number 2", null=True)
    ext_generated_num_3 = models.PositiveIntegerField(verbose_name="Ext Generated Number 3", null=True)
    ext_generated_num_4 = models.PositiveIntegerField(verbose_name="Ext Generated Number 4", null=True)
    ext_generated_num_5 = models.PositiveIntegerField(verbose_name="Ext Generated Number 5", null=True)
    ext_generated_num_6 = models.PositiveIntegerField(verbose_name="Ext Generated Number 6", null=True)
    ext_generated_num_7 = models.PositiveIntegerField(verbose_name="Ext Generated Number 7", null=True)
    ext_generated_num_8 = models.PositiveIntegerField(verbose_name="Ext Generated Number 8", null=True)
    ext_generated_num_9 = models.PositiveIntegerField(verbose_name="Ext Generated Number 9", null=True)
    ext_generated_num_10 = models.PositiveIntegerField(verbose_name="Ext Generated Number 10", null=True)
    is_active = models.BooleanField(default=True, verbose_name="Active ?")
    created_by = models.PositiveSmallIntegerField(verbose_name="User Id", null=True)
    created_date = models.DateTimeField(auto_now_add = True, verbose_name="Created Date")
    modified_by = models.PositiveSmallIntegerField(verbose_name="User Id", null=True)
    modified_date = models.DateTimeField(auto_now = True, verbose_name="Modified Date")

class UTRDetails(models.Model):
    class Meta:
        db_table = "utr_details"

    id = models.AutoField(primary_key=True)
    tenants_id = models.PositiveIntegerField(verbose_name="Tenants Id (Business Module - Tenant Id)", null=False)
    groups_id = models.PositiveIntegerField(verbose_name="Groups Id (Business Module - Groups Id)", null=False)
    entities_id = models.PositiveIntegerField(verbose_name="Entities Id (Business Module - Entities Id)", null=False)
    file_id = models.PositiveIntegerField(verbose_name="File Id", null=False)
    job_execution_id = models.PositiveIntegerField(verbose_name="Job Execution Id", null=False)
    m_processing_layer_id = models.PositiveIntegerField(verbose_name="M Processing Layer Id (Business Module - M Processing Layer Id)", null=False)
    m_processing_sub_layer_id = models.PositiveIntegerField(verbose_name="M Processing Sub Layer Id (Business Module - M Processing Sub Layer Id)", null=False)
    processing_layer_id = models.PositiveIntegerField(verbose_name="Processing Layer Id (Business Module - Processing Layer Id)", null=False)
    processing_layer_name = models.CharField(max_length=64, verbose_name="Processing Layer Name", null=True)
    utr_processing_status_1 = models.CharField(max_length=64, verbose_name="UTR Processing Status 1", null=True)
    utr_processing_status_2 = models.CharField(max_length=64, verbose_name="UTR Processing Status 2", null=True)
    utr_match_type_1 = models.CharField(max_length=64, verbose_name="UTR Match Type 1", null=True)
    utr_match_type_2 = models.CharField(max_length=64, verbose_name="UTR Match Type 2", null=True)
    utr_reference_text_1 = models.TextField(verbose_name="UTR Reference Text 1", null=True)
    utr_reference_text_2 = models.TextField(verbose_name="UTR Reference Text 2", null=True)
    utr_reference_text_3 = models.TextField(verbose_name="UTR Reference Text 3", null=True)
    utr_reference_text_4 = models.TextField(verbose_name="UTR Reference Text 4", null=True)
    utr_reference_text_5 = models.TextField(verbose_name="UTR Reference Text 5", null=True)
    utr_reference_text_6 = models.TextField(verbose_name="UTR Reference Text 6", null=True)
    utr_reference_text_7 = models.TextField(verbose_name="UTR Reference Text 7", null=True)
    utr_reference_text_8 = models.TextField(verbose_name="UTR Reference Text 8", null=True)
    utr_reference_text_9 = models.TextField(verbose_name="UTR Reference Text 9", null=True)
    utr_reference_text_10 = models.TextField(verbose_name="UTR Reference Text 10", null=True)
    utr_reference_text_11 = models.TextField(verbose_name="UTR Reference Text 11", null=True)
    utr_reference_text_12 = models.TextField(verbose_name="UTR Reference Text 12", null=True)
    utr_reference_text_13 = models.TextField(verbose_name="UTR Reference Text 13", null=True)
    utr_reference_text_14 = models.TextField(verbose_name="UTR Reference Text 14", null=True)
    utr_reference_text_15 = models.TextField(verbose_name="UTR Reference Text 15", null=True)
    utr_reference_text_16 = models.TextField(verbose_name="UTR Reference Text 16", null=True)
    utr_reference_text_17 = models.TextField(verbose_name="UTR Reference Text 17", null=True)
    utr_reference_text_18 = models.TextField(verbose_name="UTR Reference Text 18", null=True)
    utr_reference_text_19 = models.TextField(verbose_name="UTR Reference Text 19", null=True)
    utr_reference_text_20 = models.TextField(verbose_name="UTR Reference Text 20", null=True)
    utr_reference_text_21 = models.TextField(verbose_name="UTR Reference Text 21", null=True)
    utr_reference_text_22 = models.TextField(verbose_name="UTR Reference Text 22", null=True)
    utr_reference_text_23 = models.TextField(verbose_name="UTR Reference Text 23", null=True)
    utr_reference_text_24 = models.TextField(verbose_name="UTR Reference Text 24", null=True)
    utr_reference_text_25 = models.TextField(verbose_name="UTR Reference Text 25", null=True)
    utr_reference_date_time_1 = models.DateTimeField(verbose_name="UTR Reference Date Time 1", null=True)
    utr_reference_date_time_2 = models.DateTimeField(verbose_name="UTR Reference Date Time 2", null=True)
    utr_reference_date_time_3 = models.DateTimeField(verbose_name="UTR Reference Date Time 3", null=True)
    utr_reference_date_time_4 = models.DateTimeField(verbose_name="UTR Reference Date Time 4", null=True)
    utr_reference_date_time_5 = models.DateTimeField(verbose_name="UTR Reference Date Time 5", null=True)
    utr_amount_1 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="UTR Amount 1", null=True)
    utr_amount_2 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="UTR Amount 2", null=True)
    utr_generated_num_1 = models.PositiveIntegerField(verbose_name="UTR Generated Number 1", null=True)
    utr_generated_num_2 = models.PositiveIntegerField(verbose_name="UTR Generated Number 2", null=True)
    utr_generated_num_3 = models.PositiveIntegerField(verbose_name="UTR Generated Number 3", null=True)
    utr_generated_num_4 = models.PositiveIntegerField(verbose_name="UTR Generated Number 4", null=True)
    utr_generated_num_5 = models.PositiveIntegerField(verbose_name="UTR Generated Number 5", null=True)
    is_active = models.BooleanField(default=True, verbose_name="Active ?")
    created_by = models.PositiveSmallIntegerField(verbose_name="User Id", null=True)
    created_date = models.DateTimeField(auto_now_add = True, verbose_name="Created Date")
    modified_by = models.PositiveSmallIntegerField(verbose_name="User Id", null=True)
    modified_date = models.DateTimeField(auto_now = True, verbose_name="Modified Date")

class MasterClientDetails(models.Model):
    class Meta:
        db_table = "m_client_details"

    id = models.AutoField(primary_key = True)
    tenants_id = models.PositiveIntegerField(verbose_name="Tenants Id (Business Module - Tenant Id)")
    groups_id = models.PositiveIntegerField(verbose_name="Groups Id (Business Module - Groups Id)")
    entities_id = models.PositiveIntegerField(verbose_name="Entities Id (Business Module - Entities Id)")
    client_id = models.CharField(max_length=64, verbose_name="Client ID", null=False)
    client_name = models.CharField(max_length=512, verbose_name="Client Name", null=True)
    email_address = models.EmailField(max_length=512, verbose_name="Email Address", null=True)
    frequency = models.CharField(max_length=64, verbose_name="Frequency", null=True)
    last_send_on = models.CharField(max_length=64, verbose_name="Last Sent On", null=True, blank=True)
    is_active = models.BooleanField(default=True, verbose_name="Active ?")
    created_by = models.PositiveSmallIntegerField(verbose_name="User Id", null=True)
    created_date = models.DateTimeField(auto_now_add=True, verbose_name="Created Date")
    modified_by = models.PositiveSmallIntegerField(verbose_name="User Id", null=True)
    modified_date = models.DateTimeField(auto_now=True, verbose_name="Modified Date")

class RecoSettings(models.Model):
    class Meta:
        db_table = "reco_settings"

    id = models.AutoField(primary_key=True)
    tenants_id = models.PositiveIntegerField(verbose_name="Tenants Id (Business Module - Tenant Id)", null=False)
    groups_id = models.PositiveIntegerField(verbose_name="Groups Id (Business Module - Groups Id)", null=False)
    entities_id = models.PositiveIntegerField(verbose_name="Entities Id (Business Module - Entities Id)", null=False)
    m_processing_layer_id = models.PositiveIntegerField(verbose_name="M Processing Layer Id (Business Module - M Processing Layer Id)", null=False)
    m_processing_sub_layer_id = models.PositiveIntegerField(verbose_name="M Processing Sub Layer Id (Business Module - M Processing Sub Layer Id)", null=False)
    processing_layer_id = models.PositiveIntegerField(verbose_name="Processing Layer Id (Business Module - Processing Layer Id)", null=False)
    setting_key = models.CharField(max_length = 64, verbose_name="Setting Key", null=True)
    setting_value = models.TextField(verbose_name="Setting Value", null=True)
    is_active = models.BooleanField(default=True, verbose_name="Active ?")
    created_by = models.PositiveSmallIntegerField(verbose_name="User Id", null=True)
    created_date = models.DateTimeField(auto_now_add=True, verbose_name="Created Date")
    modified_by = models.PositiveSmallIntegerField(verbose_name="User Id", null=True)
    modified_date = models.DateTimeField(auto_now=True, verbose_name="Modified Date")

class CommonSettings(models.Model):
    class Meta:
        db_table = "common_settings"

    id = models.AutoField(primary_key=True)
    tenants_id = models.PositiveIntegerField(verbose_name="Tenants Id (Business Module - Tenant Id)", null=False)
    groups_id = models.PositiveIntegerField(verbose_name="Groups Id (Business Module - Groups Id)", null=False)
    entities_id = models.PositiveIntegerField(verbose_name="Entities Id (Business Module - Entities Id)", null=False)
    m_processing_layer_id = models.PositiveIntegerField(verbose_name="M Processing Layer Id (Business Module - M Processing Layer Id)", null=False)
    m_processing_sub_layer_id = models.PositiveIntegerField(verbose_name="M Processing Sub Layer Id (Business Module - M Processing Sub Layer Id)", null=False)
    setting_key = models.CharField(max_length=64, verbose_name="Setting Key", null=True)
    setting_value = models.TextField(verbose_name="Setting Value", null=True)
    is_active = models.BooleanField(default=True, verbose_name="Active ?")
    created_by = models.PositiveSmallIntegerField(verbose_name="User Id", null=True)
    created_date = models.DateTimeField(auto_now_add=True, verbose_name="Created Date")
    modified_by = models.PositiveSmallIntegerField(verbose_name="User Id", null=True)
    modified_date = models.DateTimeField(auto_now=True, verbose_name="Modified Date")

class RecoExecutionLog(models.Model):
    class Meta:
        db_table = "reco_execution_log"

    id = models.AutoField(primary_key=True)
    file_uploads_id = models.PositiveIntegerField(verbose_name="File Uploads Id", null=True)
    procedure_name = models.CharField(max_length=64, verbose_name="Procedure Name", null=True)
    start_time = models.DateTimeField(verbose_name="Start Time", null=True)
    end_time = models.DateTimeField(verbose_name="End Time", null=True)
    error_message = models.TextField(verbose_name="Error Message", null=True)
    error_state = models.TextField(verbose_name="Error State", null=True)
    comments = models.TextField(verbose_name="Comments", null=True)