# Generated by Django 3.1.7 on 2022-01-01 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('actions', models.AutoField(primary_key=True, serialize=False)),
                ('source_id', models.PositiveIntegerField(null=True, verbose_name='Source Id (Sources - Auto Field)')),
                ('action_code', models.CharField(max_length=64, verbose_name='Action Code')),
                ('action_name', models.TextField(verbose_name='Action Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
            ],
            options={
                'db_table': 'actions',
            },
        ),
        migrations.CreateModel(
            name='JobExecutions',
            fields=[
                ('job_execution_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_id', models.PositiveIntegerField(verbose_name='File Id (Process Module - File Uploads - File Id (Auto Field)')),
                ('m_processing_layer_id', models.PositiveIntegerField(verbose_name='M Processing Layer Id - Sources - M Processing Layer Id (Auto Field)')),
                ('m_processing_sub_layer_id', models.PositiveIntegerField(verbose_name='M Processing Sub Layer Id - Sources - M Processing Sub Layer Id (Auto Field)')),
                ('processing_layer_id', models.PositiveIntegerField(verbose_name='Processing Layer Id - Sources - Processing Layer Id (Auto Field)')),
                ('execution_status', models.CharField(max_length=256, verbose_name='Execution Status')),
                ('start_dt', models.DateTimeField(null=True, verbose_name='Start Date Time')),
                ('end_dt', models.DateTimeField(null=True, verbose_name='End Date Time')),
                ('duration', models.PositiveIntegerField(null=True, verbose_name='Task Duration')),
                ('executed_by', models.PositiveIntegerField(null=True, verbose_name='Executed By')),
                ('updated_by', models.PositiveIntegerField(null=True, verbose_name='Updated By')),
            ],
            options={
                'db_table': 'job_executions',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('jobs_id', models.AutoField(primary_key=True, serialize=False)),
                ('tenants_id', models.PositiveIntegerField(verbose_name='Tenants Id (Business Module - Tenant Id)')),
                ('groups_id', models.PositiveIntegerField(verbose_name='Groups Id (Business Module - Groups Id)')),
                ('entities_id', models.PositiveIntegerField(verbose_name='Entities Id (Business Module - Entities Id)')),
                ('m_processing_layer_id', models.PositiveIntegerField(verbose_name='M Processing Layer Id (Source Module - MProcessingLayerId)')),
                ('m_processing_sub_layer_id', models.PositiveIntegerField(verbose_name='M Processing Sub Layer Id (Source Module - MProcessingSubLayerId)')),
                ('processing_layer_id', models.PositiveIntegerField(verbose_name='Processing Layer Id (Source Module - ProcessingLayerId)')),
                ('job_code', models.CharField(max_length=64, verbose_name='Job Code')),
                ('job_name', models.TextField(verbose_name='Job Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('tasks_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_code', models.CharField(max_length=64, verbose_name='Task Code')),
                ('task_name', models.TextField(verbose_name='Task Name')),
                ('is_system_task', models.BooleanField(default=True, verbose_name='System Task?')),
                ('is_user_task', models.BooleanField(default=True, verbose_name='User Task?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.jobs', verbose_name='Jobs (JobId - Auto Field)')),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='ExecutionSequence',
            fields=[
                ('exc_seq_id', models.AutoField(primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField(verbose_name='Sequence')),
                ('sub_sequence', models.PositiveIntegerField(verbose_name='Sub Sequence')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('actions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.actions', verbose_name='Actions (ActionsId - Auto Field)')),
                ('jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.jobs', verbose_name='Jobs (JobId - Auto Field)')),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.tasks', verbose_name='Tasks (TaskId - Auto Field)')),
            ],
            options={
                'db_table': 'execution_sequence',
            },
        ),
        migrations.AddField(
            model_name='actions',
            name='jobs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.jobs', verbose_name='Jobs (JobId - Auto Field)'),
        ),
        migrations.AddField(
            model_name='actions',
            name='tasks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.tasks', verbose_name='Tasks (TaskId - Auto Field)'),
        ),
    ]
