# Generated by Django 3.1.7 on 2022-01-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobexecutions',
            name='file_id',
        ),
        migrations.AddField(
            model_name='jobexecutions',
            name='file_ids',
            field=models.JSONField(default={}, verbose_name='File Id (Process Module - File Uploads - File Id (Auto Field)'),
            preserve_default=False,
        ),
    ]
