# Generated by Django 3.1.7 on 2022-01-02 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20220103_0107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actions',
            old_name='actions',
            new_name='actions_id',
        ),
    ]
