# Generated by Django 3.1.7 on 2022-01-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20220103_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobexecutions',
            name='file_ids',
            field=models.JSONField(verbose_name='File Id (Process Module - File Uploads - File Id (Auto Field)'),
        ),
    ]
