# Generated by Django 3.1.7 on 2021-12-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploads',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenants_id', models.PositiveIntegerField(verbose_name='Tenants Id (Business Module - Tenant Id)')),
                ('groups_id', models.PositiveIntegerField(verbose_name='Groups Id (Business Module - Groups Id)')),
                ('entities_id', models.PositiveIntegerField(verbose_name='Entities Id (Business Module - Entities Id)')),
                ('m_source_id', models.PositiveIntegerField(verbose_name='Source Id (Business Module - Source Id)')),
                ('m_processing_layer_id', models.PositiveIntegerField(verbose_name='M Processing Layer Id (Business Module - M Processing Layer Id)')),
                ('m_processing_sub_layer_id', models.PositiveIntegerField(verbose_name='M Processing Sub Layer Id (Business Module - M Processing Sub Layer Id)')),
                ('processing_layer_id', models.PositiveIntegerField(verbose_name='Processing Layer Id (Business Module - Processing Layer Id)')),
                ('processing_layer_name', models.CharField(max_length=64, null=True, verbose_name='Processing Layer Name')),
                ('source_type', models.CharField(max_length=128, null=True, verbose_name='File Name')),
                ('extraction_type', models.CharField(max_length=128, null=True, verbose_name='File Name')),
                ('file_name', models.CharField(max_length=128, null=True, verbose_name='File Name')),
                ('file_size_bytes', models.PositiveIntegerField(null=True, verbose_name='File Size Bytes')),
                ('file_path', models.CharField(max_length=512, null=True, verbose_name='File Path')),
                ('status', models.CharField(max_length=32, null=True, verbose_name='Status')),
                ('comments', models.TextField(null=True, verbose_name='Comments')),
                ('file_row_count', models.PositiveIntegerField(null=True, verbose_name='File Row Count (Business Module - File Row Count)')),
                ('is_processed', models.BooleanField(default=True, verbose_name='Active ?')),
                ('is_processing', models.PositiveIntegerField(verbose_name='Is Processing?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
            ],
            options={
                'db_table': 'file_uploads',
            },
        ),
    ]
