# Generated by Django 3.1.7 on 2022-01-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UTRDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenants_id', models.PositiveIntegerField(verbose_name='Tenants Id (Business Module - Tenant Id)')),
                ('groups_id', models.PositiveIntegerField(verbose_name='Groups Id (Business Module - Groups Id)')),
                ('entities_id', models.PositiveIntegerField(verbose_name='Entities Id (Business Module - Entities Id)')),
                ('file_id', models.PositiveIntegerField(verbose_name='File Id')),
                ('job_execution_id', models.PositiveIntegerField(verbose_name='Job Execution Id')),
                ('m_processing_layer_id', models.PositiveIntegerField(verbose_name='M Processing Layer Id (Business Module - M Processing Layer Id)')),
                ('m_processing_sub_layer_id', models.PositiveIntegerField(verbose_name='M Processing Sub Layer Id (Business Module - M Processing Sub Layer Id)')),
                ('processing_layer_id', models.PositiveIntegerField(verbose_name='Processing Layer Id (Business Module - Processing Layer Id)')),
                ('processing_layer_name', models.CharField(max_length=64, null=True, verbose_name='Processing Layer Name')),
                ('utr_processing_status_1', models.CharField(max_length=64, null=True, verbose_name='UTR Processing Status 1')),
                ('utr_processing_status_2', models.CharField(max_length=64, null=True, verbose_name='UTR Processing Status 2')),
                ('utr_match_type_1', models.CharField(max_length=64, null=True, verbose_name='UTR Match Type 1')),
                ('utr_match_type_2', models.CharField(max_length=64, null=True, verbose_name='UTR Match Type 2')),
                ('utr_reference_text_1', models.TextField(null=True, verbose_name='UTR Reference Text 1')),
                ('utr_reference_text_2', models.TextField(null=True, verbose_name='UTR Reference Text 2')),
                ('utr_reference_text_3', models.TextField(null=True, verbose_name='UTR Reference Text 3')),
                ('utr_reference_text_4', models.TextField(null=True, verbose_name='UTR Reference Text 4')),
                ('utr_reference_text_5', models.TextField(null=True, verbose_name='UTR Reference Text 5')),
                ('utr_reference_text_6', models.TextField(null=True, verbose_name='UTR Reference Text 6')),
                ('utr_reference_text_7', models.TextField(null=True, verbose_name='UTR Reference Text 7')),
                ('utr_reference_text_8', models.TextField(null=True, verbose_name='UTR Reference Text 8')),
                ('utr_reference_text_9', models.TextField(null=True, verbose_name='UTR Reference Text 9')),
                ('utr_reference_text_10', models.TextField(null=True, verbose_name='UTR Reference Text 10')),
                ('utr_reference_text_11', models.TextField(null=True, verbose_name='UTR Reference Text 11')),
                ('utr_reference_text_12', models.TextField(null=True, verbose_name='UTR Reference Text 12')),
                ('utr_reference_text_13', models.TextField(null=True, verbose_name='UTR Reference Text 13')),
                ('utr_reference_text_14', models.TextField(null=True, verbose_name='UTR Reference Text 14')),
                ('utr_reference_text_15', models.TextField(null=True, verbose_name='UTR Reference Text 15')),
                ('utr_reference_text_16', models.TextField(null=True, verbose_name='UTR Reference Text 16')),
                ('utr_reference_text_17', models.TextField(null=True, verbose_name='UTR Reference Text 17')),
                ('utr_reference_text_18', models.TextField(null=True, verbose_name='UTR Reference Text 18')),
                ('utr_reference_text_19', models.TextField(null=True, verbose_name='UTR Reference Text 19')),
                ('utr_reference_text_20', models.TextField(null=True, verbose_name='UTR Reference Text 20')),
                ('utr_reference_text_21', models.TextField(null=True, verbose_name='UTR Reference Text 21')),
                ('utr_reference_text_22', models.TextField(null=True, verbose_name='UTR Reference Text 22')),
                ('utr_reference_text_23', models.TextField(null=True, verbose_name='UTR Reference Text 23')),
                ('utr_reference_text_24', models.TextField(null=True, verbose_name='UTR Reference Text 24')),
                ('utr_reference_text_25', models.TextField(null=True, verbose_name='UTR Reference Text 25')),
                ('utr_reference_date_time_1', models.DateTimeField(null=True, verbose_name='UTR Reference Date Time 1')),
                ('utr_reference_date_time_2', models.DateTimeField(null=True, verbose_name='UTR Reference Date Time 2')),
                ('utr_reference_date_time_3', models.DateTimeField(null=True, verbose_name='UTR Reference Date Time 3')),
                ('utr_reference_date_time_4', models.DateTimeField(null=True, verbose_name='UTR Reference Date Time 4')),
                ('utr_reference_date_time_5', models.DateTimeField(null=True, verbose_name='UTR Reference Date Time 5')),
                ('utr_amount_1', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='UTR Amount 1')),
                ('utr_amount_2', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='UTR Amount 2')),
                ('utr_generated_num_1', models.PositiveIntegerField(null=True, verbose_name='UTR Generated Number 1')),
                ('utr_generated_num_2', models.PositiveIntegerField(null=True, verbose_name='UTR Generated Number 2')),
                ('utr_generated_num_3', models.PositiveIntegerField(null=True, verbose_name='UTR Generated Number 3')),
                ('utr_generated_num_4', models.PositiveIntegerField(null=True, verbose_name='UTR Generated Number 4')),
                ('utr_generated_num_5', models.PositiveIntegerField(null=True, verbose_name='UTR Generated Number 5')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
            ],
            options={
                'db_table': 'utr_details',
            },
        ),
    ]
