# Generated by Django 3.1.7 on 2022-01-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcs', '0002_utrdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenants_id', models.PositiveIntegerField(verbose_name='Tenants Id (Business Module - Tenant Id)')),
                ('groups_id', models.PositiveIntegerField(verbose_name='Groups Id (Business Module - Groups Id)')),
                ('entities_id', models.PositiveIntegerField(verbose_name='Entities Id (Business Module - Entities Id)')),
                ('m_processing_layer_id', models.PositiveIntegerField(verbose_name='M Processing Layer Id (Business Module - M Processing Layer Id)')),
                ('m_processing_sub_layer_id', models.PositiveIntegerField(verbose_name='M Processing Sub Layer Id (Business Module - M Processing Sub Layer Id)')),
                ('processing_layer_id', models.PositiveIntegerField(verbose_name='Processing Layer Id (Business Module - Processing Layer Id)')),
                ('setting_key', models.CharField(max_length=64, null=True, verbose_name='Setting Key')),
                ('setting_value', models.TextField(null=True, verbose_name='Setting Value')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
            ],
            options={
                'db_table': 'reco_settings',
            },
        ),
    ]
