# Generated by Django 3.1.7 on 2022-01-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcs', '0003_externalrecords_internalrecords'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalrecords',
            name='ext_match_type_1',
            field=models.CharField(max_length=64, null=True, verbose_name='Ext Match Type 1'),
        ),
        migrations.AddField(
            model_name='externalrecords',
            name='ext_match_type_2',
            field=models.CharField(max_length=64, null=True, verbose_name='Ext Match Type 2'),
        ),
        migrations.AddField(
            model_name='externalrecords',
            name='ext_match_type_3',
            field=models.CharField(max_length=64, null=True, verbose_name='Ext Match Type 3'),
        ),
        migrations.AddField(
            model_name='externalrecords',
            name='ext_match_type_4',
            field=models.CharField(max_length=64, null=True, verbose_name='Ext Match Type 4'),
        ),
        migrations.AddField(
            model_name='externalrecords',
            name='ext_match_type_5',
            field=models.CharField(max_length=64, null=True, verbose_name='Ext Match Type 5'),
        ),
        migrations.AddField(
            model_name='externalrecords',
            name='ext_processing_status_1',
            field=models.CharField(max_length=64, null=True, verbose_name='Ext Processing Status 1'),
        ),
        migrations.AddField(
            model_name='externalrecords',
            name='ext_processing_status_2',
            field=models.CharField(max_length=64, null=True, verbose_name='Ext Processing Status 2'),
        ),
        migrations.AddField(
            model_name='externalrecords',
            name='ext_processing_status_3',
            field=models.CharField(max_length=64, null=True, verbose_name='Ext Processing Status 3'),
        ),
        migrations.AddField(
            model_name='externalrecords',
            name='ext_processing_status_4',
            field=models.CharField(max_length=64, null=True, verbose_name='Ext Processing Status 4'),
        ),
        migrations.AddField(
            model_name='externalrecords',
            name='ext_processing_status_5',
            field=models.CharField(max_length=64, null=True, verbose_name='Ext Processing Status 5'),
        ),
        migrations.AddField(
            model_name='externalrecords',
            name='file_id',
            field=models.PositiveIntegerField(default=1, verbose_name='File Id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='externalrecords',
            name='job_execution_id',
            field=models.PositiveIntegerField(default=1, verbose_name='Job Execution Id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='file_id',
            field=models.PositiveIntegerField(default=1, verbose_name='File Id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_match_type_1',
            field=models.CharField(max_length=64, null=True, verbose_name='Int Match Type 1'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_match_type_2',
            field=models.CharField(max_length=64, null=True, verbose_name='Int Match Type 2'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_match_type_3',
            field=models.CharField(max_length=64, null=True, verbose_name='Int Match Type 3'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_match_type_4',
            field=models.CharField(max_length=64, null=True, verbose_name='Int Match Type 4'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_match_type_5',
            field=models.CharField(max_length=64, null=True, verbose_name='Int Match Type 5'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_processing_status_1',
            field=models.CharField(max_length=64, null=True, verbose_name='Int Processing Status 1'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_processing_status_2',
            field=models.CharField(max_length=64, null=True, verbose_name='Int Processing Status 2'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_processing_status_3',
            field=models.CharField(max_length=64, null=True, verbose_name='Int Processing Status 3'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_processing_status_4',
            field=models.CharField(max_length=64, null=True, verbose_name='Int Processing Status 4'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_processing_status_5',
            field=models.CharField(max_length=64, null=True, verbose_name='Int Processing Status 5'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='job_execution_id',
            field=models.PositiveIntegerField(default=1, verbose_name='Job Execution Id'),
            preserve_default=False,
        ),
    ]
