# Generated by Django 3.1.7 on 2022-01-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcs', '0005_stagingexternalrecords_staginginternalrecords_stagingutrdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoExecutionLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_uploads_id', models.PositiveIntegerField(null=True, verbose_name='File Uploads Id')),
                ('procedure_name', models.CharField(max_length=64, null=True, verbose_name='Procedure Name')),
                ('start_time', models.DateTimeField(null=True, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(null=True, verbose_name='End Time')),
                ('error_message', models.TextField(null=True, verbose_name='Error Message')),
                ('error_state', models.TextField(null=True, verbose_name='Error State')),
                ('comments', models.TextField(null=True, verbose_name='Comments')),
            ],
            options={
                'db_table': 'reco_execution_log',
            },
        ),
    ]
