# Generated by Django 3.1.7 on 2022-01-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcs', '0006_recoexecutionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagingexternalrecords',
            name='ext_reference_date_time_1',
            field=models.TextField(null=True, verbose_name='Ext Reference Date Time 1'),
        ),
        migrations.AlterField(
            model_name='stagingexternalrecords',
            name='ext_reference_date_time_2',
            field=models.TextField(null=True, verbose_name='Ext Reference Date Time 2'),
        ),
        migrations.AlterField(
            model_name='stagingexternalrecords',
            name='ext_reference_date_time_3',
            field=models.TextField(null=True, verbose_name='Ext Reference Date Time 3'),
        ),
        migrations.AlterField(
            model_name='stagingexternalrecords',
            name='ext_reference_date_time_4',
            field=models.TextField(null=True, verbose_name='Ext Reference Date Time 4'),
        ),
        migrations.AlterField(
            model_name='stagingexternalrecords',
            name='ext_reference_date_time_5',
            field=models.TextField(null=True, verbose_name='Ext Reference Date Time 5'),
        ),
        migrations.AlterField(
            model_name='staginginternalrecords',
            name='int_reference_date_time_1',
            field=models.TextField(null=True, verbose_name='Int Reference Date Time 1'),
        ),
        migrations.AlterField(
            model_name='staginginternalrecords',
            name='int_reference_date_time_2',
            field=models.TextField(null=True, verbose_name='Int Reference Date Time 2'),
        ),
        migrations.AlterField(
            model_name='staginginternalrecords',
            name='int_reference_date_time_3',
            field=models.TextField(null=True, verbose_name='Int Reference Date Time 3'),
        ),
        migrations.AlterField(
            model_name='staginginternalrecords',
            name='int_reference_date_time_4',
            field=models.TextField(null=True, verbose_name='Int Reference Date Time 4'),
        ),
        migrations.AlterField(
            model_name='staginginternalrecords',
            name='int_reference_date_time_5',
            field=models.TextField(null=True, verbose_name='Int Reference Date Time 5'),
        ),
    ]
