# Generated by Django 3.1.7 on 2022-01-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcs', '0007_auto_20220125_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterclientdetails',
            name='email_address',
            field=models.EmailField(max_length=512, null=True, verbose_name='Email Address'),
        ),
    ]
