# Generated by Django 3.1.7 on 2022-01-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcs', '0008_masterclientdetails_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterclientdetails',
            name='frequency',
            field=models.CharField(max_length=64, null=True, verbose_name='Frequency'),
        ),
    ]
