# Generated by Django 3.1.7 on 2022-01-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcs', '0010_masterclientdetails_last_send_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterclientdetails',
            name='last_send_on',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Last Sent On'),
        ),
    ]
