# Generated by Django 3.1.7 on 2022-02-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcs', '0011_auto_20220131_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploads',
            name='file_upload_type',
            field=models.CharField(default=1, max_length=64, verbose_name='File Upload Type'),
            preserve_default=False,
        ),
    ]
