# Generated by Django 3.1.7 on 2022-02-03 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alcs', '0013_auto_20220203_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileuploads',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='fileuploads',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified Date'),
        ),
    ]
