# Generated by Django 3.1.7 on 2022-02-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcs', '0014_auto_20220203_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalrecords',
            name='int_extracted_text_11',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 11'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_extracted_text_12',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 12'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_extracted_text_13',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 13'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_extracted_text_14',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 14'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_extracted_text_15',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 15'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_extracted_text_16',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 16'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_extracted_text_17',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 17'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_extracted_text_18',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 18'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_extracted_text_19',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 19'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_extracted_text_20',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 20'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_extracted_text_21',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 21'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_extracted_text_22',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 22'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_extracted_text_23',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 23'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_extracted_text_24',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 24'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_extracted_text_25',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 25'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_extracted_text_26',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 26'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_extracted_text_27',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 27'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_extracted_text_28',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 28'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_extracted_text_29',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 29'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_extracted_text_30',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 30'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_extracted_text_31',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 31'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_extracted_text_32',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 32'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_extracted_text_33',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 33'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_extracted_text_34',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 34'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_extracted_text_35',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 35'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_extracted_text_36',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 36'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_extracted_text_37',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 37'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_extracted_text_38',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 38'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_extracted_text_39',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 39'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_extracted_text_40',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 40'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_extracted_text_41',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 41'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_extracted_text_42',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 42'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_extracted_text_43',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 43'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_extracted_text_44',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 44'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_extracted_text_45',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 45'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_extracted_text_46',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 46'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_extracted_text_47',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 47'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_extracted_text_48',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 48'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_extracted_text_49',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 49'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_extracted_text_50',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 50'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_reference_text_26',
            field=models.TextField(null=True, verbose_name='Int Reference Text 26'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_reference_text_27',
            field=models.TextField(null=True, verbose_name='Int Reference Text 27'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_reference_text_28',
            field=models.TextField(null=True, verbose_name='Int Reference Text 28'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_reference_text_29',
            field=models.TextField(null=True, verbose_name='Int Reference Text 29'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_reference_text_30',
            field=models.TextField(null=True, verbose_name='Int Reference Text 30'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_reference_text_31',
            field=models.TextField(null=True, verbose_name='Int Reference Text 31'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_reference_text_32',
            field=models.TextField(null=True, verbose_name='Int Reference Text 32'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_reference_text_33',
            field=models.TextField(null=True, verbose_name='Int Reference Text 33'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_reference_text_34',
            field=models.TextField(null=True, verbose_name='Int Reference Text 34'),
        ),
        migrations.AddField(
            model_name='internalrecords',
            name='int_reference_text_35',
            field=models.TextField(null=True, verbose_name='Int Reference Text 35'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_extracted_text_11',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 11'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_extracted_text_12',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 12'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_extracted_text_13',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 13'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_extracted_text_14',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 14'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_extracted_text_15',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 15'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_extracted_text_16',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 16'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_extracted_text_17',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 17'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_extracted_text_18',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 18'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_extracted_text_19',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 19'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_extracted_text_20',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 20'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_extracted_text_21',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 21'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_extracted_text_22',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 22'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_extracted_text_23',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 23'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_extracted_text_24',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 24'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_extracted_text_25',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 25'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_extracted_text_26',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 26'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_extracted_text_27',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 27'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_extracted_text_28',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 28'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_extracted_text_29',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 29'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_extracted_text_30',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 30'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_extracted_text_31',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 31'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_extracted_text_32',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 32'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_extracted_text_33',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 33'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_extracted_text_34',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 34'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_extracted_text_35',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 35'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_extracted_text_36',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 36'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_extracted_text_37',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 37'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_extracted_text_38',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 38'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_extracted_text_39',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 39'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_extracted_text_40',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 40'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_extracted_text_41',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 41'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_extracted_text_42',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 42'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_extracted_text_43',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 43'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_extracted_text_44',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 44'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_extracted_text_45',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 45'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_extracted_text_46',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 46'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_extracted_text_47',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 47'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_extracted_text_48',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 48'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_extracted_text_49',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 49'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_extracted_text_50',
            field=models.TextField(null=True, verbose_name='Int Extracted Text 50'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_reference_text_26',
            field=models.TextField(null=True, verbose_name='Int Reference Text 26'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_reference_text_27',
            field=models.TextField(null=True, verbose_name='Int Reference Text 27'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_reference_text_28',
            field=models.TextField(null=True, verbose_name='Int Reference Text 28'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_reference_text_29',
            field=models.TextField(null=True, verbose_name='Int Reference Text 29'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_reference_text_30',
            field=models.TextField(null=True, verbose_name='Int Reference Text 30'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_reference_text_31',
            field=models.TextField(null=True, verbose_name='Int Reference Text 31'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_reference_text_32',
            field=models.TextField(null=True, verbose_name='Int Reference Text 32'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_reference_text_33',
            field=models.TextField(null=True, verbose_name='Int Reference Text 33'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_reference_text_34',
            field=models.TextField(null=True, verbose_name='Int Reference Text 34'),
        ),
        migrations.AddField(
            model_name='staginginternalrecords',
            name='int_reference_text_35',
            field=models.TextField(null=True, verbose_name='Int Reference Text 35'),
        ),
    ]
