# Generated by Django 3.1.7 on 2022-07-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankRecon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosingBalancesBank',
            fields=[
                ('closing_balances_bank_id', models.AutoField(primary_key=True, serialize=False)),
                ('tenants_id', models.PositiveIntegerField(verbose_name='Tenants Id (Business Module - Tenant Id)')),
                ('groups_id', models.PositiveIntegerField(verbose_name='Groups Id (Business Module - Groups Id)')),
                ('entities_id', models.PositiveIntegerField(verbose_name='Entities Id (Business Module - Entities Id)')),
                ('m_processing_layer_id', models.PositiveIntegerField(null=True, verbose_name='M Processing Layer Id')),
                ('m_processing_sub_layer_id', models.PositiveIntegerField(null=True, verbose_name='M Processing Sub Layer Id')),
                ('processing_layer_id', models.PositiveIntegerField(null=True, verbose_name='Processing Layer Id')),
                ('bank_closing_month', models.CharField(max_length=32, null=True, verbose_name='Bank Closing Month')),
                ('bank_closing_year', models.CharField(max_length=6, null=True, verbose_name='Bank Closing Year')),
                ('bank_closing_date', models.CharField(max_length=32, null=True, verbose_name='Date')),
                ('bank_closing_balance', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Bank Closing Balance')),
                ('approved_by', models.PositiveIntegerField(null=True, verbose_name='Approved By')),
                ('approved_date', models.CharField(max_length=64, null=True, verbose_name='Approved Date')),
            ],
            options={
                'db_table': 'closing_balances_bank',
            },
        ),
        migrations.CreateModel(
            name='ClosingBalancesGL',
            fields=[
                ('closing_balances_gl_id', models.AutoField(primary_key=True, serialize=False)),
                ('tenants_id', models.PositiveIntegerField(verbose_name='Tenants Id (Business Module - Tenant Id)')),
                ('groups_id', models.PositiveIntegerField(verbose_name='Groups Id (Business Module - Groups Id)')),
                ('entities_id', models.PositiveIntegerField(verbose_name='Entities Id (Business Module - Entities Id)')),
                ('m_processing_layer_id', models.PositiveIntegerField(null=True, verbose_name='M Processing Layer Id')),
                ('m_processing_sub_layer_id', models.PositiveIntegerField(null=True, verbose_name='M Processing Sub Layer Id')),
                ('processing_layer_id', models.PositiveIntegerField(null=True, verbose_name='Processing Layer Id')),
                ('gl_closing_month', models.CharField(max_length=32, null=True, verbose_name='GL Closing Month')),
                ('gl_closing_year', models.CharField(max_length=6, null=True, verbose_name='GL Closing Year')),
                ('gl_closing_date', models.CharField(max_length=32, null=True, verbose_name='Date')),
                ('gl_closing_balance', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='GL Closing Balance')),
                ('approved_by', models.PositiveIntegerField(null=True, verbose_name='Approved By')),
                ('approved_date', models.CharField(max_length=64, null=True, verbose_name='Approved Date')),
            ],
            options={
                'db_table': 'closing_balances_gl',
            },
        ),
        migrations.CreateModel(
            name='DailyBalancesBank',
            fields=[
                ('daily_balances_bank_id', models.AutoField(primary_key=True, serialize=False)),
                ('tenants_id', models.PositiveIntegerField(verbose_name='Tenants Id (Business Module - Tenant Id)')),
                ('groups_id', models.PositiveIntegerField(verbose_name='Groups Id (Business Module - Groups Id)')),
                ('entities_id', models.PositiveIntegerField(verbose_name='Entities Id (Business Module - Entities Id)')),
                ('m_processing_layer_id', models.PositiveIntegerField(null=True, verbose_name='M Processing Layer Id')),
                ('m_processing_sub_layer_id', models.PositiveIntegerField(null=True, verbose_name='M Processing Sub Layer Id')),
                ('processing_layer_id', models.PositiveIntegerField(null=True, verbose_name='Processing Layer Id')),
                ('date', models.CharField(max_length=32, null=True, verbose_name='Date')),
                ('total_debits_bank', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Total Debits Bank')),
                ('total_credits_bank', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Total Credits Bank')),
                ('bank_opening_balance', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Bank Opening Balance')),
                ('bank_closing_balance', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Bank Closing Balance')),
                ('approved_by', models.PositiveIntegerField(null=True, verbose_name='Approved By')),
                ('approved_date', models.CharField(max_length=64, null=True, verbose_name='Approved Date')),
            ],
            options={
                'db_table': 'daily_balances_bank',
            },
        ),
        migrations.CreateModel(
            name='DailyBalancesGL',
            fields=[
                ('daily_balances_gl_id', models.AutoField(primary_key=True, serialize=False)),
                ('tenants_id', models.PositiveIntegerField(verbose_name='Tenants Id (Business Module - Tenant Id)')),
                ('groups_id', models.PositiveIntegerField(verbose_name='Groups Id (Business Module - Groups Id)')),
                ('entities_id', models.PositiveIntegerField(verbose_name='Entities Id (Business Module - Entities Id)')),
                ('m_processing_layer_id', models.PositiveIntegerField(null=True, verbose_name='M Processing Layer Id')),
                ('m_processing_sub_layer_id', models.PositiveIntegerField(null=True, verbose_name='M Processing Sub Layer Id')),
                ('processing_layer_id', models.PositiveIntegerField(null=True, verbose_name='Processing Layer Id')),
                ('date', models.CharField(max_length=32, null=True, verbose_name='Date')),
                ('total_debits_gl', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Total Debits GL')),
                ('total_credits_gl', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Total Credits GL')),
                ('gl_opening_balance', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='GL Opening Balance')),
                ('gl_closing_balance', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='GL Closing Balance')),
                ('approved_by', models.PositiveIntegerField(null=True, verbose_name='Approved By')),
                ('approved_date', models.CharField(max_length=64, null=True, verbose_name='Approved Date')),
            ],
            options={
                'db_table': 'daily_balances_gl',
            },
        ),
    ]
