# Generated by Django 3.2 on 2021-06-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleDetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submodules',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='submodules',
            name='sub_module_icon',
            field=models.CharField(max_length=64, null=True, verbose_name='Module Icon'),
        ),
    ]
