# Generated by Django 3.2 on 2021-06-30 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleDetails', '0002_auto_20210629_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userroles',
            old_name='sub_model',
            new_name='main_model',
        ),
    ]
