# Generated by Django 3.2 on 2021-06-30 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleDetails', '0003_rename_sub_model_userroles_main_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userroles',
            old_name='main_model',
            new_name='sub_model',
        ),
    ]
