# Generated by Django 3.1.7 on 2021-07-26 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleDetails', '0005_alter_submodels_sub_model_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterUserFilters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filters', models.CharField(max_length=64, null=True, verbose_name='Filters')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('modified_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified Date')),
            ],
            options={
                'db_table': 'm_user_filters',
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=64, null=True, verbose_name='Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
            ],
            options={
                'db_table': 'types',
            },
        ),
        migrations.CreateModel(
            name='UserFilterAccess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_access', models.BooleanField(default=False, verbose_name='Is Access?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('modified_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified Date')),
                ('m_user_filters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuleDetails.masteruserfilters', verbose_name='M User Filters Id (Auto Generated)')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Users Id (Auto Generated)')),
            ],
            options={
                'db_table': 'user_filter_access',
            },
        ),
        migrations.CreateModel(
            name='ModuleConnections',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('m_processing_layer_id', models.PositiveIntegerField(null=True, verbose_name='Sources - M Processing Layer Id (Auto generated)')),
                ('m_processing_sub_layer_id', models.PositiveIntegerField(null=True, verbose_name='Sources - M Processing Sub Layer Id (Auto Generated)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('modified_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified Date')),
                ('main_modules', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuleDetails.mainmodules', verbose_name='Mail Modules Id (Auto Generated)')),
                ('sub_modules', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuleDetails.submodules', verbose_name='Sub Module Id (Auto Generated)')),
            ],
            options={
                'db_table': 'module_connections',
            },
        ),
        migrations.AddField(
            model_name='users',
            name='types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuleDetails.types', verbose_name='Types Id (Auto Generated)', null=True),
            preserve_default=False,
        ),
    ]
