# Generated by Django 3.1.7 on 2021-07-26 22:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleDetails', '0006_auto_20210726_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleconnections',
            name='m_processing_layer_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Sources - M Processing Layer Id (Auto Generated)'),
        ),
        migrations.CreateModel(
            name='TypeConnections',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('processing_layer_id', models.PositiveIntegerField(null=True, verbose_name='Sources - Processing Layer Id (auto Generated)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('modified_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified Date')),
                ('types_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuleDetails.types', verbose_name='Types Id (Auto Generated)')),
            ],
            options={
                'db_table': 'type_connections',
            },
        ),
    ]
