# Generated by Django 3.1.7 on 2021-07-26 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleDetails', '0007_auto_20210726_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typeconnections',
            old_name='types_id',
            new_name='types',
        ),
    ]
