# Generated by Django 3.1.7 on 2021-07-27 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleDetails', '0008_auto_20210726_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='types',
            name='departments',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='ModuleDetails.departments', verbose_name='Departments Id (Auto Generated)'),
            preserve_default=False,
        ),
    ]
