# Generated by Django 3.1.7 on 2021-07-27 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleDetails', '0009_types_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfilteraccess',
            name='users',
        ),
        migrations.AddField(
            model_name='userfilteraccess',
            name='roles',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='ModuleDetails.roles', verbose_name='Role Id (Auto Generated)'),
            preserve_default=False,
        ),
    ]
