# Generated by Django 3.1.7 on 2021-07-28 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleDetails', '0010_auto_20210727_2310'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TypeConnections',
        ),
    ]
