# Generated by Django 3.2.2 on 2021-05-12 12:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterSources',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenants_id', models.PositiveIntegerField(verbose_name='Tenants Id (Business Module - Tenant Id)')),
                ('groups_id', models.PositiveIntegerField(verbose_name='Groups Id (Business Module - Groups Id)')),
                ('entities_id', models.PositiveIntegerField(verbose_name='Entities Id (Business Module - Entities Id)')),
                ('module_id', models.PositiveIntegerField(verbose_name='Module Id (Business Module - Module Id)')),
                ('source_code', models.CharField(max_length=64, unique=True, verbose_name='Source Code')),
                ('source_name', models.CharField(max_length=64, unique=True, verbose_name='Source Name')),
                ('source_config', models.JSONField(verbose_name='Source Configurations')),
                ('source_input_location', models.CharField(max_length=512, null=True, verbose_name='Source Input Location')),
                ('source_archive_location', models.CharField(max_length=512, null=True, verbose_name='Source Archive Location')),
                ('source_error_location', models.CharField(max_length=512, null=True, verbose_name='Source Error Location')),
                ('source_import_location', models.CharField(max_length=512, null=True, verbose_name='Source Import Location')),
                ('source_import_seq', models.PositiveIntegerField(null=True, verbose_name='Source Import Sequence')),
                ('source_field_number', models.PositiveIntegerField(null=True, verbose_name='Source Field Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('modified_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified Date')),
            ],
            options={
                'db_table': 'm_sources',
            },
        ),
        migrations.CreateModel(
            name='SourceSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenants_id', models.PositiveIntegerField(verbose_name='Tenants Id (Business Module - Tenant Id)')),
                ('groups_id', models.PositiveIntegerField(verbose_name='Groups Id (Business Module - Groups Id)')),
                ('entities_id', models.PositiveIntegerField(verbose_name='Entities Id (Business Module - Entities Id)')),
                ('module_id', models.PositiveIntegerField(verbose_name='Module Id (Business Module - Module Id)')),
                ('setting_key', models.CharField(max_length=64, null=True, verbose_name='Setting Key')),
                ('setting_value', models.JSONField(null=True, verbose_name='Setting Value')),
                ('setting_description', models.TextField(null=True, verbose_name='Setting Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('modified_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified Date')),
            ],
            options={
                'db_table': 'source_settings',
            },
        ),
        migrations.CreateModel(
            name='MasterSourceDefinitions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenants_id', models.PositiveIntegerField(verbose_name='Tenants Id (Business Module - Tenant Id)')),
                ('groups_id', models.PositiveIntegerField(verbose_name='Groups Id (Business Module - Groups Id)')),
                ('entities_id', models.PositiveIntegerField(verbose_name='Entities Id (Business Module - Entities Id)')),
                ('module_id', models.PositiveIntegerField(verbose_name='Module Id (Business Module - Module Id)')),
                ('attribute_name', models.CharField(max_length=64, null=True, verbose_name='Attribute Name')),
                ('attribute_position', models.PositiveIntegerField(null=True, verbose_name='Attribute Position')),
                ('attribute_type', models.CharField(max_length=16, null=True, verbose_name='Attribute Type')),
                ('attribute_data_type', models.CharField(max_length=32, null=True, verbose_name='Attribute Data Type')),
                ('attribute_date_format', models.CharField(max_length=32, null=True, verbose_name='Attribute Date Format')),
                ('attribute_pattern', models.CharField(max_length=128, null=True, verbose_name='Attribute Pattern')),
                ('attribute_enums', models.JSONField(null=True, verbose_name='Attribute Enums')),
                ('attribute_min_length', models.PositiveIntegerField(null=True, verbose_name='Attribute Minimum Length')),
                ('attribute_max_length', models.PositiveIntegerField(null=True, verbose_name='Attribute Maximum Length')),
                ('attribute_default_value', models.CharField(max_length=512, null=True, verbose_name='Attribute Default Value')),
                ('attribute_formula', models.CharField(max_length=128, null=True, verbose_name='Attribute Formula')),
                ('attribute_reference_field', models.CharField(max_length=64, null=True, verbose_name='Attribute Reference Field')),
                ('attribute_reference_table', models.CharField(max_length=64, null=True, verbose_name='Attribute Reference Table')),
                ('attribute_reference_data_type', models.CharField(max_length=64, null=True, verbose_name='Attribute Reference Date Type')),
                ('file_reference_field', models.CharField(max_length=256, null=True, verbose_name='File Reference Field')),
                ('is_validate', models.BooleanField(default=False, verbose_name='To be Validated or not')),
                ('is_required', models.BooleanField(default=True, verbose_name='Required ?')),
                ('is_unique', models.BooleanField(default=False, verbose_name='Unique ?')),
                ('is_editable', models.BooleanField(default=False, verbose_name='Editable ?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_by', models.PositiveSmallIntegerField(null=True, verbose_name='Business Module - User Id')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('modified_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified Date')),
                ('m_sources_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.mastersources', verbose_name='MasterSources Id (Auto Generated)')),
            ],
            options={
                'db_table': 'm_source_definitions',
            },
        ),
    ]
