# Generated by Django 3.2.2 on 2021-05-14 10:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastersourcedefinitions',
            name='module_id',
        ),
        migrations.RemoveField(
            model_name='mastersources',
            name='module_id',
        ),
        migrations.RemoveField(
            model_name='sourcesettings',
            name='module_id',
        ),
        migrations.CreateModel(
            name='SourceQueries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenants_id', models.PositiveIntegerField(verbose_name='Tenants Id (Business Module - Tenant Id)')),
                ('groups_id', models.PositiveIntegerField(verbose_name='Groups Id (Business Module - Groups Id)')),
                ('entities_id', models.PositiveIntegerField(verbose_name='Entities Id (Business Module - Entities Id)')),
                ('source_key', models.CharField(max_length=64, null=True, verbose_name='Source Setting')),
                ('source_value', models.TextField(null=True, verbose_name='Source Key')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_by', models.PositiveSmallIntegerField(null=True, verbose_name='Business Module - User Id')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('modified_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified Date')),
                ('m_sources', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.mastersources', verbose_name='MasterSources Id (Auto Generated)')),
            ],
            options={
                'db_table': 'source_queries',
            },
        ),
        migrations.CreateModel(
            name='MasterSourceFileUploads',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenants_id', models.PositiveIntegerField(verbose_name='Tenants Id (Business Module - Tenant Id)')),
                ('groups_id', models.PositiveIntegerField(verbose_name='Groups Id (Business Module - Groups Id)')),
                ('entities_id', models.PositiveIntegerField(verbose_name='Entities Id (Business Module - Entities Id)')),
                ('file_name', models.CharField(max_length=128, null=True, verbose_name='File Name')),
                ('file_size_bytes', models.PositiveIntegerField(null=True, verbose_name='File Size Bytes')),
                ('file_path', models.CharField(max_length=512, null=True, verbose_name='File Path')),
                ('status', models.CharField(max_length=32, null=True, verbose_name='Status')),
                ('comments', models.TextField(null=True, verbose_name='Comments')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('modified_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified Date')),
                ('m_sources_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.mastersources', verbose_name='MasterSources Id (Auto Generated)')),
            ],
            options={
                'db_table': 'm_source_file_uploads',
            },
        ),
    ]
