# Generated by Django 3.2.2 on 2021-05-14 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0002_auto_20210514_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mastersourcefileuploads',
            old_name='m_sources_id',
            new_name='m_sources',
        ),
    ]
