# Generated by Django 3.2.2 on 2021-05-16 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0004_auto_20210516_2118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MasterTransformationsOperators',
        ),
        migrations.DeleteModel(
            name='TransformationsFields',
        ),
    ]
