# Generated by Django 3.2.2 on 2021-05-25 05:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0006_mastertransformationsoperators'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterSourcesAudit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('operation_flag', models.CharField(max_length=512, verbose_name='Audit Flag')),
                ('tenants_id', models.PositiveIntegerField(verbose_name='Tenants Id (Business Module - Tenant Id)')),
                ('groups_id', models.PositiveIntegerField(verbose_name='Groups Id (Business Module - Groups Id)')),
                ('entities_id', models.PositiveIntegerField(verbose_name='Entities Id (Business Module - Entities Id)')),
                ('m_sources_id', models.PositiveIntegerField(verbose_name='Master Source Id')),
                ('source_code', models.CharField(max_length=64, unique=True, verbose_name='Source Code')),
                ('source_name', models.CharField(max_length=64, unique=True, verbose_name='Source Name')),
                ('source_config', models.JSONField(verbose_name='Source Configurations')),
                ('source_input_location', models.CharField(max_length=512, null=True, verbose_name='Source Input Location')),
                ('source_archive_location', models.CharField(max_length=512, null=True, verbose_name='Source Archive Location')),
                ('source_error_location', models.CharField(max_length=512, null=True, verbose_name='Source Error Location')),
                ('source_import_location', models.CharField(max_length=512, null=True, verbose_name='Source Import Location')),
                ('source_import_seq', models.PositiveIntegerField(null=True, verbose_name='Source Import Sequence')),
                ('source_field_number', models.PositiveIntegerField(null=True, verbose_name='Source Field Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
            ],
            options={
                'db_table': 'm_sources_audit',
            },
        ),
        migrations.DeleteModel(
            name='MasterAggregators',
        ),
        migrations.DeleteModel(
            name='MasterAggregatorsDetails',
        ),
        migrations.DeleteModel(
            name='MasterAggregatorsQueries',
        ),
        migrations.DeleteModel(
            name='MasterTransformations',
        ),
        migrations.DeleteModel(
            name='MasterTransformationsOperators',
        ),
        migrations.RenameField(
            model_name='mastersourcedefinitions',
            old_name='m_sources_id',
            new_name='m_sources',
        ),
    ]
