# Generated by Django 3.2.2 on 2021-05-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0007_auto_20210525_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastersourcedefinitions',
            name='attribute_default_value',
        ),
        migrations.RemoveField(
            model_name='mastersourcedefinitions',
            name='attribute_reference_data_type',
        ),
        migrations.RemoveField(
            model_name='mastersourcedefinitions',
            name='attribute_type',
        ),
        migrations.RemoveField(
            model_name='mastersourcedefinitions',
            name='file_reference_field',
        ),
        migrations.AddField(
            model_name='sourcequeries',
            name='description',
            field=models.TextField(null=True, verbose_name='Setting Description'),
        ),
    ]
