# Generated by Django 3.2.2 on 2021-05-26 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0009_masteraggregators'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MasterAggregators',
        ),
    ]
