# Generated by Django 3.2.2 on 2021-05-26 16:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0011_masteraggregators'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterAggregatorsDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenants_id', models.PositiveIntegerField(verbose_name='Tenants Id (Business Module - Tenant Id)')),
                ('groups_id', models.PositiveIntegerField(verbose_name='Groups Id (Business Module - Groups Id)')),
                ('entities_id', models.PositiveIntegerField(verbose_name='Entities Id (Business Module - Entities Id)')),
                ('is_base_source', models.BooleanField(default=True, verbose_name='Base ?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('modified_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified Date')),
                ('m_aggregator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.masteraggregators', verbose_name='MasterAggregator Id (Auto Generated)')),
                ('m_sources', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.mastersources', verbose_name='MasterSources Id (Auto Generated)')),
            ],
            options={
                'db_table': 'm_aggregator_details',
            },
        ),
    ]
