# Generated by Django 3.2.2 on 2021-05-27 10:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0013_aggregatorsqueries'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterTransformations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenants_id', models.PositiveIntegerField(verbose_name='Tenants Id (Business Module - Tenant Id)')),
                ('groups_id', models.PositiveIntegerField(verbose_name='Groups Id (Business Module - Groups Id)')),
                ('entities_id', models.PositiveIntegerField(verbose_name='Entities Id (Business Module - Entities Id)')),
                ('transformation_name', models.CharField(max_length=64, null=True, verbose_name='Transformation Name')),
                ('transformation_description', models.TextField(null=True, verbose_name='Transformation Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('modified_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified Date')),
                ('m_sources', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.mastersources', verbose_name='MasterSources Id (Auto Generated)')),
            ],
            options={
                'db_table': 'm_transformations',
            },
        ),
    ]
