# Generated by Django 3.2 on 2021-06-05 07:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0016_mastertransformationsoperators'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransformationsFields',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenants_id', models.PositiveIntegerField(verbose_name='Tenants Id (Business Module - Tenant Id)')),
                ('groups_id', models.PositiveIntegerField(verbose_name='Groups Id (Business Module - Groups Id)')),
                ('entities_id', models.PositiveIntegerField(verbose_name='Entities Id (Business Module - Entities Id)')),
                ('transformation_name', models.CharField(max_length=64, null=True, verbose_name='Setting Key')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('modified_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified Date')),
                ('m_transformations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.mastertransformations', verbose_name='MasterTransformations Id (Auto Generated)')),
            ],
            options={
                'db_table': 'transformation_fields',
            },
        ),
        migrations.CreateModel(
            name='LookupExtraction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenants_id', models.PositiveIntegerField(verbose_name='Tenants Id (Business Module - Tenant Id)')),
                ('groups_id', models.PositiveIntegerField(verbose_name='Groups Id (Business Module - Groups Id)')),
                ('entities_id', models.PositiveIntegerField(verbose_name='Entities Id (Business Module - Entities Id)')),
                ('sequence', models.PositiveIntegerField(null=True, verbose_name='Sequence')),
                ('base_source_name', models.CharField(max_length=64, null=True, verbose_name='Base Source Name')),
                ('lookup_field_name', models.CharField(max_length=64, null=True, verbose_name='Lookup Field Name')),
                ('extraction_source_name', models.CharField(max_length=64, null=True, verbose_name='Extraction Source Name')),
                ('extraction_field_name', models.CharField(max_length=64, null=True, verbose_name='Extraction Field Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_by', models.PositiveSmallIntegerField(null=True, verbose_name='Business Module - User Id')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('modified_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified Date')),
                ('base_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_source', to='source.mastersources', verbose_name='MasterSources Id (Auto Generated)')),
                ('extraction_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_field', to='source.mastersourcedefinitions', verbose_name='MasterSourcesDefinition Id (Auto Generated)')),
                ('extraction_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.mastersources', verbose_name='MasterSources Id (Auto Generated)')),
                ('lookup_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lookup_field', to='source.mastersourcedefinitions', verbose_name='MasterSourcesDefinition Id (Auto Generated)')),
                ('m_aggregator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.masteraggregators', verbose_name='Master Aggregator Id (Auto Generated)')),
                ('transformation_fields', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.transformationsfields', verbose_name='Transformations Fields Id (Auto Generated)')),
            ],
            options={
                'db_table': 'lookup_extraction',
            },
        ),
        migrations.CreateModel(
            name='FieldExtraction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenants_id', models.PositiveIntegerField(verbose_name='Tenants Id (Business Module - Tenant Id)')),
                ('groups_id', models.PositiveIntegerField(verbose_name='Groups Id (Business Module - Groups Id)')),
                ('entities_id', models.PositiveIntegerField(verbose_name='Entities Id (Business Module - Entities Id)')),
                ('attribute_name', models.CharField(max_length=64, null=True, verbose_name='Attribute Name')),
                ('pattern_type', models.CharField(max_length=16, null=True, verbose_name='Attribute Type')),
                ('pattern_input', models.CharField(max_length=32, null=True, verbose_name='Attribute Data Type')),
                ('transaction_placed', models.CharField(max_length=32, null=True, verbose_name='Attribute Date Format')),
                ('transaction_reference', models.CharField(max_length=128, null=True, verbose_name='Attribute Pattern')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_by', models.PositiveSmallIntegerField(null=True, verbose_name='Business Module - User Id')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('modified_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified Date')),
                ('m_aggregators', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.masteraggregators', verbose_name='Master Aggregator Id')),
                ('m_source_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.mastersourcedefinitions', verbose_name='MasterSourcesDefinition Id (Auto Generated)')),
                ('m_sources', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.mastersources', verbose_name='MasterSources Id (Auto Generated)')),
                ('transformation_fields', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.transformationsfields', verbose_name='Transformations Fields Id (Auto Generated)')),
            ],
            options={
                'db_table': 'field_extraction',
            },
        ),
    ]
