# Generated by Django 3.2 on 2021-06-05 15:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0017_fieldextraction_lookupextraction_transformationsfields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterProcessingLayer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenants_id', models.PositiveIntegerField(verbose_name='Tenants Id (Business Module - Tenant Id)')),
                ('groups_id', models.PositiveIntegerField(verbose_name='Groups Id (Business Module - Groups Id)')),
                ('entities_id', models.PositiveIntegerField(verbose_name='Entities Id (Business Module - Entities Id)')),
                ('processing_layer_code', models.CharField(max_length=64, null=True, verbose_name='Transformation Name')),
                ('processing_layer_name', models.CharField(max_length=64, null=True, verbose_name='Transformation Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('modified_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified Date')),
            ],
            options={
                'db_table': 'm_processing_layer',
            },
        ),
        migrations.CreateModel(
            name='MasterProcessingSubLayer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenants_id', models.PositiveIntegerField(verbose_name='Tenants Id (Business Module - Tenant Id)')),
                ('groups_id', models.PositiveIntegerField(verbose_name='Groups Id (Business Module - Groups Id)')),
                ('entities_id', models.PositiveIntegerField(verbose_name='Entities Id (Business Module - Entities Id)')),
                ('sub_layer_code', models.CharField(max_length=64, null=True, verbose_name='Transformation Name')),
                ('sub_layer_name', models.CharField(max_length=64, null=True, verbose_name='Transformation Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('modified_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified Date')),
                ('m_processing_layer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.masterprocessinglayer', verbose_name='MasterProcessingLayer Id (Auto Generated)')),
            ],
            options={
                'db_table': 'm_processing_sub_layer',
            },
        ),
        migrations.CreateModel(
            name='ProcessingLayer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenants_id', models.PositiveIntegerField(verbose_name='Tenants Id (Business Module - Tenant Id)')),
                ('groups_id', models.PositiveIntegerField(verbose_name='Groups Id (Business Module - Groups Id)')),
                ('entities_id', models.PositiveIntegerField(verbose_name='Entities Id (Business Module - Entities Id)')),
                ('name', models.CharField(max_length=64, null=True, unique=True, verbose_name='Transformation Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('modified_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified Date')),
                ('m_processing_layer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.masterprocessinglayer', verbose_name='MasterProcessingLayer Id (Auto Generated)')),
                ('m_processing_sub_layer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.masterprocessingsublayer', verbose_name='MasterProcessingSubLayer Id (Auto Generated)')),
            ],
            options={
                'db_table': 'processing_layer',
            },
        ),
        migrations.CreateModel(
            name='ProcessingLayerDefinition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenants_id', models.PositiveIntegerField(verbose_name='Tenants Id (Business Module - Tenant Id)')),
                ('groups_id', models.PositiveIntegerField(verbose_name='Groups Id (Business Module - Groups Id)')),
                ('entities_id', models.PositiveIntegerField(verbose_name='Entities Id (Business Module - Entities Id)')),
                ('side', models.CharField(max_length=64, null=True, unique=True, verbose_name='Transformation Name')),
                ('side_name', models.CharField(max_length=64, null=True, unique=True, verbose_name='Transformation Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('modified_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified Date')),
                ('m_aggregators_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.masteraggregators', verbose_name='MasterAggregator Id (Auto Generated)')),
                ('processing_layer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.processinglayer', verbose_name='ProcessingLayer Id (Auto Generated)')),
            ],
            options={
                'db_table': 'processing_layer_definition',
            },
        ),
    ]
