# Generated by Django 3.2 on 2021-06-05 15:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0018_masterprocessinglayer_masterprocessingsublayer_processinglayer_processinglayerdefinition'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterRuleCategories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenants_id', models.PositiveIntegerField(verbose_name='Tenants Id (Business Module - Tenant Id)')),
                ('groups_id', models.PositiveIntegerField(verbose_name='Groups Id (Business Module - Groups Id)')),
                ('entities_id', models.PositiveIntegerField(verbose_name='Entities Id (Business Module - Entities Id)')),
                ('rule_category', models.CharField(max_length=64, null=True, verbose_name='Transformation Name')),
                ('rule_category_description', models.TextField(null=True, verbose_name='Transformation Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('modified_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified Date')),
            ],
            options={
                'db_table': 'm_rule_categories',
            },
        ),
        migrations.CreateModel(
            name='MasterRuleType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenants_id', models.PositiveIntegerField(verbose_name='Tenants Id (Business Module - Tenant Id)')),
                ('groups_id', models.PositiveIntegerField(verbose_name='Groups Id (Business Module - Groups Id)')),
                ('entities_id', models.PositiveIntegerField(verbose_name='Entities Id (Business Module - Entities Id)')),
                ('rule_type', models.CharField(max_length=64, null=True, verbose_name='Transformation Name')),
                ('rule_type_description', models.CharField(max_length=64, null=True, verbose_name='Transformation Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('modified_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified Date')),
            ],
            options={
                'db_table': 'm_rule_type',
            },
        ),
        migrations.CreateModel(
            name='BusinessLayer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenants_id', models.PositiveIntegerField(verbose_name='Tenants Id (Business Module - Tenant Id)')),
                ('groups_id', models.PositiveIntegerField(verbose_name='Groups Id (Business Module - Groups Id)')),
                ('entities_id', models.PositiveIntegerField(verbose_name='Entities Id (Business Module - Entities Id)')),
                ('processing_layer_name', models.CharField(max_length=64, verbose_name='ProcessingLayer Name')),
                ('rule_set_name', models.CharField(max_length=64, null=True, verbose_name='RuleSet Name')),
                ('execution_sequence', models.PositiveIntegerField(verbose_name='RuleCategory Name')),
                ('execution_sub_sequence', models.PositiveIntegerField(verbose_name='RuleCategory Name')),
                ('rule_name', models.CharField(max_length=64, null=True, verbose_name='Rule Name')),
                ('rule_description', models.TextField(null=True, verbose_name='Rule Name')),
                ('match_type', models.CharField(max_length=64, null=True, verbose_name='Rule Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('modified_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified Date')),
                ('m_rule_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.masterrulecategories', verbose_name='RuleCategory Id (Auto Generated)')),
                ('processing_layer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.processinglayer', verbose_name='ProcessingLayer Id (Auto Generated)')),
                ('rule_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.masterruletype', verbose_name='RuleType Id (Auto Generated)')),
            ],
            options={
                'db_table': 'business_layer',
            },
        ),
    ]
