# Generated by Django 3.2 on 2021-06-05 15:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0019_businesslayer_masterrulecategories_masterruletype'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLayerDefinition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenants_id', models.PositiveIntegerField(verbose_name='Tenants Id (Business Module - Tenant Id)')),
                ('groups_id', models.PositiveIntegerField(verbose_name='Groups Id (Business Module - Groups Id)')),
                ('entities_id', models.PositiveIntegerField(verbose_name='Entities Id (Business Module - Entities Id)')),
                ('processing_layer_name', models.CharField(max_length=64, verbose_name='PL Side Name')),
                ('rule_set_name', models.CharField(max_length=64, verbose_name='Rule Set Name')),
                ('rule_name', models.CharField(max_length=64, verbose_name='Rule Name')),
                ('factor_type', models.CharField(max_length=64, verbose_name='Date Name')),
                ('internal_field', models.CharField(max_length=64, verbose_name='Rule Name')),
                ('external_field', models.CharField(max_length=64, verbose_name='Rule Name')),
                ('condition', models.CharField(max_length=64, verbose_name='Rule Name')),
                ('date_tolerance', models.PositiveIntegerField(verbose_name='Tenants Id (Business Module - Tenant Id)')),
                ('amount_tolerance', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Tenants Id (Business Module - Tenant Id)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('modified_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified Date')),
                ('business_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.businesslayer', verbose_name='BusinessLayer Id (Auto Generated)')),
                ('processing_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.processinglayer', verbose_name='ProcessingLayer Id (Auto Generated)')),
            ],
            options={
                'db_table': 'business_layer_definition',
            },
        ),
    ]
