# Generated by Django 3.2 on 2021-06-08 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0020_businesslayerdefinition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldextraction',
            name='m_aggregators',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_aggregators', to='source.masteraggregators', verbose_name='Master Aggregator Id'),
        ),
        migrations.AlterField(
            model_name='fieldextraction',
            name='m_source_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_source_definition', to='source.mastersourcedefinitions', verbose_name='MasterSourcesDefinition Id (Auto Generated)'),
        ),
        migrations.AlterField(
            model_name='fieldextraction',
            name='m_sources',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_sources', to='source.mastersources', verbose_name='MasterSources Id (Auto Generated)'),
        ),
        migrations.AlterField(
            model_name='fieldextraction',
            name='transformation_fields',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformation_fields', to='source.transformationsfields', verbose_name='Transformations Fields Id (Auto Generated)'),
        ),
    ]
