# Generated by Django 3.2 on 2021-06-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0021_auto_20210608_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterprocessingsublayer',
            old_name='m_processing_layer_id',
            new_name='m_processing_layer',
        ),
        migrations.RemoveField(
            model_name='fieldextraction',
            name='m_aggregators',
        ),
        migrations.RemoveField(
            model_name='fieldextraction',
            name='m_source_definition',
        ),
        migrations.RemoveField(
            model_name='fieldextraction',
            name='m_sources',
        ),
        migrations.RemoveField(
            model_name='fieldextraction',
            name='transformation_fields',
        ),
        migrations.AddField(
            model_name='fieldextraction',
            name='m_aggregators_id',
            field=models.PositiveIntegerField(default=0, verbose_name='Agggregator Id(m_aggregator_id)'),
        ),
        migrations.AddField(
            model_name='fieldextraction',
            name='m_source_definition_id',
            field=models.PositiveIntegerField(default=0, verbose_name='Source Definition Id (m_source_definiton_id)'),
        ),
        migrations.AddField(
            model_name='fieldextraction',
            name='m_sources_id',
            field=models.PositiveIntegerField(default=0, verbose_name='Entities Id (Business Module - Entities Id)'),
        ),
        migrations.AddField(
            model_name='fieldextraction',
            name='transformation_fields_id',
            field=models.PositiveIntegerField(default=0, verbose_name='Transformation Field Id(m_transformations)'),
        ),
    ]
