# Generated by Django 3.2 on 2021-06-08 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0022_auto_20210608_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processinglayerdefinition',
            old_name='m_aggregators_id',
            new_name='m_aggregators',
        ),
        migrations.RenameField(
            model_name='processinglayerdefinition',
            old_name='processing_layer_id',
            new_name='processing_layer',
        ),
    ]
