# Generated by Django 3.2 on 2021-06-08 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0023_auto_20210608_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processinglayer',
            old_name='m_processing_layer_id',
            new_name='m_processing_layer',
        ),
        migrations.RenameField(
            model_name='processinglayer',
            old_name='m_processing_sub_layer_id',
            new_name='m_processing_sub_layer',
        ),
    ]
