# Generated by Django 3.2 on 2021-06-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0025_auto_20210608_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processinglayerdefinition',
            name='side',
            field=models.CharField(max_length=64, null=True, verbose_name='Transformation Name'),
        ),
    ]
