# Generated by Django 3.2 on 2021-06-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0027_alter_businesslayer_processing_layer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesslayerdefinition',
            name='business_layer',
        ),
        migrations.RemoveField(
            model_name='businesslayerdefinition',
            name='processing_layer',
        ),
        migrations.AddField(
            model_name='businesslayerdefinition',
            name='business_laye_id',
            field=models.PositiveIntegerField(default=0, verbose_name='BusinessLayer Id (Auto Generated)'),
        ),
        migrations.AddField(
            model_name='businesslayerdefinition',
            name='processing_layer_id',
            field=models.PositiveIntegerField(default=0, verbose_name='ProcessingLayer Id (Auto Generated)'),
        ),
    ]
