# Generated by Django 3.2 on 2021-06-13 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0028_auto_20210613_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesslayerdefinition',
            old_name='business_laye_id',
            new_name='business_layer_id',
        ),
    ]
