# Generated by Django 3.1.7 on 2021-07-27 18:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0029_rename_business_laye_id_businesslayerdefinition_business_layer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeConnections',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('types_id', models.PositiveIntegerField(null=True, verbose_name='Sources - Types Id (Auto Generated)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('modified_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified Date')),
                ('processing_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.processinglayer', verbose_name='Processing Layer Id (Auto Generated)')),
            ],
            options={
                'db_table': 'type_connections',
            },
        ),
    ]
